// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &dhcpOdhcpdDataSource{}
	_ datasource.DataSourceWithConfigure = &dhcpOdhcpdDataSource{}
)

type dhcpOdhcpdDataSource struct{ client *client.Client }

func NewDhcpOdhcpdDataSource() datasource.DataSource { return &dhcpOdhcpdDataSource{} }

func (d *dhcpOdhcpdDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dhcp_odhcpd"
}

func (d *dhcpOdhcpdDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *dhcpOdhcpdDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the odhcpd settings.",
		Attributes: map[string]dsschema.Attribute{
			"id":           dsComputedString("Stable id."),
			"managed":      dsManagedAttribute(),
			"etag":         dsComputedString("Opaque ETag of the resource's current state."),
			"leasefile":    dsComputedString("uci option leasefile."),
			"leasetrigger": dsComputedString("uci option leasetrigger."),
			"loglevel":     dsComputedInt64("uci option loglevel."),
			"maindhcp":     dsComputedBool("uci option maindhcp."),
		},
	}
}

func (d *dhcpOdhcpdDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m dhcpOdhcpdModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, dhcpOdhcpdPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading odhcpd settings", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("odhcpd settings not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&dhcpOdhcpdResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
