// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &dhcpDnsmasqDataSource{}
	_ datasource.DataSourceWithConfigure = &dhcpDnsmasqDataSource{}
)

type dhcpDnsmasqDataSource struct{ client *client.Client }

func NewDhcpDnsmasqDataSource() datasource.DataSource { return &dhcpDnsmasqDataSource{} }

func (d *dhcpDnsmasqDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dhcp_dnsmasq"
}

func (d *dhcpDnsmasqDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *dhcpDnsmasqDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the dnsmasq settings.",
		Attributes: map[string]dsschema.Attribute{
			"id":                dsComputedString("Stable id."),
			"managed":           dsManagedAttribute(),
			"etag":              dsComputedString("Opaque ETag of the resource's current state."),
			"address":           dsComputedStringList("uci option address."),
			"authoritative":     dsComputedBool("uci option authoritative."),
			"boguspriv":         dsComputedBool("uci option boguspriv."),
			"cachesize":         dsComputedInt64("uci option cachesize."),
			"domain":            dsComputedString("uci option domain."),
			"domainneeded":      dsComputedBool("uci option domainneeded."),
			"expandhosts":       dsComputedBool("uci option expandhosts."),
			"filterwin2k":       dsComputedBool("uci option filterwin2k."),
			"leasefile":         dsComputedString("uci option leasefile."),
			"local":             dsComputedString("uci option local."),
			"nonwildcard":       dsComputedBool("uci option nonwildcard."),
			"noresolv":          dsComputedBool("uci option noresolv."),
			"port":              dsComputedInt64("uci option port."),
			"readethers":        dsComputedBool("uci option readethers."),
			"rebind_protection": dsComputedBool("uci option rebind_protection."),
			"resolvfile":        dsComputedString("uci option resolvfile."),
			"server":            dsComputedStringList("uci option server."),
		},
	}
}

func (d *dhcpDnsmasqDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m dhcpDnsmasqModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, dhcpDnsmasqPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading dnsmasq settings", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("dnsmasq settings not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&dhcpDnsmasqResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
