// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const dhcpDnsmasqPath = "/dhcp/dnsmasq"

var (
	_ resource.Resource                = &dhcpDnsmasqResource{}
	_ resource.ResourceWithConfigure   = &dhcpDnsmasqResource{}
	_ resource.ResourceWithImportState = &dhcpDnsmasqResource{}
)

type dhcpDnsmasqResource struct{ client *client.Client }

func NewDhcpDnsmasqResource() resource.Resource { return &dhcpDnsmasqResource{} }

type dhcpDnsmasqModel struct {
	ID               types.String `tfsdk:"id"`
	Managed          types.Bool   `tfsdk:"managed"`
	ETag             types.String `tfsdk:"etag"`
	Address          types.List   `tfsdk:"address"`
	Authoritative    types.Bool   `tfsdk:"authoritative"`
	Boguspriv        types.Bool   `tfsdk:"boguspriv"`
	Cachesize        types.Int64  `tfsdk:"cachesize"`
	Domain           types.String `tfsdk:"domain"`
	Domainneeded     types.Bool   `tfsdk:"domainneeded"`
	Expandhosts      types.Bool   `tfsdk:"expandhosts"`
	Filterwin2k      types.Bool   `tfsdk:"filterwin2k"`
	Leasefile        types.String `tfsdk:"leasefile"`
	Local            types.String `tfsdk:"local"`
	Nonwildcard      types.Bool   `tfsdk:"nonwildcard"`
	Noresolv         types.Bool   `tfsdk:"noresolv"`
	Port             types.Int64  `tfsdk:"port"`
	Readethers       types.Bool   `tfsdk:"readethers"`
	RebindProtection types.Bool   `tfsdk:"rebind_protection"`
	Resolvfile       types.String `tfsdk:"resolvfile"`
	Server           types.List   `tfsdk:"server"`
}

func (r *dhcpDnsmasqResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dhcp_dnsmasq"
}

func (r *dhcpDnsmasqResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *dhcpDnsmasqResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A dnsmasq settings.",
		Attributes: map[string]schema.Attribute{
			"id":                computedIDAttribute(),
			"managed":           managedAttribute(),
			"etag":              etagAttribute(),
			"address":           optionalComputedStringList("uci option address."),
			"authoritative":     optionalComputedBool("uci option authoritative."),
			"boguspriv":         optionalComputedBool("uci option boguspriv."),
			"cachesize":         optionalComputedInt64("uci option cachesize."),
			"domain":            optionalComputedString("uci option domain."),
			"domainneeded":      optionalComputedBool("uci option domainneeded."),
			"expandhosts":       optionalComputedBool("uci option expandhosts."),
			"filterwin2k":       optionalComputedBool("uci option filterwin2k."),
			"leasefile":         optionalComputedString("uci option leasefile."),
			"local":             optionalComputedString("uci option local."),
			"nonwildcard":       optionalComputedBool("uci option nonwildcard."),
			"noresolv":          optionalComputedBool("uci option noresolv."),
			"port":              optionalComputedInt64("uci option port."),
			"readethers":        optionalComputedBool("uci option readethers."),
			"rebind_protection": optionalComputedBool("uci option rebind_protection."),
			"resolvfile":        optionalComputedString("uci option resolvfile."),
			"server":            optionalComputedStringList("uci option server."),
		},
	}
}

func (r *dhcpDnsmasqResource) body(ctx context.Context, m dhcpDnsmasqModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putList(ctx, out, "address", m.Address, diags.d)
	putBool(out, "authoritative", m.Authoritative)
	putBool(out, "boguspriv", m.Boguspriv)
	putInt64(out, "cachesize", m.Cachesize)
	putStr(out, "domain", m.Domain)
	putBool(out, "domainneeded", m.Domainneeded)
	putBool(out, "expandhosts", m.Expandhosts)
	putBool(out, "filterwin2k", m.Filterwin2k)
	putStr(out, "leasefile", m.Leasefile)
	putStr(out, "local", m.Local)
	putBool(out, "nonwildcard", m.Nonwildcard)
	putBool(out, "noresolv", m.Noresolv)
	putInt64(out, "port", m.Port)
	putBool(out, "readethers", m.Readethers)
	putBool(out, "rebind_protection", m.RebindProtection)
	putStr(out, "resolvfile", m.Resolvfile)
	putList(ctx, out, "server", m.Server, diags.d)
	return out
}

func (r *dhcpDnsmasqResource) read(ctx context.Context, obj map[string]any, m *dhcpDnsmasqModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Address = diags.list(listVal(ctx, obj, "address"))
	m.Authoritative = boolVal(obj, "authoritative")
	m.Boguspriv = boolVal(obj, "boguspriv")
	m.Cachesize = int64Val(obj, "cachesize")
	m.Domain = strVal(obj, "domain")
	m.Domainneeded = boolVal(obj, "domainneeded")
	m.Expandhosts = boolVal(obj, "expandhosts")
	m.Filterwin2k = boolVal(obj, "filterwin2k")
	m.Leasefile = strVal(obj, "leasefile")
	m.Local = strVal(obj, "local")
	m.Nonwildcard = boolVal(obj, "nonwildcard")
	m.Noresolv = boolVal(obj, "noresolv")
	m.Port = int64Val(obj, "port")
	m.Readethers = boolVal(obj, "readethers")
	m.RebindProtection = boolVal(obj, "rebind_protection")
	m.Resolvfile = strVal(obj, "resolvfile")
	m.Server = diags.list(listVal(ctx, obj, "server"))
}

func (r *dhcpDnsmasqResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dhcpDnsmasqModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, dhcpDnsmasqPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "dnsmasq settings", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dhcpDnsmasqResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dhcpDnsmasqModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, dhcpDnsmasqPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading dnsmasq settings", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dhcpDnsmasqResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state dhcpDnsmasqModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, dhcpDnsmasqPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "dnsmasq settings", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *dhcpDnsmasqResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *dhcpDnsmasqResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
