// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &dhcpServerDataSource{}
	_ datasource.DataSourceWithConfigure = &dhcpServerDataSource{}
)

type dhcpServerDataSource struct{ client *client.Client }

func NewDhcpServerDataSource() datasource.DataSource { return &dhcpServerDataSource{} }

func (d *dhcpServerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dhcp_server"
}

func (d *dhcpServerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *dhcpServerDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the dhcp server.",
		Attributes: map[string]dsschema.Attribute{
			"id":          dsIDAttribute(),
			"managed":     dsManagedAttribute(),
			"etag":        dsComputedString("Opaque ETag of the resource's current state."),
			"dhcp_option": dsComputedStringList("uci option dhcp_option."),
			"dhcpv6":      dsComputedString("uci option dhcpv6."),
			"domain":      dsComputedString("uci option domain."),
			"dynamicdhcp": dsComputedBool("uci option dynamicdhcp."),
			"force":       dsComputedBool("uci option force."),
			"ignore":      dsComputedBool("uci option ignore."),
			"interface":   dsComputedString("Network interface this entry applies to."),
			"leasetime":   dsComputedString("uci option leasetime."),
			"limit":       dsComputedInt64("uci option limit."),
			"ra":          dsComputedString("uci option ra."),
			"ra_default":  dsComputedInt64("uci option ra_default."),
			"start":       dsComputedInt64("uci option start."),
		},
	}
}

func (d *dhcpServerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m dhcpServerModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+dhcpServerCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading dhcp server", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("dhcp server not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&dhcpServerResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
