// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &dhcpHostDataSource{}
	_ datasource.DataSourceWithConfigure = &dhcpHostDataSource{}
)

type dhcpHostDataSource struct{ client *client.Client }

func NewDhcpHostDataSource() datasource.DataSource { return &dhcpHostDataSource{} }

func (d *dhcpHostDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dhcp_host"
}

func (d *dhcpHostDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *dhcpHostDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the dhcp host.",
		Attributes: map[string]dsschema.Attribute{
			"id":          dsIDAttribute(),
			"managed":     dsManagedAttribute(),
			"etag":        dsComputedString("Opaque ETag of the resource's current state."),
			"broadcast":   dsComputedBool("uci option broadcast."),
			"dns":         dsComputedBool("uci option dns."),
			"duid":        dsComputedString("uci option duid."),
			"hostid":      dsComputedString("uci option hostid."),
			"instance":    dsComputedString("uci option instance."),
			"ip":          dsComputedString("uci option ip."),
			"leasetime":   dsComputedString("uci option leasetime."),
			"mac":         dsComputedString("uci option mac."),
			"mac_aliases": dsComputedStringList("uci option mac_aliases."),
			"name":        dsComputedString("Optional section name."),
			"tag":         dsComputedString("uci option tag."),
		},
	}
}

func (d *dhcpHostDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m dhcpHostModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+dhcpHostCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading dhcp host", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("dhcp host not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&dhcpHostResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
