// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const dhcpHostCollection = "dhcp/hosts"

var (
	_ resource.Resource                = &dhcpHostResource{}
	_ resource.ResourceWithConfigure   = &dhcpHostResource{}
	_ resource.ResourceWithImportState = &dhcpHostResource{}
)

type dhcpHostResource struct{ client *client.Client }

func NewDhcpHostResource() resource.Resource { return &dhcpHostResource{} }

type dhcpHostModel struct {
	ID         types.String `tfsdk:"id"`
	Managed    types.Bool   `tfsdk:"managed"`
	ETag       types.String `tfsdk:"etag"`
	Broadcast  types.Bool   `tfsdk:"broadcast"`
	Dns        types.Bool   `tfsdk:"dns"`
	Duid       types.String `tfsdk:"duid"`
	Hostid     types.String `tfsdk:"hostid"`
	Instance   types.String `tfsdk:"instance"`
	Ip         types.String `tfsdk:"ip"`
	Leasetime  types.String `tfsdk:"leasetime"`
	Mac        types.String `tfsdk:"mac"`
	MacAliases types.List   `tfsdk:"mac_aliases"`
	Name       types.String `tfsdk:"name"`
	Tag        types.String `tfsdk:"tag"`
}

func (r *dhcpHostResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dhcp_host"
}

func (r *dhcpHostResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *dhcpHostResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A dhcp host.",
		Attributes: map[string]schema.Attribute{
			"id":          computedIDAttribute(),
			"managed":     managedAttribute(),
			"etag":        etagAttribute(),
			"broadcast":   optionalComputedBool("uci option broadcast."),
			"dns":         optionalComputedBool("uci option dns."),
			"duid":        optionalComputedString("uci option duid."),
			"hostid":      optionalComputedString("uci option hostid."),
			"instance":    optionalComputedString("uci option instance."),
			"ip":          schema.StringAttribute{Required: true, Description: "uci option ip."},
			"leasetime":   optionalComputedString("uci option leasetime."),
			"mac":         optionalComputedString("uci option mac."),
			"mac_aliases": optionalComputedStringList("uci option mac_aliases."),
			"name":        optionalComputedString("Optional section name."),
			"tag":         optionalComputedString("uci option tag."),
		},
	}
}

func (r *dhcpHostResource) body(ctx context.Context, m dhcpHostModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putBool(out, "broadcast", m.Broadcast)
	putBool(out, "dns", m.Dns)
	putStr(out, "duid", m.Duid)
	putStr(out, "hostid", m.Hostid)
	putStr(out, "instance", m.Instance)
	putStr(out, "ip", m.Ip)
	putStr(out, "leasetime", m.Leasetime)
	putStr(out, "mac", m.Mac)
	putList(ctx, out, "mac_aliases", m.MacAliases, diags.d)
	putStr(out, "name", m.Name)
	putStr(out, "tag", m.Tag)
	return out
}

func (r *dhcpHostResource) read(ctx context.Context, obj map[string]any, m *dhcpHostModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Broadcast = boolVal(obj, "broadcast")
	m.Dns = boolVal(obj, "dns")
	m.Duid = strVal(obj, "duid")
	m.Hostid = strVal(obj, "hostid")
	m.Instance = strVal(obj, "instance")
	m.Ip = strVal(obj, "ip")
	m.Leasetime = strVal(obj, "leasetime")
	m.Mac = strVal(obj, "mac")
	m.MacAliases = diags.list(listVal(ctx, obj, "mac_aliases"))
	m.Name = strVal(obj, "name")
	m.Tag = strVal(obj, "tag")
}

func (r *dhcpHostResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dhcpHostModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+dhcpHostCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "dhcp host", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dhcpHostResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dhcpHostModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+dhcpHostCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading dhcp host", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dhcpHostResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state dhcpHostModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+dhcpHostCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "dhcp host", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dhcpHostResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state dhcpHostModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+dhcpHostCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "dhcp host", err)
	}
}

func (r *dhcpHostResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, dhcpHostCollection, "dhcp host", req, resp)
}
