// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const dhcpServerCollection = "dhcp/servers"

var (
	_ resource.Resource                = &dhcpServerResource{}
	_ resource.ResourceWithConfigure   = &dhcpServerResource{}
	_ resource.ResourceWithImportState = &dhcpServerResource{}
)

type dhcpServerResource struct{ client *client.Client }

func NewDhcpServerResource() resource.Resource { return &dhcpServerResource{} }

type dhcpServerModel struct {
	ID          types.String `tfsdk:"id"`
	Managed     types.Bool   `tfsdk:"managed"`
	ETag        types.String `tfsdk:"etag"`
	DhcpOption  types.List   `tfsdk:"dhcp_option"`
	Dhcpv6      types.String `tfsdk:"dhcpv6"`
	Domain      types.String `tfsdk:"domain"`
	Dynamicdhcp types.Bool   `tfsdk:"dynamicdhcp"`
	Force       types.Bool   `tfsdk:"force"`
	Ignore      types.Bool   `tfsdk:"ignore"`
	Interface   types.String `tfsdk:"interface"`
	Leasetime   types.String `tfsdk:"leasetime"`
	Limit       types.Int64  `tfsdk:"limit"`
	Ra          types.String `tfsdk:"ra"`
	RaDefault   types.Int64  `tfsdk:"ra_default"`
	Start       types.Int64  `tfsdk:"start"`
}

func (r *dhcpServerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dhcp_server"
}

func (r *dhcpServerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *dhcpServerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Dhcp server.",
		Attributes: map[string]schema.Attribute{
			"id":          computedIDAttribute(),
			"managed":     managedAttribute(),
			"etag":        etagAttribute(),
			"dhcp_option": optionalComputedStringList("uci option dhcp_option."),
			"dhcpv6":      optionalComputedString("uci option dhcpv6."),
			"domain":      optionalComputedString("uci option domain."),
			"dynamicdhcp": optionalComputedBool("uci option dynamicdhcp."),
			"force":       optionalComputedBool("uci option force."),
			"ignore":      optionalComputedBool("uci option ignore."),
			"interface":   schema.StringAttribute{Required: true, Description: "Network interface this entry applies to."},
			"leasetime":   optionalComputedString("uci option leasetime."),
			"limit":       optionalComputedInt64("uci option limit."),
			"ra":          optionalComputedString("uci option ra."),
			"ra_default":  optionalComputedInt64("uci option ra_default."),
			"start":       optionalComputedInt64("uci option start."),
		},
	}
}

func (r *dhcpServerResource) body(ctx context.Context, m dhcpServerModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putList(ctx, out, "dhcp_option", m.DhcpOption, diags.d)
	putStr(out, "dhcpv6", m.Dhcpv6)
	putStr(out, "domain", m.Domain)
	putBool(out, "dynamicdhcp", m.Dynamicdhcp)
	putBool(out, "force", m.Force)
	putBool(out, "ignore", m.Ignore)
	putStr(out, "interface", m.Interface)
	putStr(out, "leasetime", m.Leasetime)
	putInt64(out, "limit", m.Limit)
	putStr(out, "ra", m.Ra)
	putInt64(out, "ra_default", m.RaDefault)
	putInt64(out, "start", m.Start)
	return out
}

func (r *dhcpServerResource) read(ctx context.Context, obj map[string]any, m *dhcpServerModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.DhcpOption = diags.list(listVal(ctx, obj, "dhcp_option"))
	m.Dhcpv6 = strVal(obj, "dhcpv6")
	m.Domain = strVal(obj, "domain")
	m.Dynamicdhcp = boolVal(obj, "dynamicdhcp")
	m.Force = boolVal(obj, "force")
	m.Ignore = boolVal(obj, "ignore")
	m.Interface = strVal(obj, "interface")
	m.Leasetime = strVal(obj, "leasetime")
	m.Limit = int64Val(obj, "limit")
	m.Ra = strVal(obj, "ra")
	m.RaDefault = int64Val(obj, "ra_default")
	m.Start = int64Val(obj, "start")
}

func (r *dhcpServerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dhcpServerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+dhcpServerCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "dhcp server", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dhcpServerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dhcpServerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+dhcpServerCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading dhcp server", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dhcpServerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state dhcpServerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+dhcpServerCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "dhcp server", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dhcpServerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state dhcpServerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+dhcpServerCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "dhcp server", err)
	}
}

func (r *dhcpServerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, dhcpServerCollection, "dhcp server", req, resp)
}
