// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const dhcpOdhcpdPath = "/dhcp/odhcpd"

var (
	_ resource.Resource                = &dhcpOdhcpdResource{}
	_ resource.ResourceWithConfigure   = &dhcpOdhcpdResource{}
	_ resource.ResourceWithImportState = &dhcpOdhcpdResource{}
)

type dhcpOdhcpdResource struct{ client *client.Client }

func NewDhcpOdhcpdResource() resource.Resource { return &dhcpOdhcpdResource{} }

type dhcpOdhcpdModel struct {
	ID           types.String `tfsdk:"id"`
	Managed      types.Bool   `tfsdk:"managed"`
	ETag         types.String `tfsdk:"etag"`
	Leasefile    types.String `tfsdk:"leasefile"`
	Leasetrigger types.String `tfsdk:"leasetrigger"`
	Loglevel     types.Int64  `tfsdk:"loglevel"`
	Maindhcp     types.Bool   `tfsdk:"maindhcp"`
}

func (r *dhcpOdhcpdResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dhcp_odhcpd"
}

func (r *dhcpOdhcpdResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *dhcpOdhcpdResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A odhcpd settings.",
		Attributes: map[string]schema.Attribute{
			"id":           computedIDAttribute(),
			"managed":      managedAttribute(),
			"etag":         etagAttribute(),
			"leasefile":    optionalComputedString("uci option leasefile."),
			"leasetrigger": optionalComputedString("uci option leasetrigger."),
			"loglevel":     optionalComputedInt64("uci option loglevel."),
			"maindhcp":     optionalComputedBool("uci option maindhcp."),
		},
	}
}

func (r *dhcpOdhcpdResource) body(ctx context.Context, m dhcpOdhcpdModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "leasefile", m.Leasefile)
	putStr(out, "leasetrigger", m.Leasetrigger)
	putInt64(out, "loglevel", m.Loglevel)
	putBool(out, "maindhcp", m.Maindhcp)
	return out
}

func (r *dhcpOdhcpdResource) read(ctx context.Context, obj map[string]any, m *dhcpOdhcpdModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Leasefile = strVal(obj, "leasefile")
	m.Leasetrigger = strVal(obj, "leasetrigger")
	m.Loglevel = int64Val(obj, "loglevel")
	m.Maindhcp = boolVal(obj, "maindhcp")
}

func (r *dhcpOdhcpdResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dhcpOdhcpdModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, dhcpOdhcpdPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "odhcpd settings", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dhcpOdhcpdResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dhcpOdhcpdModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, dhcpOdhcpdPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading odhcpd settings", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dhcpOdhcpdResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state dhcpOdhcpdModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, dhcpOdhcpdPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "odhcpd settings", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *dhcpOdhcpdResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *dhcpOdhcpdResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
