// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &dropbearInstanceDataSource{}
	_ datasource.DataSourceWithConfigure = &dropbearInstanceDataSource{}
)

type dropbearInstanceDataSource struct{ client *client.Client }

func NewDropbearInstanceDataSource() datasource.DataSource { return &dropbearInstanceDataSource{} }

func (d *dropbearInstanceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dropbear_instance"
}

func (d *dropbearInstanceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *dropbearInstanceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the dropbear instance.",
		Attributes: map[string]dsschema.Attribute{
			"id":                 dsIDAttribute(),
			"managed":            dsManagedAttribute(),
			"etag":               dsComputedString("Opaque ETag of the resource's current state."),
			"banner_file":        dsComputedString("uci option banner_file."),
			"enable":             dsComputedBool("uci option enable."),
			"gateway_ports":      dsComputedBool("uci option gateway_ports."),
			"interface":          dsComputedString("Network interface this entry applies to."),
			"password_auth":      dsComputedBool("uci option password_auth."),
			"port":               dsComputedInt64("uci option port."),
			"root_login":         dsComputedBool("uci option root_login."),
			"root_password_auth": dsComputedBool("uci option root_password_auth."),
		},
	}
}

func (d *dropbearInstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m dropbearInstanceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+dropbearInstanceCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading dropbear instance", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("dropbear instance not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&dropbearInstanceResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
