// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const dropbearInstanceCollection = "dropbear/instances"

var (
	_ resource.Resource                = &dropbearInstanceResource{}
	_ resource.ResourceWithConfigure   = &dropbearInstanceResource{}
	_ resource.ResourceWithImportState = &dropbearInstanceResource{}
)

type dropbearInstanceResource struct{ client *client.Client }

func NewDropbearInstanceResource() resource.Resource { return &dropbearInstanceResource{} }

type dropbearInstanceModel struct {
	ID               types.String `tfsdk:"id"`
	Managed          types.Bool   `tfsdk:"managed"`
	ETag             types.String `tfsdk:"etag"`
	BannerFile       types.String `tfsdk:"banner_file"`
	Enable           types.Bool   `tfsdk:"enable"`
	GatewayPorts     types.Bool   `tfsdk:"gateway_ports"`
	Interface        types.String `tfsdk:"interface"`
	PasswordAuth     types.Bool   `tfsdk:"password_auth"`
	Port             types.Int64  `tfsdk:"port"`
	RootLogin        types.Bool   `tfsdk:"root_login"`
	RootPasswordAuth types.Bool   `tfsdk:"root_password_auth"`
}

func (r *dropbearInstanceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dropbear_instance"
}

func (r *dropbearInstanceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *dropbearInstanceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Dropbear instance.",
		Attributes: map[string]schema.Attribute{
			"id":                 optionalComputedIDAttribute(),
			"managed":            managedAttribute(),
			"etag":               etagAttribute(),
			"banner_file":        optionalComputedString("uci option banner_file."),
			"enable":             optionalComputedBool("uci option enable."),
			"gateway_ports":      optionalComputedBool("uci option gateway_ports."),
			"interface":          optionalComputedString("Network interface this entry applies to."),
			"password_auth":      optionalComputedBool("uci option password_auth."),
			"port":               optionalComputedInt64("uci option port."),
			"root_login":         optionalComputedBool("uci option root_login."),
			"root_password_auth": optionalComputedBool("uci option root_password_auth."),
		},
	}
}

func (r *dropbearInstanceResource) body(ctx context.Context, m dropbearInstanceModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	if create {
		putStr(out, "id", m.ID)
	}
	putStr(out, "banner_file", m.BannerFile)
	putBool(out, "enable", m.Enable)
	putBool(out, "gateway_ports", m.GatewayPorts)
	putStr(out, "interface", m.Interface)
	putBool(out, "password_auth", m.PasswordAuth)
	putInt64(out, "port", m.Port)
	putBool(out, "root_login", m.RootLogin)
	putBool(out, "root_password_auth", m.RootPasswordAuth)
	return out
}

func (r *dropbearInstanceResource) read(ctx context.Context, obj map[string]any, m *dropbearInstanceModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.BannerFile = strVal(obj, "banner_file")
	m.Enable = boolVal(obj, "enable")
	m.GatewayPorts = boolVal(obj, "gateway_ports")
	m.Interface = strVal(obj, "interface")
	m.PasswordAuth = boolVal(obj, "password_auth")
	m.Port = int64Val(obj, "port")
	m.RootLogin = boolVal(obj, "root_login")
	m.RootPasswordAuth = boolVal(obj, "root_password_auth")
}

func (r *dropbearInstanceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dropbearInstanceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+dropbearInstanceCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "dropbear instance", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dropbearInstanceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dropbearInstanceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+dropbearInstanceCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading dropbear instance", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dropbearInstanceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state dropbearInstanceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+dropbearInstanceCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "dropbear instance", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dropbearInstanceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state dropbearInstanceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+dropbearInstanceCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "dropbear instance", err)
	}
}

func (r *dropbearInstanceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, dropbearInstanceCollection, "dropbear instance", req, resp)
}
