// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &firewallDefaultsDataSource{}
	_ datasource.DataSourceWithConfigure = &firewallDefaultsDataSource{}
)

type firewallDefaultsDataSource struct{ client *client.Client }

func NewFirewallDefaultsDataSource() datasource.DataSource { return &firewallDefaultsDataSource{} }

func (d *firewallDefaultsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_defaults"
}

func (d *firewallDefaultsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *firewallDefaultsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the firewall defaults.",
		Attributes: map[string]dsschema.Attribute{
			"id":                 dsComputedString("Stable id."),
			"managed":            dsManagedAttribute(),
			"etag":               dsComputedString("Opaque ETag of the resource's current state."),
			"drop_invalid":       dsComputedBool("uci option drop_invalid."),
			"flow_offloading":    dsComputedBool("uci option flow_offloading."),
			"flow_offloading_hw": dsComputedBool("uci option flow_offloading_hw."),
			"forward":            dsComputedString("uci option forward."),
			"input":              dsComputedString("uci option input."),
			"output_policy":      dsComputedString("uci option output_policy."),
			"syn_flood":          dsComputedBool("uci option syn_flood."),
			"synflood_burst":     dsComputedInt64("uci option synflood_burst."),
			"synflood_rate":      dsComputedInt64("uci option synflood_rate."),
			"tcp_syncookies":     dsComputedBool("uci option tcp_syncookies."),
		},
	}
}

func (d *firewallDefaultsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m firewallDefaultsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, firewallDefaultsPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall defaults", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("firewall defaults not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&firewallDefaultsResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
