// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &firewallZoneDataSource{}
	_ datasource.DataSourceWithConfigure = &firewallZoneDataSource{}
)

type firewallZoneDataSource struct{ client *client.Client }

func NewFirewallZoneDataSource() datasource.DataSource { return &firewallZoneDataSource{} }

func (d *firewallZoneDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_zone"
}

func (d *firewallZoneDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *firewallZoneDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the firewall zone.",
		Attributes: map[string]dsschema.Attribute{
			"id":            dsIDAttribute(),
			"managed":       dsManagedAttribute(),
			"etag":          dsComputedString("Opaque ETag of the resource's current state."),
			"family":        dsComputedString("Address family: any, ipv4, or ipv6."),
			"forward":       dsComputedString("uci option forward."),
			"input":         dsComputedString("uci option input."),
			"masq":          dsComputedBool("uci option masq."),
			"mtu_fix":       dsComputedBool("uci option mtu_fix."),
			"name":          dsComputedString("Optional section name."),
			"network":       dsComputedStringList("uci option network."),
			"output_policy": dsComputedString("uci option output_policy."),
		},
	}
}

func (d *firewallZoneDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m firewallZoneModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+firewallZoneCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall zone", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("firewall zone not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&firewallZoneResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
