// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const firewallRuleCollection = "firewall/rules"

var (
	_ resource.Resource                = &firewallRuleResource{}
	_ resource.ResourceWithConfigure   = &firewallRuleResource{}
	_ resource.ResourceWithImportState = &firewallRuleResource{}
)

type firewallRuleResource struct{ client *client.Client }

func NewFirewallRuleResource() resource.Resource { return &firewallRuleResource{} }

type firewallRuleModel struct {
	ID      types.String       `tfsdk:"id"`
	Managed types.Bool         `tfsdk:"managed"`
	ETag    types.String       `tfsdk:"etag"`
	Enabled types.Bool         `tfsdk:"enabled"`
	Name    types.String       `tfsdk:"name"`
	Target  types.String       `tfsdk:"target"`
	Match   *firewallRuleMatch `tfsdk:"match"`
}

type firewallRuleMatch struct {
	SrcZone  types.String `tfsdk:"src_zone"`
	DestZone types.String `tfsdk:"dest_zone"`
	SrcIP    types.List   `tfsdk:"src_ip"`
	SrcPort  types.List   `tfsdk:"src_port"`
	DestIP   types.List   `tfsdk:"dest_ip"`
	DestPort types.List   `tfsdk:"dest_port"`
	Proto    types.List   `tfsdk:"proto"`
	Family   types.String `tfsdk:"family"`
}

func (r *firewallRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_rule"
}

func (r *firewallRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *firewallRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Firewall rule.",
		Attributes: map[string]schema.Attribute{
			"id":      optionalComputedIDAttribute(),
			"managed": managedAttribute(),
			"etag":    etagAttribute(),
			"enabled": optionalComputedBool("Whether the entry is active."),
			"name":    optionalComputedString("Optional section name."),
			"target":  schema.StringAttribute{Required: true, Description: "Target / action."},
			"match": schema.SingleNestedAttribute{
				Required:    true,
				Description: "Match conditions.",
				Attributes: map[string]schema.Attribute{
					"src_zone":  schema.StringAttribute{Required: true, Description: "Source firewall zone name."},
					"dest_zone": optionalComputedString("Destination firewall zone name."),
					"src_ip":    optionalComputedStringList("Source IP addresses or CIDRs."),
					"src_port":  optionalComputedStringList("Source ports."),
					"dest_ip":   optionalComputedStringList("Destination IP addresses or CIDRs."),
					"dest_port": optionalComputedStringList("Destination ports."),
					"proto":     optionalComputedStringList("Protocols."),
					"family":    optionalComputedString("Address family: any, ipv4, or ipv6."),
				},
			},
		},
	}
}

func (r *firewallRuleResource) body(ctx context.Context, m firewallRuleModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	if create {
		putStr(out, "id", m.ID)
	}
	putBool(out, "enabled", m.Enabled)
	putStr(out, "name", m.Name)
	putStr(out, "target", m.Target)
	match := map[string]any{}
	if m.Match != nil {
		putStr(match, "src_zone", m.Match.SrcZone)
		putStr(match, "dest_zone", m.Match.DestZone)
		putList(ctx, match, "src_ip", m.Match.SrcIP, diags.d)
		putList(ctx, match, "src_port", m.Match.SrcPort, diags.d)
		putList(ctx, match, "dest_ip", m.Match.DestIP, diags.d)
		putList(ctx, match, "dest_port", m.Match.DestPort, diags.d)
		putList(ctx, match, "proto", m.Match.Proto, diags.d)
		putStr(match, "family", m.Match.Family)
	}
	out["match"] = match
	return out
}

func (r *firewallRuleResource) read(ctx context.Context, obj map[string]any, m *firewallRuleModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Enabled = boolVal(obj, "enabled")
	m.Name = strVal(obj, "name")
	m.Target = strVal(obj, "target")
	nested, _ := obj["match"].(map[string]any)
	if nested == nil {
		nested = map[string]any{}
	}
	nm := &firewallRuleMatch{}
	nm.SrcZone = strVal(nested, "src_zone")
	nm.DestZone = strVal(nested, "dest_zone")
	nm.SrcIP = diags.list(listVal(ctx, nested, "src_ip"))
	nm.SrcPort = diags.list(listVal(ctx, nested, "src_port"))
	nm.DestIP = diags.list(listVal(ctx, nested, "dest_ip"))
	nm.DestPort = diags.list(listVal(ctx, nested, "dest_port"))
	nm.Proto = diags.list(listVal(ctx, nested, "proto"))
	nm.Family = strVal(nested, "family")
	m.Match = nm
}

func (r *firewallRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan firewallRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+firewallRuleCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "firewall rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state firewallRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+firewallRuleCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall rule", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *firewallRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state firewallRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+firewallRuleCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "firewall rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state firewallRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+firewallRuleCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "firewall rule", err)
	}
}

func (r *firewallRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, firewallRuleCollection, "firewall rule", req, resp)
}
