// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const firewallDefaultsPath = "/firewall/defaults"

var (
	_ resource.Resource                = &firewallDefaultsResource{}
	_ resource.ResourceWithConfigure   = &firewallDefaultsResource{}
	_ resource.ResourceWithImportState = &firewallDefaultsResource{}
)

type firewallDefaultsResource struct{ client *client.Client }

func NewFirewallDefaultsResource() resource.Resource { return &firewallDefaultsResource{} }

type firewallDefaultsModel struct {
	ID               types.String `tfsdk:"id"`
	Managed          types.Bool   `tfsdk:"managed"`
	ETag             types.String `tfsdk:"etag"`
	DropInvalid      types.Bool   `tfsdk:"drop_invalid"`
	FlowOffloading   types.Bool   `tfsdk:"flow_offloading"`
	FlowOffloadingHw types.Bool   `tfsdk:"flow_offloading_hw"`
	Forward          types.String `tfsdk:"forward"`
	Input            types.String `tfsdk:"input"`
	OutputPolicy     types.String `tfsdk:"output_policy"`
	SynFlood         types.Bool   `tfsdk:"syn_flood"`
	SynfloodBurst    types.Int64  `tfsdk:"synflood_burst"`
	SynfloodRate     types.Int64  `tfsdk:"synflood_rate"`
	TcpSyncookies    types.Bool   `tfsdk:"tcp_syncookies"`
}

func (r *firewallDefaultsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_defaults"
}

func (r *firewallDefaultsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *firewallDefaultsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A firewall defaults.",
		Attributes: map[string]schema.Attribute{
			"id":                 computedIDAttribute(),
			"managed":            managedAttribute(),
			"etag":               etagAttribute(),
			"drop_invalid":       optionalComputedBool("uci option drop_invalid."),
			"flow_offloading":    optionalComputedBool("uci option flow_offloading."),
			"flow_offloading_hw": optionalComputedBool("uci option flow_offloading_hw."),
			"forward":            optionalComputedString("uci option forward."),
			"input":              optionalComputedString("uci option input."),
			"output_policy":      optionalComputedString("uci option output_policy."),
			"syn_flood":          optionalComputedBool("uci option syn_flood."),
			"synflood_burst":     optionalComputedInt64("uci option synflood_burst."),
			"synflood_rate":      optionalComputedInt64("uci option synflood_rate."),
			"tcp_syncookies":     optionalComputedBool("uci option tcp_syncookies."),
		},
	}
}

func (r *firewallDefaultsResource) body(ctx context.Context, m firewallDefaultsModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putBool(out, "drop_invalid", m.DropInvalid)
	putBool(out, "flow_offloading", m.FlowOffloading)
	putBool(out, "flow_offloading_hw", m.FlowOffloadingHw)
	putStr(out, "forward", m.Forward)
	putStr(out, "input", m.Input)
	putStr(out, "output_policy", m.OutputPolicy)
	putBool(out, "syn_flood", m.SynFlood)
	putInt64(out, "synflood_burst", m.SynfloodBurst)
	putInt64(out, "synflood_rate", m.SynfloodRate)
	putBool(out, "tcp_syncookies", m.TcpSyncookies)
	return out
}

func (r *firewallDefaultsResource) read(ctx context.Context, obj map[string]any, m *firewallDefaultsModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.DropInvalid = boolVal(obj, "drop_invalid")
	m.FlowOffloading = boolVal(obj, "flow_offloading")
	m.FlowOffloadingHw = boolVal(obj, "flow_offloading_hw")
	m.Forward = strVal(obj, "forward")
	m.Input = strVal(obj, "input")
	m.OutputPolicy = strVal(obj, "output_policy")
	m.SynFlood = boolVal(obj, "syn_flood")
	m.SynfloodBurst = int64Val(obj, "synflood_burst")
	m.SynfloodRate = int64Val(obj, "synflood_rate")
	m.TcpSyncookies = boolVal(obj, "tcp_syncookies")
}

func (r *firewallDefaultsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan firewallDefaultsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, firewallDefaultsPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "firewall defaults", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallDefaultsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state firewallDefaultsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, firewallDefaultsPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall defaults", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *firewallDefaultsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state firewallDefaultsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, firewallDefaultsPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "firewall defaults", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *firewallDefaultsResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *firewallDefaultsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
