// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const firewallForwardingCollection = "firewall/forwardings"

var (
	_ resource.Resource                = &firewallForwardingResource{}
	_ resource.ResourceWithConfigure   = &firewallForwardingResource{}
	_ resource.ResourceWithImportState = &firewallForwardingResource{}
)

type firewallForwardingResource struct{ client *client.Client }

func NewFirewallForwardingResource() resource.Resource { return &firewallForwardingResource{} }

type firewallForwardingModel struct {
	ID      types.String `tfsdk:"id"`
	Managed types.Bool   `tfsdk:"managed"`
	ETag    types.String `tfsdk:"etag"`
	Dest    types.String `tfsdk:"dest"`
	Enabled types.Bool   `tfsdk:"enabled"`
	Family  types.String `tfsdk:"family"`
	Src     types.String `tfsdk:"src"`
}

func (r *firewallForwardingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_forwarding"
}

func (r *firewallForwardingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *firewallForwardingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Firewall forwarding.",
		Attributes: map[string]schema.Attribute{
			"id":      computedIDAttribute(),
			"managed": managedAttribute(),
			"etag":    etagAttribute(),
			"dest":    schema.StringAttribute{Required: true, Description: "uci option dest."},
			"enabled": optionalComputedBool("Whether the entry is active."),
			"family":  optionalComputedString("Address family: any, ipv4, or ipv6."),
			"src":     schema.StringAttribute{Required: true, Description: "uci option src."},
		},
	}
}

func (r *firewallForwardingResource) body(ctx context.Context, m firewallForwardingModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "dest", m.Dest)
	putBool(out, "enabled", m.Enabled)
	putStr(out, "family", m.Family)
	putStr(out, "src", m.Src)
	return out
}

func (r *firewallForwardingResource) read(ctx context.Context, obj map[string]any, m *firewallForwardingModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Dest = strVal(obj, "dest")
	m.Enabled = boolVal(obj, "enabled")
	m.Family = strVal(obj, "family")
	m.Src = strVal(obj, "src")
}

func (r *firewallForwardingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan firewallForwardingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+firewallForwardingCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "firewall forwarding", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallForwardingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state firewallForwardingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+firewallForwardingCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall forwarding", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *firewallForwardingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state firewallForwardingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+firewallForwardingCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "firewall forwarding", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallForwardingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state firewallForwardingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+firewallForwardingCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "firewall forwarding", err)
	}
}

func (r *firewallForwardingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, firewallForwardingCollection, "firewall forwarding", req, resp)
}
