// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &firewallRedirectDataSource{}
	_ datasource.DataSourceWithConfigure = &firewallRedirectDataSource{}
)

type firewallRedirectDataSource struct{ client *client.Client }

func NewFirewallRedirectDataSource() datasource.DataSource { return &firewallRedirectDataSource{} }

func (d *firewallRedirectDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_redirect"
}

func (d *firewallRedirectDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *firewallRedirectDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the firewall redirect.",
		Attributes: map[string]dsschema.Attribute{
			"id":              dsIDAttribute(),
			"managed":         dsManagedAttribute(),
			"etag":            dsComputedString("Opaque ETag of the resource's current state."),
			"enabled":         dsComputedBool("Whether the entry is active."),
			"name":            dsComputedString("Optional section name."),
			"reflection":      dsComputedBool("uci option reflection."),
			"reflection_src":  dsComputedString("uci option reflection_src."),
			"reflection_zone": dsComputedStringList("uci option reflection_zone."),
			"target":          dsComputedString("Target / action."),
			"match": dsschema.SingleNestedAttribute{
				Computed:    true,
				Description: "Match conditions.",
				Attributes: map[string]dsschema.Attribute{
					"src_zone":  dsComputedString("Source firewall zone name."),
					"dest_zone": dsComputedString("Destination firewall zone name."),
					"src_ip":    dsComputedStringList("Source IP addresses or CIDRs."),
					"src_port":  dsComputedStringList("Source ports."),
					"src_dport": dsComputedStringList("Incoming (destination) ports to redirect."),
					"dest_ip":   dsComputedStringList("Internal destination IP addresses."),
					"dest_port": dsComputedStringList("Internal destination ports."),
					"proto":     dsComputedStringList("Protocols."),
					"family":    dsComputedString("Address family: any, ipv4, or ipv6."),
				},
			},
		},
	}
}

func (d *firewallRedirectDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m firewallRedirectModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+firewallRedirectCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall redirect", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("firewall redirect not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&firewallRedirectResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
