// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const firewallRedirectCollection = "firewall/redirects"

var (
	_ resource.Resource                = &firewallRedirectResource{}
	_ resource.ResourceWithConfigure   = &firewallRedirectResource{}
	_ resource.ResourceWithImportState = &firewallRedirectResource{}
)

type firewallRedirectResource struct{ client *client.Client }

func NewFirewallRedirectResource() resource.Resource { return &firewallRedirectResource{} }

type firewallRedirectModel struct {
	ID             types.String           `tfsdk:"id"`
	Managed        types.Bool             `tfsdk:"managed"`
	ETag           types.String           `tfsdk:"etag"`
	Enabled        types.Bool             `tfsdk:"enabled"`
	Name           types.String           `tfsdk:"name"`
	Reflection     types.Bool             `tfsdk:"reflection"`
	ReflectionSrc  types.String           `tfsdk:"reflection_src"`
	ReflectionZone types.List             `tfsdk:"reflection_zone"`
	Target         types.String           `tfsdk:"target"`
	Match          *firewallRedirectMatch `tfsdk:"match"`
}

type firewallRedirectMatch struct {
	SrcZone  types.String `tfsdk:"src_zone"`
	DestZone types.String `tfsdk:"dest_zone"`
	SrcIP    types.List   `tfsdk:"src_ip"`
	SrcPort  types.List   `tfsdk:"src_port"`
	SrcDport types.List   `tfsdk:"src_dport"`
	DestIP   types.List   `tfsdk:"dest_ip"`
	DestPort types.List   `tfsdk:"dest_port"`
	Proto    types.List   `tfsdk:"proto"`
	Family   types.String `tfsdk:"family"`
}

func (r *firewallRedirectResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_redirect"
}

func (r *firewallRedirectResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *firewallRedirectResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A firewall redirect.",
		Attributes: map[string]schema.Attribute{
			"id":              computedIDAttribute(),
			"managed":         managedAttribute(),
			"etag":            etagAttribute(),
			"enabled":         optionalComputedBool("Whether the entry is active."),
			"name":            optionalComputedString("Optional section name."),
			"reflection":      optionalComputedBool("uci option reflection."),
			"reflection_src":  optionalComputedString("uci option reflection_src."),
			"reflection_zone": optionalComputedStringList("uci option reflection_zone."),
			"target":          optionalComputedString("Target / action."),
			"match": schema.SingleNestedAttribute{
				Required:    true,
				Description: "Match conditions.",
				Attributes: map[string]schema.Attribute{
					"src_zone":  schema.StringAttribute{Required: true, Description: "Source firewall zone name."},
					"dest_zone": optionalComputedString("Destination firewall zone name."),
					"src_ip":    optionalComputedStringList("Source IP addresses or CIDRs."),
					"src_port":  optionalComputedStringList("Source ports."),
					"src_dport": optionalComputedStringList("Incoming (destination) ports to redirect."),
					"dest_ip":   optionalComputedStringList("Internal destination IP addresses."),
					"dest_port": optionalComputedStringList("Internal destination ports."),
					"proto":     optionalComputedStringList("Protocols."),
					"family":    optionalComputedString("Address family: any, ipv4, or ipv6."),
				},
			},
		},
	}
}

func (r *firewallRedirectResource) body(ctx context.Context, m firewallRedirectModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putBool(out, "enabled", m.Enabled)
	putStr(out, "name", m.Name)
	putBool(out, "reflection", m.Reflection)
	putStr(out, "reflection_src", m.ReflectionSrc)
	putList(ctx, out, "reflection_zone", m.ReflectionZone, diags.d)
	putStr(out, "target", m.Target)
	match := map[string]any{}
	if m.Match != nil {
		putStr(match, "src_zone", m.Match.SrcZone)
		putStr(match, "dest_zone", m.Match.DestZone)
		putList(ctx, match, "src_ip", m.Match.SrcIP, diags.d)
		putList(ctx, match, "src_port", m.Match.SrcPort, diags.d)
		putList(ctx, match, "src_dport", m.Match.SrcDport, diags.d)
		putList(ctx, match, "dest_ip", m.Match.DestIP, diags.d)
		putList(ctx, match, "dest_port", m.Match.DestPort, diags.d)
		putList(ctx, match, "proto", m.Match.Proto, diags.d)
		putStr(match, "family", m.Match.Family)
	}
	out["match"] = match
	return out
}

func (r *firewallRedirectResource) read(ctx context.Context, obj map[string]any, m *firewallRedirectModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Enabled = boolVal(obj, "enabled")
	m.Name = strVal(obj, "name")
	m.Reflection = boolVal(obj, "reflection")
	m.ReflectionSrc = strVal(obj, "reflection_src")
	m.ReflectionZone = diags.list(listVal(ctx, obj, "reflection_zone"))
	m.Target = strVal(obj, "target")
	nested, _ := obj["match"].(map[string]any)
	if nested == nil {
		nested = map[string]any{}
	}
	nm := &firewallRedirectMatch{}
	nm.SrcZone = strVal(nested, "src_zone")
	nm.DestZone = strVal(nested, "dest_zone")
	nm.SrcIP = diags.list(listVal(ctx, nested, "src_ip"))
	nm.SrcPort = diags.list(listVal(ctx, nested, "src_port"))
	nm.SrcDport = diags.list(listVal(ctx, nested, "src_dport"))
	nm.DestIP = diags.list(listVal(ctx, nested, "dest_ip"))
	nm.DestPort = diags.list(listVal(ctx, nested, "dest_port"))
	nm.Proto = diags.list(listVal(ctx, nested, "proto"))
	nm.Family = strVal(nested, "family")
	m.Match = nm
}

func (r *firewallRedirectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan firewallRedirectModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+firewallRedirectCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "firewall redirect", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallRedirectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state firewallRedirectModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+firewallRedirectCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall redirect", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *firewallRedirectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state firewallRedirectModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+firewallRedirectCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "firewall redirect", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallRedirectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state firewallRedirectModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+firewallRedirectCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "firewall redirect", err)
	}
}

func (r *firewallRedirectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, firewallRedirectCollection, "firewall redirect", req, resp)
}
