// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const firewallZoneCollection = "firewall/zones"

var (
	_ resource.Resource                = &firewallZoneResource{}
	_ resource.ResourceWithConfigure   = &firewallZoneResource{}
	_ resource.ResourceWithImportState = &firewallZoneResource{}
)

type firewallZoneResource struct{ client *client.Client }

func NewFirewallZoneResource() resource.Resource { return &firewallZoneResource{} }

type firewallZoneModel struct {
	ID           types.String `tfsdk:"id"`
	Managed      types.Bool   `tfsdk:"managed"`
	ETag         types.String `tfsdk:"etag"`
	Family       types.String `tfsdk:"family"`
	Forward      types.String `tfsdk:"forward"`
	Input        types.String `tfsdk:"input"`
	Masq         types.Bool   `tfsdk:"masq"`
	MtuFix       types.Bool   `tfsdk:"mtu_fix"`
	Name         types.String `tfsdk:"name"`
	Network      types.List   `tfsdk:"network"`
	OutputPolicy types.String `tfsdk:"output_policy"`
}

func (r *firewallZoneResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_zone"
}

func (r *firewallZoneResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *firewallZoneResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Firewall zone.",
		Attributes: map[string]schema.Attribute{
			"id":            computedIDAttribute(),
			"managed":       managedAttribute(),
			"etag":          etagAttribute(),
			"family":        optionalComputedString("Address family: any, ipv4, or ipv6."),
			"forward":       optionalComputedString("uci option forward."),
			"input":         optionalComputedString("uci option input."),
			"masq":          optionalComputedBool("uci option masq."),
			"mtu_fix":       optionalComputedBool("uci option mtu_fix."),
			"name":          schema.StringAttribute{Required: true, Description: "Optional section name."},
			"network":       optionalComputedStringList("uci option network."),
			"output_policy": optionalComputedString("uci option output_policy."),
		},
	}
}

func (r *firewallZoneResource) body(ctx context.Context, m firewallZoneModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "family", m.Family)
	putStr(out, "forward", m.Forward)
	putStr(out, "input", m.Input)
	putBool(out, "masq", m.Masq)
	putBool(out, "mtu_fix", m.MtuFix)
	putStr(out, "name", m.Name)
	putList(ctx, out, "network", m.Network, diags.d)
	putStr(out, "output_policy", m.OutputPolicy)
	return out
}

func (r *firewallZoneResource) read(ctx context.Context, obj map[string]any, m *firewallZoneModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Family = strVal(obj, "family")
	m.Forward = strVal(obj, "forward")
	m.Input = strVal(obj, "input")
	m.Masq = boolVal(obj, "masq")
	m.MtuFix = boolVal(obj, "mtu_fix")
	m.Name = strVal(obj, "name")
	m.Network = diags.list(listVal(ctx, obj, "network"))
	m.OutputPolicy = strVal(obj, "output_policy")
}

func (r *firewallZoneResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan firewallZoneModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+firewallZoneCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "firewall zone", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallZoneResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state firewallZoneModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+firewallZoneCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall zone", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *firewallZoneResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state firewallZoneModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+firewallZoneCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "firewall zone", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallZoneResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state firewallZoneModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+firewallZoneCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "firewall zone", err)
	}
}

func (r *firewallZoneResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, firewallZoneCollection, "firewall zone", req, resp)
}
