// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const lldpdConfigPath = "/lldpd/config"

var (
	_ resource.Resource                = &lldpdConfigResource{}
	_ resource.ResourceWithConfigure   = &lldpdConfigResource{}
	_ resource.ResourceWithImportState = &lldpdConfigResource{}
)

type lldpdConfigResource struct{ client *client.Client }

func NewLldpdConfigResource() resource.Resource { return &lldpdConfigResource{} }

type lldpdConfigModel struct {
	ID               types.String `tfsdk:"id"`
	Managed          types.Bool   `tfsdk:"managed"`
	ETag             types.String `tfsdk:"etag"`
	EnableCdp        types.Bool   `tfsdk:"enable_cdp"`
	EnableEdp        types.Bool   `tfsdk:"enable_edp"`
	EnableFdp        types.Bool   `tfsdk:"enable_fdp"`
	EnableLldpmed    types.Bool   `tfsdk:"enable_lldpmed"`
	EnableSonmp      types.Bool   `tfsdk:"enable_sonmp"`
	Interface        types.List   `tfsdk:"interface"`
	LldpCapabilities types.Bool   `tfsdk:"lldp_capabilities"`
	LldpClass        types.Int64  `tfsdk:"lldp_class"`
	LldpDescription  types.Bool   `tfsdk:"lldp_description"`
	LldpMgmtIp       types.String `tfsdk:"lldp_mgmt_ip"`
}

func (r *lldpdConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_lldpd_config"
}

func (r *lldpdConfigResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *lldpdConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Lldpd config.",
		Attributes: map[string]schema.Attribute{
			"id":                computedIDAttribute(),
			"managed":           managedAttribute(),
			"etag":              etagAttribute(),
			"enable_cdp":        optionalComputedBool("uci option enable_cdp."),
			"enable_edp":        optionalComputedBool("uci option enable_edp."),
			"enable_fdp":        optionalComputedBool("uci option enable_fdp."),
			"enable_lldpmed":    optionalComputedBool("uci option enable_lldpmed."),
			"enable_sonmp":      optionalComputedBool("uci option enable_sonmp."),
			"interface":         optionalComputedStringList("Network interface this entry applies to."),
			"lldp_capabilities": optionalComputedBool("uci option lldp_capabilities."),
			"lldp_class":        optionalComputedInt64("uci option lldp_class."),
			"lldp_description":  optionalComputedBool("uci option lldp_description."),
			"lldp_mgmt_ip":      optionalComputedString("uci option lldp_mgmt_ip."),
		},
	}
}

func (r *lldpdConfigResource) body(ctx context.Context, m lldpdConfigModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putBool(out, "enable_cdp", m.EnableCdp)
	putBool(out, "enable_edp", m.EnableEdp)
	putBool(out, "enable_fdp", m.EnableFdp)
	putBool(out, "enable_lldpmed", m.EnableLldpmed)
	putBool(out, "enable_sonmp", m.EnableSonmp)
	putList(ctx, out, "interface", m.Interface, diags.d)
	putBool(out, "lldp_capabilities", m.LldpCapabilities)
	putInt64(out, "lldp_class", m.LldpClass)
	putBool(out, "lldp_description", m.LldpDescription)
	putStr(out, "lldp_mgmt_ip", m.LldpMgmtIp)
	return out
}

func (r *lldpdConfigResource) read(ctx context.Context, obj map[string]any, m *lldpdConfigModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.EnableCdp = boolVal(obj, "enable_cdp")
	m.EnableEdp = boolVal(obj, "enable_edp")
	m.EnableFdp = boolVal(obj, "enable_fdp")
	m.EnableLldpmed = boolVal(obj, "enable_lldpmed")
	m.EnableSonmp = boolVal(obj, "enable_sonmp")
	m.Interface = diags.list(listVal(ctx, obj, "interface"))
	m.LldpCapabilities = boolVal(obj, "lldp_capabilities")
	m.LldpClass = int64Val(obj, "lldp_class")
	m.LldpDescription = boolVal(obj, "lldp_description")
	m.LldpMgmtIp = strVal(obj, "lldp_mgmt_ip")
}

func (r *lldpdConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan lldpdConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, lldpdConfigPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "lldpd config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *lldpdConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state lldpdConfigModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, lldpdConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading lldpd config", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *lldpdConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state lldpdConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, lldpdConfigPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "lldpd config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *lldpdConfigResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *lldpdConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
