// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &lldpdConfigDataSource{}
	_ datasource.DataSourceWithConfigure = &lldpdConfigDataSource{}
)

type lldpdConfigDataSource struct{ client *client.Client }

func NewLldpdConfigDataSource() datasource.DataSource { return &lldpdConfigDataSource{} }

func (d *lldpdConfigDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_lldpd_config"
}

func (d *lldpdConfigDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *lldpdConfigDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the lldpd config.",
		Attributes: map[string]dsschema.Attribute{
			"id":                dsComputedString("Stable id."),
			"managed":           dsManagedAttribute(),
			"etag":              dsComputedString("Opaque ETag of the resource's current state."),
			"enable_cdp":        dsComputedBool("uci option enable_cdp."),
			"enable_edp":        dsComputedBool("uci option enable_edp."),
			"enable_fdp":        dsComputedBool("uci option enable_fdp."),
			"enable_lldpmed":    dsComputedBool("uci option enable_lldpmed."),
			"enable_sonmp":      dsComputedBool("uci option enable_sonmp."),
			"interface":         dsComputedStringList("Network interface this entry applies to."),
			"lldp_capabilities": dsComputedBool("uci option lldp_capabilities."),
			"lldp_class":        dsComputedInt64("uci option lldp_class."),
			"lldp_description":  dsComputedBool("uci option lldp_description."),
			"lldp_mgmt_ip":      dsComputedString("uci option lldp_mgmt_ip."),
		},
	}
}

func (d *lldpdConfigDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m lldpdConfigModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, lldpdConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading lldpd config", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("lldpd config not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&lldpdConfigResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
