// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &mwan3InterfaceDataSource{}
	_ datasource.DataSourceWithConfigure = &mwan3InterfaceDataSource{}
)

type mwan3InterfaceDataSource struct{ client *client.Client }

func NewMwan3InterfaceDataSource() datasource.DataSource { return &mwan3InterfaceDataSource{} }

func (d *mwan3InterfaceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_interface"
}

func (d *mwan3InterfaceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *mwan3InterfaceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the mwan3 interface.",
		Attributes: map[string]dsschema.Attribute{
			"id":                    dsIDAttribute(),
			"managed":               dsManagedAttribute(),
			"etag":                  dsComputedString("Opaque ETag of the resource's current state."),
			"check_quality":         dsComputedBool("uci option check_quality."),
			"down":                  dsComputedInt64("uci option down."),
			"enabled":               dsComputedBool("Whether the entry is active."),
			"failure_interval":      dsComputedInt64("uci option failure_interval."),
			"failure_latency":       dsComputedInt64("uci option failure_latency."),
			"failure_loss":          dsComputedInt64("uci option failure_loss."),
			"family":                dsComputedString("Address family: any, ipv4, or ipv6."),
			"flush_conntrack":       dsComputedStringList("uci option flush_conntrack."),
			"interval":              dsComputedInt64("uci option interval."),
			"keep_failure_interval": dsComputedBool("uci option keep_failure_interval."),
			"max_ttl":               dsComputedInt64("uci option max_ttl."),
			"probe_count":           dsComputedInt64("Probes per cycle per track_ip."),
			"recovery_interval":     dsComputedInt64("uci option recovery_interval."),
			"recovery_latency":      dsComputedInt64("uci option recovery_latency."),
			"recovery_loss":         dsComputedInt64("uci option recovery_loss."),
			"reliability":           dsComputedInt64("uci option reliability."),
			"size":                  dsComputedInt64("uci option size."),
			"timeout":               dsComputedInt64("uci option timeout."),
			"track_ip":              dsComputedStringList("uci option track_ip."),
			"track_method":          dsComputedString("uci option track_method."),
			"up":                    dsComputedInt64("uci option up."),
		},
	}
}

func (d *mwan3InterfaceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m mwan3InterfaceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+mwan3InterfaceCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 interface", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("mwan3 interface not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&mwan3InterfaceResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
