// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &mwan3PolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &mwan3PolicyDataSource{}
)

type mwan3PolicyDataSource struct{ client *client.Client }

func NewMwan3PolicyDataSource() datasource.DataSource { return &mwan3PolicyDataSource{} }

func (d *mwan3PolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_policy"
}

func (d *mwan3PolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *mwan3PolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the mwan3 policy.",
		Attributes: map[string]dsschema.Attribute{
			"id":          dsIDAttribute(),
			"managed":     dsManagedAttribute(),
			"etag":        dsComputedString("Opaque ETag of the resource's current state."),
			"last_resort": dsComputedString("uci option last_resort."),
			"use_members": dsComputedStringList("uci option use_members."),
		},
	}
}

func (d *mwan3PolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m mwan3PolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+mwan3PolicyCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 policy", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("mwan3 policy not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&mwan3PolicyResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
