// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &mwan3GlobalsDataSource{}
	_ datasource.DataSourceWithConfigure = &mwan3GlobalsDataSource{}
)

type mwan3GlobalsDataSource struct{ client *client.Client }

func NewMwan3GlobalsDataSource() datasource.DataSource { return &mwan3GlobalsDataSource{} }

func (d *mwan3GlobalsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_globals"
}

func (d *mwan3GlobalsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *mwan3GlobalsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the mwan3 globals.",
		Attributes: map[string]dsschema.Attribute{
			"id":             dsComputedString("Stable id."),
			"managed":        dsManagedAttribute(),
			"etag":           dsComputedString("Opaque ETag of the resource's current state."),
			"local_source":   dsComputedString("uci option local_source."),
			"logging":        dsComputedBool("uci option logging."),
			"loglevel":       dsComputedString("uci option loglevel."),
			"mmx_mask":       dsComputedString("uci option mmx_mask."),
			"rtmon_interval": dsComputedInt64("uci option rtmon_interval."),
		},
	}
}

func (d *mwan3GlobalsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m mwan3GlobalsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, mwan3GlobalsPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 globals", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("mwan3 globals not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&mwan3GlobalsResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
