// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const mwan3PolicyCollection = "mwan3/policies"

var (
	_ resource.Resource                = &mwan3PolicyResource{}
	_ resource.ResourceWithConfigure   = &mwan3PolicyResource{}
	_ resource.ResourceWithImportState = &mwan3PolicyResource{}
)

type mwan3PolicyResource struct{ client *client.Client }

func NewMwan3PolicyResource() resource.Resource { return &mwan3PolicyResource{} }

type mwan3PolicyModel struct {
	ID         types.String `tfsdk:"id"`
	Managed    types.Bool   `tfsdk:"managed"`
	ETag       types.String `tfsdk:"etag"`
	LastResort types.String `tfsdk:"last_resort"`
	UseMembers types.List   `tfsdk:"use_members"`
}

func (r *mwan3PolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_policy"
}

func (r *mwan3PolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *mwan3PolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Mwan3 policy.",
		Attributes: map[string]schema.Attribute{
			"id":          optionalComputedIDAttribute(),
			"managed":     managedAttribute(),
			"etag":        etagAttribute(),
			"last_resort": optionalComputedString("uci option last_resort."),
			"use_members": schema.ListAttribute{ElementType: types.StringType, Required: true, Description: "uci option use_members."},
		},
	}
}

func (r *mwan3PolicyResource) body(ctx context.Context, m mwan3PolicyModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	if create {
		putStr(out, "id", m.ID)
	}
	putStr(out, "last_resort", m.LastResort)
	putList(ctx, out, "use_members", m.UseMembers, diags.d)
	return out
}

func (r *mwan3PolicyResource) read(ctx context.Context, obj map[string]any, m *mwan3PolicyModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.LastResort = strVal(obj, "last_resort")
	m.UseMembers = diags.list(listVal(ctx, obj, "use_members"))
}

func (r *mwan3PolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mwan3PolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+mwan3PolicyCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "mwan3 policy", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mwan3PolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mwan3PolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+mwan3PolicyCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 policy", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mwan3PolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state mwan3PolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+mwan3PolicyCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "mwan3 policy", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mwan3PolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state mwan3PolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+mwan3PolicyCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "mwan3 policy", err)
	}
}

func (r *mwan3PolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, mwan3PolicyCollection, "mwan3 policy", req, resp)
}
