// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const mwan3GlobalsPath = "/mwan3/globals"

var (
	_ resource.Resource                = &mwan3GlobalsResource{}
	_ resource.ResourceWithConfigure   = &mwan3GlobalsResource{}
	_ resource.ResourceWithImportState = &mwan3GlobalsResource{}
)

type mwan3GlobalsResource struct{ client *client.Client }

func NewMwan3GlobalsResource() resource.Resource { return &mwan3GlobalsResource{} }

type mwan3GlobalsModel struct {
	ID            types.String `tfsdk:"id"`
	Managed       types.Bool   `tfsdk:"managed"`
	ETag          types.String `tfsdk:"etag"`
	LocalSource   types.String `tfsdk:"local_source"`
	Logging       types.Bool   `tfsdk:"logging"`
	Loglevel      types.String `tfsdk:"loglevel"`
	MmxMask       types.String `tfsdk:"mmx_mask"`
	RtmonInterval types.Int64  `tfsdk:"rtmon_interval"`
}

func (r *mwan3GlobalsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_globals"
}

func (r *mwan3GlobalsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *mwan3GlobalsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A mwan3 globals.",
		Attributes: map[string]schema.Attribute{
			"id":             computedIDAttribute(),
			"managed":        managedAttribute(),
			"etag":           etagAttribute(),
			"local_source":   optionalComputedString("uci option local_source."),
			"logging":        optionalComputedBool("uci option logging."),
			"loglevel":       optionalComputedString("uci option loglevel."),
			"mmx_mask":       optionalComputedString("uci option mmx_mask."),
			"rtmon_interval": optionalComputedInt64("uci option rtmon_interval."),
		},
	}
}

func (r *mwan3GlobalsResource) body(ctx context.Context, m mwan3GlobalsModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "local_source", m.LocalSource)
	putBool(out, "logging", m.Logging)
	putStr(out, "loglevel", m.Loglevel)
	putStr(out, "mmx_mask", m.MmxMask)
	putInt64(out, "rtmon_interval", m.RtmonInterval)
	return out
}

func (r *mwan3GlobalsResource) read(ctx context.Context, obj map[string]any, m *mwan3GlobalsModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.LocalSource = strVal(obj, "local_source")
	m.Logging = boolVal(obj, "logging")
	m.Loglevel = strVal(obj, "loglevel")
	m.MmxMask = strVal(obj, "mmx_mask")
	m.RtmonInterval = int64Val(obj, "rtmon_interval")
}

func (r *mwan3GlobalsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mwan3GlobalsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, mwan3GlobalsPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "mwan3 globals", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mwan3GlobalsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mwan3GlobalsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, mwan3GlobalsPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 globals", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mwan3GlobalsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state mwan3GlobalsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, mwan3GlobalsPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "mwan3 globals", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *mwan3GlobalsResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *mwan3GlobalsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
