// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const mwan3RuleCollection = "mwan3/rules"

var (
	_ resource.Resource                = &mwan3RuleResource{}
	_ resource.ResourceWithConfigure   = &mwan3RuleResource{}
	_ resource.ResourceWithImportState = &mwan3RuleResource{}
)

type mwan3RuleResource struct{ client *client.Client }

func NewMwan3RuleResource() resource.Resource { return &mwan3RuleResource{} }

type mwan3RuleModel struct {
	ID        types.String `tfsdk:"id"`
	Managed   types.Bool   `tfsdk:"managed"`
	ETag      types.String `tfsdk:"etag"`
	DestIp    types.String `tfsdk:"dest_ip"`
	DestPort  types.String `tfsdk:"dest_port"`
	Family    types.String `tfsdk:"family"`
	Ipset     types.String `tfsdk:"ipset"`
	Logging   types.Bool   `tfsdk:"logging"`
	Proto     types.String `tfsdk:"proto"`
	SrcIp     types.String `tfsdk:"src_ip"`
	SrcPort   types.String `tfsdk:"src_port"`
	Sticky    types.Bool   `tfsdk:"sticky"`
	Timeout   types.Int64  `tfsdk:"timeout"`
	UsePolicy types.String `tfsdk:"use_policy"`
}

func (r *mwan3RuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_rule"
}

func (r *mwan3RuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *mwan3RuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A mwan3 rule.",
		Attributes: map[string]schema.Attribute{
			"id":         computedIDAttribute(),
			"managed":    managedAttribute(),
			"etag":       etagAttribute(),
			"dest_ip":    optionalComputedString("Destination IP addresses or CIDRs."),
			"dest_port":  optionalComputedString("Destination ports."),
			"family":     optionalComputedString("Address family: any, ipv4, or ipv6."),
			"ipset":      optionalComputedString("uci option ipset."),
			"logging":    optionalComputedBool("uci option logging."),
			"proto":      optionalComputedString("Protocol."),
			"src_ip":     optionalComputedString("Source IP addresses or CIDRs."),
			"src_port":   optionalComputedString("Source ports."),
			"sticky":     optionalComputedBool("uci option sticky."),
			"timeout":    optionalComputedInt64("uci option timeout."),
			"use_policy": schema.StringAttribute{Required: true, Description: "uci option use_policy."},
		},
	}
}

func (r *mwan3RuleResource) body(ctx context.Context, m mwan3RuleModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "dest_ip", m.DestIp)
	putStr(out, "dest_port", m.DestPort)
	putStr(out, "family", m.Family)
	putStr(out, "ipset", m.Ipset)
	putBool(out, "logging", m.Logging)
	putStr(out, "proto", m.Proto)
	putStr(out, "src_ip", m.SrcIp)
	putStr(out, "src_port", m.SrcPort)
	putBool(out, "sticky", m.Sticky)
	putInt64(out, "timeout", m.Timeout)
	putStr(out, "use_policy", m.UsePolicy)
	return out
}

func (r *mwan3RuleResource) read(ctx context.Context, obj map[string]any, m *mwan3RuleModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.DestIp = strVal(obj, "dest_ip")
	m.DestPort = strVal(obj, "dest_port")
	m.Family = strVal(obj, "family")
	m.Ipset = strVal(obj, "ipset")
	m.Logging = boolVal(obj, "logging")
	m.Proto = strVal(obj, "proto")
	m.SrcIp = strVal(obj, "src_ip")
	m.SrcPort = strVal(obj, "src_port")
	m.Sticky = boolVal(obj, "sticky")
	m.Timeout = int64Val(obj, "timeout")
	m.UsePolicy = strVal(obj, "use_policy")
}

func (r *mwan3RuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mwan3RuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+mwan3RuleCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "mwan3 rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mwan3RuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mwan3RuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+mwan3RuleCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 rule", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mwan3RuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state mwan3RuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+mwan3RuleCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "mwan3 rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mwan3RuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state mwan3RuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+mwan3RuleCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "mwan3 rule", err)
	}
}

func (r *mwan3RuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, mwan3RuleCollection, "mwan3 rule", req, resp)
}
