// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &mwan3MemberDataSource{}
	_ datasource.DataSourceWithConfigure = &mwan3MemberDataSource{}
)

type mwan3MemberDataSource struct{ client *client.Client }

func NewMwan3MemberDataSource() datasource.DataSource { return &mwan3MemberDataSource{} }

func (d *mwan3MemberDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_member"
}

func (d *mwan3MemberDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *mwan3MemberDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the mwan3 member.",
		Attributes: map[string]dsschema.Attribute{
			"id":        dsIDAttribute(),
			"managed":   dsManagedAttribute(),
			"etag":      dsComputedString("Opaque ETag of the resource's current state."),
			"interface": dsComputedString("Network interface this entry applies to."),
			"metric":    dsComputedInt64("uci option metric."),
			"weight":    dsComputedInt64("uci option weight."),
		},
	}
}

func (d *mwan3MemberDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m mwan3MemberModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+mwan3MemberCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 member", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("mwan3 member not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&mwan3MemberResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
