// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &mwan3RuleDataSource{}
	_ datasource.DataSourceWithConfigure = &mwan3RuleDataSource{}
)

type mwan3RuleDataSource struct{ client *client.Client }

func NewMwan3RuleDataSource() datasource.DataSource { return &mwan3RuleDataSource{} }

func (d *mwan3RuleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_rule"
}

func (d *mwan3RuleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *mwan3RuleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the mwan3 rule.",
		Attributes: map[string]dsschema.Attribute{
			"id":         dsIDAttribute(),
			"managed":    dsManagedAttribute(),
			"etag":       dsComputedString("Opaque ETag of the resource's current state."),
			"dest_ip":    dsComputedString("Destination IP addresses or CIDRs."),
			"dest_port":  dsComputedString("Destination ports."),
			"family":     dsComputedString("Address family: any, ipv4, or ipv6."),
			"ipset":      dsComputedString("uci option ipset."),
			"logging":    dsComputedBool("uci option logging."),
			"proto":      dsComputedString("Protocol."),
			"src_ip":     dsComputedString("Source IP addresses or CIDRs."),
			"src_port":   dsComputedString("Source ports."),
			"sticky":     dsComputedBool("uci option sticky."),
			"timeout":    dsComputedInt64("uci option timeout."),
			"use_policy": dsComputedString("uci option use_policy."),
		},
	}
}

func (d *mwan3RuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m mwan3RuleModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+mwan3RuleCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 rule", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("mwan3 rule not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&mwan3RuleResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
