// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const mwan3InterfaceCollection = "mwan3/interfaces"

var (
	_ resource.Resource                = &mwan3InterfaceResource{}
	_ resource.ResourceWithConfigure   = &mwan3InterfaceResource{}
	_ resource.ResourceWithImportState = &mwan3InterfaceResource{}
)

type mwan3InterfaceResource struct{ client *client.Client }

func NewMwan3InterfaceResource() resource.Resource { return &mwan3InterfaceResource{} }

type mwan3InterfaceModel struct {
	ID                  types.String `tfsdk:"id"`
	Managed             types.Bool   `tfsdk:"managed"`
	ETag                types.String `tfsdk:"etag"`
	CheckQuality        types.Bool   `tfsdk:"check_quality"`
	Down                types.Int64  `tfsdk:"down"`
	Enabled             types.Bool   `tfsdk:"enabled"`
	FailureInterval     types.Int64  `tfsdk:"failure_interval"`
	FailureLatency      types.Int64  `tfsdk:"failure_latency"`
	FailureLoss         types.Int64  `tfsdk:"failure_loss"`
	Family              types.String `tfsdk:"family"`
	FlushConntrack      types.List   `tfsdk:"flush_conntrack"`
	Interval            types.Int64  `tfsdk:"interval"`
	KeepFailureInterval types.Bool   `tfsdk:"keep_failure_interval"`
	MaxTtl              types.Int64  `tfsdk:"max_ttl"`
	ProbeCount          types.Int64  `tfsdk:"probe_count"`
	RecoveryInterval    types.Int64  `tfsdk:"recovery_interval"`
	RecoveryLatency     types.Int64  `tfsdk:"recovery_latency"`
	RecoveryLoss        types.Int64  `tfsdk:"recovery_loss"`
	Reliability         types.Int64  `tfsdk:"reliability"`
	Size                types.Int64  `tfsdk:"size"`
	Timeout             types.Int64  `tfsdk:"timeout"`
	TrackIp             types.List   `tfsdk:"track_ip"`
	TrackMethod         types.String `tfsdk:"track_method"`
	Up                  types.Int64  `tfsdk:"up"`
}

func (r *mwan3InterfaceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mwan3_interface"
}

func (r *mwan3InterfaceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *mwan3InterfaceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A mwan3 interface.",
		Attributes: map[string]schema.Attribute{
			"id":                    computedIDAttribute(),
			"managed":               managedAttribute(),
			"etag":                  etagAttribute(),
			"check_quality":         optionalComputedBool("uci option check_quality."),
			"down":                  optionalComputedInt64("uci option down."),
			"enabled":               optionalComputedBool("Whether the entry is active."),
			"failure_interval":      optionalComputedInt64("uci option failure_interval."),
			"failure_latency":       optionalComputedInt64("uci option failure_latency."),
			"failure_loss":          optionalComputedInt64("uci option failure_loss."),
			"family":                schema.StringAttribute{Required: true, Description: "Address family: any, ipv4, or ipv6."},
			"flush_conntrack":       optionalComputedStringList("uci option flush_conntrack."),
			"interval":              optionalComputedInt64("uci option interval."),
			"keep_failure_interval": optionalComputedBool("uci option keep_failure_interval."),
			"max_ttl":               optionalComputedInt64("uci option max_ttl."),
			"probe_count":           optionalComputedInt64("Probes per cycle per track_ip."),
			"recovery_interval":     optionalComputedInt64("uci option recovery_interval."),
			"recovery_latency":      optionalComputedInt64("uci option recovery_latency."),
			"recovery_loss":         optionalComputedInt64("uci option recovery_loss."),
			"reliability":           optionalComputedInt64("uci option reliability."),
			"size":                  optionalComputedInt64("uci option size."),
			"timeout":               optionalComputedInt64("uci option timeout."),
			"track_ip":              optionalComputedStringList("uci option track_ip."),
			"track_method":          optionalComputedString("uci option track_method."),
			"up":                    optionalComputedInt64("uci option up."),
		},
	}
}

func (r *mwan3InterfaceResource) body(ctx context.Context, m mwan3InterfaceModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putBool(out, "check_quality", m.CheckQuality)
	putInt64(out, "down", m.Down)
	putBool(out, "enabled", m.Enabled)
	putInt64(out, "failure_interval", m.FailureInterval)
	putInt64(out, "failure_latency", m.FailureLatency)
	putInt64(out, "failure_loss", m.FailureLoss)
	putStr(out, "family", m.Family)
	putList(ctx, out, "flush_conntrack", m.FlushConntrack, diags.d)
	putInt64(out, "interval", m.Interval)
	putBool(out, "keep_failure_interval", m.KeepFailureInterval)
	putInt64(out, "max_ttl", m.MaxTtl)
	putInt64(out, "probe_count", m.ProbeCount)
	putInt64(out, "recovery_interval", m.RecoveryInterval)
	putInt64(out, "recovery_latency", m.RecoveryLatency)
	putInt64(out, "recovery_loss", m.RecoveryLoss)
	putInt64(out, "reliability", m.Reliability)
	putInt64(out, "size", m.Size)
	putInt64(out, "timeout", m.Timeout)
	putList(ctx, out, "track_ip", m.TrackIp, diags.d)
	putStr(out, "track_method", m.TrackMethod)
	putInt64(out, "up", m.Up)
	return out
}

func (r *mwan3InterfaceResource) read(ctx context.Context, obj map[string]any, m *mwan3InterfaceModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.CheckQuality = boolVal(obj, "check_quality")
	m.Down = int64Val(obj, "down")
	m.Enabled = boolVal(obj, "enabled")
	m.FailureInterval = int64Val(obj, "failure_interval")
	m.FailureLatency = int64Val(obj, "failure_latency")
	m.FailureLoss = int64Val(obj, "failure_loss")
	m.Family = strVal(obj, "family")
	m.FlushConntrack = diags.list(listVal(ctx, obj, "flush_conntrack"))
	m.Interval = int64Val(obj, "interval")
	m.KeepFailureInterval = boolVal(obj, "keep_failure_interval")
	m.MaxTtl = int64Val(obj, "max_ttl")
	m.ProbeCount = int64Val(obj, "probe_count")
	m.RecoveryInterval = int64Val(obj, "recovery_interval")
	m.RecoveryLatency = int64Val(obj, "recovery_latency")
	m.RecoveryLoss = int64Val(obj, "recovery_loss")
	m.Reliability = int64Val(obj, "reliability")
	m.Size = int64Val(obj, "size")
	m.Timeout = int64Val(obj, "timeout")
	m.TrackIp = diags.list(listVal(ctx, obj, "track_ip"))
	m.TrackMethod = strVal(obj, "track_method")
	m.Up = int64Val(obj, "up")
}

func (r *mwan3InterfaceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mwan3InterfaceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+mwan3InterfaceCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "mwan3 interface", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mwan3InterfaceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mwan3InterfaceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+mwan3InterfaceCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading mwan3 interface", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mwan3InterfaceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state mwan3InterfaceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+mwan3InterfaceCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "mwan3 interface", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mwan3InterfaceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state mwan3InterfaceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+mwan3InterfaceCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "mwan3 interface", err)
	}
}

func (r *mwan3InterfaceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, mwan3InterfaceCollection, "mwan3 interface", req, resp)
}
