// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const networkWireguardPeerCollection = "network/wireguard_peers"

var (
	_ resource.Resource                = &networkWireguardPeerResource{}
	_ resource.ResourceWithConfigure   = &networkWireguardPeerResource{}
	_ resource.ResourceWithImportState = &networkWireguardPeerResource{}
)

type networkWireguardPeerResource struct{ client *client.Client }

func NewNetworkWireguardPeerResource() resource.Resource { return &networkWireguardPeerResource{} }

type networkWireguardPeerModel struct {
	ID                  types.String `tfsdk:"id"`
	Managed             types.Bool   `tfsdk:"managed"`
	ETag                types.String `tfsdk:"etag"`
	AllowedIps          types.List   `tfsdk:"allowed_ips"`
	Description         types.String `tfsdk:"description"`
	Disabled            types.Bool   `tfsdk:"disabled"`
	EndpointHost        types.String `tfsdk:"endpoint_host"`
	EndpointPort        types.Int64  `tfsdk:"endpoint_port"`
	HasPresharedKey     types.Bool   `tfsdk:"has_preshared_key"`
	Interface           types.String `tfsdk:"interface"`
	PersistentKeepalive types.Int64  `tfsdk:"persistent_keepalive"`
	PresharedKey        types.String `tfsdk:"preshared_key"`
	PublicKey           types.String `tfsdk:"public_key"`
	RouteAllowedIps     types.Bool   `tfsdk:"route_allowed_ips"`
}

func (r *networkWireguardPeerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_wireguard_peer"
}

func (r *networkWireguardPeerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *networkWireguardPeerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A network WireGuard peer.",
		Attributes: map[string]schema.Attribute{
			"id":                   computedIDAttribute(),
			"managed":              managedAttribute(),
			"etag":                 etagAttribute(),
			"allowed_ips":          schema.ListAttribute{ElementType: types.StringType, Required: true, Description: "uci option allowed_ips."},
			"description":          optionalComputedString("uci option description."),
			"disabled":             optionalComputedBool("Whether the entry is disabled."),
			"endpoint_host":        optionalComputedString("uci option endpoint_host."),
			"endpoint_port":        optionalComputedInt64("uci option endpoint_port."),
			"has_preshared_key":    schema.BoolAttribute{Computed: true, Description: "Whether a preshared key is configured."},
			"interface":            schema.StringAttribute{Required: true, Description: "Network interface this entry applies to."},
			"persistent_keepalive": optionalComputedInt64("uci option persistent_keepalive."),
			"preshared_key":        schema.StringAttribute{Optional: true, Sensitive: true, Description: "WireGuard preshared key. Write-only: never returned by the API."},
			"public_key":           schema.StringAttribute{Required: true, Description: "uci option public_key."},
			"route_allowed_ips":    optionalComputedBool("uci option route_allowed_ips."),
		},
	}
}

func (r *networkWireguardPeerResource) body(ctx context.Context, m networkWireguardPeerModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putList(ctx, out, "allowed_ips", m.AllowedIps, diags.d)
	putStr(out, "description", m.Description)
	putBool(out, "disabled", m.Disabled)
	putStr(out, "endpoint_host", m.EndpointHost)
	putInt64(out, "endpoint_port", m.EndpointPort)
	putStr(out, "interface", m.Interface)
	putInt64(out, "persistent_keepalive", m.PersistentKeepalive)
	putStr(out, "preshared_key", m.PresharedKey)
	putStr(out, "public_key", m.PublicKey)
	putBool(out, "route_allowed_ips", m.RouteAllowedIps)
	return out
}

func (r *networkWireguardPeerResource) read(ctx context.Context, obj map[string]any, m *networkWireguardPeerModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.AllowedIps = diags.list(listVal(ctx, obj, "allowed_ips"))
	m.Description = strVal(obj, "description")
	m.Disabled = boolVal(obj, "disabled")
	m.EndpointHost = strVal(obj, "endpoint_host")
	m.EndpointPort = int64Val(obj, "endpoint_port")
	m.HasPresharedKey = boolValDefault(obj, "has_preshared_key")
	m.Interface = strVal(obj, "interface")
	m.PersistentKeepalive = int64Val(obj, "persistent_keepalive")
	// preshared_key is write-only: preserve the planned value (the API never returns it).
	m.PublicKey = strVal(obj, "public_key")
	m.RouteAllowedIps = boolVal(obj, "route_allowed_ips")
}

func (r *networkWireguardPeerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan networkWireguardPeerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+networkWireguardPeerCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "network WireGuard peer", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkWireguardPeerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state networkWireguardPeerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+networkWireguardPeerCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network WireGuard peer", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *networkWireguardPeerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state networkWireguardPeerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+networkWireguardPeerCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "network WireGuard peer", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkWireguardPeerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state networkWireguardPeerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+networkWireguardPeerCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "network WireGuard peer", err)
	}
}

func (r *networkWireguardPeerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, networkWireguardPeerCollection, "network WireGuard peer", req, resp)
}
