// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &networkDeviceDataSource{}
	_ datasource.DataSourceWithConfigure = &networkDeviceDataSource{}
)

type networkDeviceDataSource struct{ client *client.Client }

func NewNetworkDeviceDataSource() datasource.DataSource { return &networkDeviceDataSource{} }

func (d *networkDeviceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_device"
}

func (d *networkDeviceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *networkDeviceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the network device.",
		Attributes: map[string]dsschema.Attribute{
			"id":      dsIDAttribute(),
			"managed": dsManagedAttribute(),
			"etag":    dsComputedString("Opaque ETag of the resource's current state."),
			"ifname":  dsComputedString("uci option ifname."),
			"ipv6":    dsComputedBool("uci option ipv6."),
			"macaddr": dsComputedString("uci option macaddr."),
			"mtu":     dsComputedInt64("uci option mtu."),
			"name":    dsComputedString("Optional section name."),
			"ports":   dsComputedStringList("uci option ports."),
			"type":    dsComputedString("uci option type."),
			"vid":     dsComputedInt64("uci option vid."),
		},
	}
}

func (d *networkDeviceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m networkDeviceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+networkDeviceCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network device", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("network device not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&networkDeviceResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
