// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &networkRuleDataSource{}
	_ datasource.DataSourceWithConfigure = &networkRuleDataSource{}
)

type networkRuleDataSource struct{ client *client.Client }

func NewNetworkRuleDataSource() datasource.DataSource { return &networkRuleDataSource{} }

func (d *networkRuleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_rule"
}

func (d *networkRuleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *networkRuleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the network rule.",
		Attributes: map[string]dsschema.Attribute{
			"id":       dsIDAttribute(),
			"managed":  dsManagedAttribute(),
			"etag":     dsComputedString("Opaque ETag of the resource's current state."),
			"action":   dsComputedString("uci option action."),
			"dest":     dsComputedString("uci option dest."),
			"goto":     dsComputedInt64("uci option goto."),
			"in":       dsComputedString("uci option in."),
			"invert":   dsComputedBool("uci option invert."),
			"lookup":   dsComputedInt64("uci option lookup."),
			"mark":     dsComputedString("uci option mark."),
			"out":      dsComputedString("uci option out."),
			"priority": dsComputedInt64("uci option priority."),
			"src":      dsComputedString("uci option src."),
		},
	}
}

func (d *networkRuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m networkRuleModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+networkRuleCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network rule", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("network rule not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&networkRuleResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
