// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const networkBridgeVlanCollection = "network/bridge_vlans"

var (
	_ resource.Resource                = &networkBridgeVlanResource{}
	_ resource.ResourceWithConfigure   = &networkBridgeVlanResource{}
	_ resource.ResourceWithImportState = &networkBridgeVlanResource{}
)

type networkBridgeVlanResource struct{ client *client.Client }

func NewNetworkBridgeVlanResource() resource.Resource { return &networkBridgeVlanResource{} }

type networkBridgeVlanModel struct {
	ID      types.String `tfsdk:"id"`
	Managed types.Bool   `tfsdk:"managed"`
	ETag    types.String `tfsdk:"etag"`
	Device  types.String `tfsdk:"device"`
	Ports   types.List   `tfsdk:"ports"`
	Vlan    types.Int64  `tfsdk:"vlan"`
}

func (r *networkBridgeVlanResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_bridge_vlan"
}

func (r *networkBridgeVlanResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *networkBridgeVlanResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Network bridge VLAN.",
		Attributes: map[string]schema.Attribute{
			"id":      computedIDAttribute(),
			"managed": managedAttribute(),
			"etag":    etagAttribute(),
			"device":  schema.StringAttribute{Required: true, Description: "Underlying device."},
			"ports":   optionalComputedStringList("uci option ports."),
			"vlan":    schema.Int64Attribute{Required: true, Description: "uci option vlan."},
		},
	}
}

func (r *networkBridgeVlanResource) body(ctx context.Context, m networkBridgeVlanModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "device", m.Device)
	putList(ctx, out, "ports", m.Ports, diags.d)
	putInt64(out, "vlan", m.Vlan)
	return out
}

func (r *networkBridgeVlanResource) read(ctx context.Context, obj map[string]any, m *networkBridgeVlanModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Device = strVal(obj, "device")
	m.Ports = diags.list(listVal(ctx, obj, "ports"))
	m.Vlan = int64Val(obj, "vlan")
}

func (r *networkBridgeVlanResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan networkBridgeVlanModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+networkBridgeVlanCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "network bridge VLAN", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkBridgeVlanResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state networkBridgeVlanModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+networkBridgeVlanCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network bridge VLAN", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *networkBridgeVlanResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state networkBridgeVlanModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+networkBridgeVlanCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "network bridge VLAN", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkBridgeVlanResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state networkBridgeVlanModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+networkBridgeVlanCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "network bridge VLAN", err)
	}
}

func (r *networkBridgeVlanResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, networkBridgeVlanCollection, "network bridge VLAN", req, resp)
}
