// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const networkRuleCollection = "network/rules"

var (
	_ resource.Resource                = &networkRuleResource{}
	_ resource.ResourceWithConfigure   = &networkRuleResource{}
	_ resource.ResourceWithImportState = &networkRuleResource{}
)

type networkRuleResource struct{ client *client.Client }

func NewNetworkRuleResource() resource.Resource { return &networkRuleResource{} }

type networkRuleModel struct {
	ID       types.String `tfsdk:"id"`
	Managed  types.Bool   `tfsdk:"managed"`
	ETag     types.String `tfsdk:"etag"`
	Action   types.String `tfsdk:"action"`
	Dest     types.String `tfsdk:"dest"`
	Goto     types.Int64  `tfsdk:"goto"`
	In       types.String `tfsdk:"in"`
	Invert   types.Bool   `tfsdk:"invert"`
	Lookup   types.Int64  `tfsdk:"lookup"`
	Mark     types.String `tfsdk:"mark"`
	Out      types.String `tfsdk:"out"`
	Priority types.Int64  `tfsdk:"priority"`
	Src      types.String `tfsdk:"src"`
}

func (r *networkRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_rule"
}

func (r *networkRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *networkRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Network rule.",
		Attributes: map[string]schema.Attribute{
			"id":       computedIDAttribute(),
			"managed":  managedAttribute(),
			"etag":     etagAttribute(),
			"action":   optionalComputedString("uci option action."),
			"dest":     optionalComputedString("uci option dest."),
			"goto":     optionalComputedInt64("uci option goto."),
			"in":       optionalComputedString("uci option in."),
			"invert":   optionalComputedBool("uci option invert."),
			"lookup":   optionalComputedInt64("uci option lookup."),
			"mark":     optionalComputedString("uci option mark."),
			"out":      optionalComputedString("uci option out."),
			"priority": optionalComputedInt64("uci option priority."),
			"src":      optionalComputedString("uci option src."),
		},
	}
}

func (r *networkRuleResource) body(ctx context.Context, m networkRuleModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "action", m.Action)
	putStr(out, "dest", m.Dest)
	putInt64(out, "goto", m.Goto)
	putStr(out, "in", m.In)
	putBool(out, "invert", m.Invert)
	putInt64(out, "lookup", m.Lookup)
	putStr(out, "mark", m.Mark)
	putStr(out, "out", m.Out)
	putInt64(out, "priority", m.Priority)
	putStr(out, "src", m.Src)
	return out
}

func (r *networkRuleResource) read(ctx context.Context, obj map[string]any, m *networkRuleModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Action = strVal(obj, "action")
	m.Dest = strVal(obj, "dest")
	m.Goto = int64Val(obj, "goto")
	m.In = strVal(obj, "in")
	m.Invert = boolVal(obj, "invert")
	m.Lookup = int64Val(obj, "lookup")
	m.Mark = strVal(obj, "mark")
	m.Out = strVal(obj, "out")
	m.Priority = int64Val(obj, "priority")
	m.Src = strVal(obj, "src")
}

func (r *networkRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan networkRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+networkRuleCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "network rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state networkRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+networkRuleCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network rule", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *networkRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state networkRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+networkRuleCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "network rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state networkRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+networkRuleCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "network rule", err)
	}
}

func (r *networkRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, networkRuleCollection, "network rule", req, resp)
}
