// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const networkDeviceCollection = "network/devices"

var (
	_ resource.Resource                = &networkDeviceResource{}
	_ resource.ResourceWithConfigure   = &networkDeviceResource{}
	_ resource.ResourceWithImportState = &networkDeviceResource{}
)

type networkDeviceResource struct{ client *client.Client }

func NewNetworkDeviceResource() resource.Resource { return &networkDeviceResource{} }

type networkDeviceModel struct {
	ID      types.String `tfsdk:"id"`
	Managed types.Bool   `tfsdk:"managed"`
	ETag    types.String `tfsdk:"etag"`
	Ifname  types.String `tfsdk:"ifname"`
	Ipv6    types.Bool   `tfsdk:"ipv6"`
	Macaddr types.String `tfsdk:"macaddr"`
	Mtu     types.Int64  `tfsdk:"mtu"`
	Name    types.String `tfsdk:"name"`
	Ports   types.List   `tfsdk:"ports"`
	Type    types.String `tfsdk:"type"`
	Vid     types.Int64  `tfsdk:"vid"`
}

func (r *networkDeviceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_device"
}

func (r *networkDeviceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *networkDeviceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A network device.",
		Attributes: map[string]schema.Attribute{
			"id":      computedIDAttribute(),
			"managed": managedAttribute(),
			"etag":    etagAttribute(),
			"ifname":  optionalComputedString("uci option ifname."),
			"ipv6":    optionalComputedBool("uci option ipv6."),
			"macaddr": optionalComputedString("uci option macaddr."),
			"mtu":     optionalComputedInt64("uci option mtu."),
			"name":    schema.StringAttribute{Required: true, Description: "Optional section name."},
			"ports":   optionalComputedStringList("uci option ports."),
			"type":    schema.StringAttribute{Required: true, Description: "uci option type."},
			"vid":     optionalComputedInt64("uci option vid."),
		},
	}
}

func (r *networkDeviceResource) body(ctx context.Context, m networkDeviceModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "ifname", m.Ifname)
	putBool(out, "ipv6", m.Ipv6)
	putStr(out, "macaddr", m.Macaddr)
	putInt64(out, "mtu", m.Mtu)
	putStr(out, "name", m.Name)
	putList(ctx, out, "ports", m.Ports, diags.d)
	putStr(out, "type", m.Type)
	putInt64(out, "vid", m.Vid)
	return out
}

func (r *networkDeviceResource) read(ctx context.Context, obj map[string]any, m *networkDeviceModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Ifname = strVal(obj, "ifname")
	m.Ipv6 = boolVal(obj, "ipv6")
	m.Macaddr = strVal(obj, "macaddr")
	m.Mtu = int64Val(obj, "mtu")
	m.Name = strVal(obj, "name")
	m.Ports = diags.list(listVal(ctx, obj, "ports"))
	m.Type = strVal(obj, "type")
	m.Vid = int64Val(obj, "vid")
}

func (r *networkDeviceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan networkDeviceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+networkDeviceCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "network device", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkDeviceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state networkDeviceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+networkDeviceCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network device", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *networkDeviceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state networkDeviceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+networkDeviceCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "network device", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkDeviceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state networkDeviceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+networkDeviceCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "network device", err)
	}
}

func (r *networkDeviceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, networkDeviceCollection, "network device", req, resp)
}
