// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

type networkInterfaceDSModel struct {
	ID            types.String                  `tfsdk:"id"`
	Managed       types.Bool                    `tfsdk:"managed"`
	ETag          types.String                  `tfsdk:"etag"`
	Addresses     types.List                    `tfsdk:"addresses"`
	Auto          types.Bool                    `tfsdk:"auto"`
	Clientid      types.String                  `tfsdk:"clientid"`
	Defaultroute  types.Bool                    `tfsdk:"defaultroute"`
	Delegate      types.Bool                    `tfsdk:"delegate"`
	Device        types.String                  `tfsdk:"device"`
	Dns           types.List                    `tfsdk:"dns"`
	Gateway       types.String                  `tfsdk:"gateway"`
	HasPrivateKey types.Bool                    `tfsdk:"has_private_key"`
	Hostname      types.String                  `tfsdk:"hostname"`
	Ip4table      types.String                  `tfsdk:"ip4table"`
	Ip6assign     types.Int64                   `tfsdk:"ip6assign"`
	Ip6hint       types.String                  `tfsdk:"ip6hint"`
	Ip6ifaceid    types.String                  `tfsdk:"ip6ifaceid"`
	Ip6table      types.String                  `tfsdk:"ip6table"`
	Ipaddr        types.String                  `tfsdk:"ipaddr"`
	Ipaddrs       types.List                    `tfsdk:"ipaddrs"`
	ListenPort    types.Int64                   `tfsdk:"listen_port"`
	Metric        types.Int64                   `tfsdk:"metric"`
	Mtu           types.Int64                   `tfsdk:"mtu"`
	Netmask       types.String                  `tfsdk:"netmask"`
	Nohostroute   types.Bool                    `tfsdk:"nohostroute"`
	Peerdns       types.Bool                    `tfsdk:"peerdns"`
	PrivateKey    types.String                  `tfsdk:"private_key"`
	Proto         types.String                  `tfsdk:"proto"`
	Reqaddress    types.String                  `tfsdk:"reqaddress"`
	Reqprefix     types.String                  `tfsdk:"reqprefix"`
	Runtime       *networkInterfaceRuntimeModel `tfsdk:"runtime"`
}

var (
	_ datasource.DataSource              = &networkInterfaceDataSource{}
	_ datasource.DataSourceWithConfigure = &networkInterfaceDataSource{}
)

type networkInterfaceDataSource struct{ client *client.Client }

func NewNetworkInterfaceDataSource() datasource.DataSource { return &networkInterfaceDataSource{} }

func (d *networkInterfaceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_interface"
}

func (d *networkInterfaceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *networkInterfaceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the network interface.",
		Attributes: map[string]dsschema.Attribute{
			"id":              dsIDAttribute(),
			"managed":         dsManagedAttribute(),
			"etag":            dsComputedString("Opaque ETag of the resource's current state."),
			"addresses":       dsComputedStringList("uci option addresses."),
			"auto":            dsComputedBool("uci option auto."),
			"clientid":        dsComputedString("uci option clientid."),
			"defaultroute":    dsComputedBool("uci option defaultroute."),
			"delegate":        dsComputedBool("uci option delegate."),
			"device":          dsComputedString("Underlying device."),
			"dns":             dsComputedStringList("uci option dns."),
			"gateway":         dsComputedString("uci option gateway."),
			"has_private_key": dsComputedBool("Whether a private key is configured."),
			"hostname":        dsComputedString("uci option hostname."),
			"ip4table":        dsComputedString("uci option ip4table."),
			"ip6assign":       dsComputedInt64("uci option ip6assign."),
			"ip6hint":         dsComputedString("uci option ip6hint."),
			"ip6ifaceid":      dsComputedString("uci option ip6ifaceid."),
			"ip6table":        dsComputedString("uci option ip6table."),
			"ipaddr":          dsComputedString("uci option ipaddr."),
			"ipaddrs":         dsComputedStringList("uci option ipaddrs."),
			"listen_port":     dsComputedInt64("uci option listen_port."),
			"metric":          dsComputedInt64("uci option metric."),
			"mtu":             dsComputedInt64("uci option mtu."),
			"netmask":         dsComputedString("uci option netmask."),
			"nohostroute":     dsComputedBool("uci option nohostroute."),
			"peerdns":         dsComputedBool("uci option peerdns."),
			"private_key":     dsschema.StringAttribute{Computed: true, Sensitive: true, Description: "Always null; never returned by the API."},
			"proto":           dsComputedString("Protocol."),
			"reqaddress":      dsComputedString("uci option reqaddress."),
			"reqprefix":       dsComputedString("uci option reqprefix."),
			"runtime":         networkInterfaceRuntimeAttribute(),
		},
	}
}

func (d *networkInterfaceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var id types.String
	resp.Diagnostics.Append(req.Config.GetAttribute(ctx, path.Root("id"), &id)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+networkInterfaceCollection+"/"+id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network interface", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("network interface not found", "not found")
		return
	}
	var base networkInterfaceModel
	ds := newDiagsink(&resp.Diagnostics)
	(&networkInterfaceResource{}).read(ctx, obj, &base, ds)
	base.ETag = types.StringValue(etag)
	m := networkInterfaceDSModel{
		ID: base.ID, Managed: base.Managed, ETag: base.ETag,
		Addresses:     base.Addresses,
		Auto:          base.Auto,
		Clientid:      base.Clientid,
		Defaultroute:  base.Defaultroute,
		Delegate:      base.Delegate,
		Device:        base.Device,
		Dns:           base.Dns,
		Gateway:       base.Gateway,
		HasPrivateKey: base.HasPrivateKey,
		Hostname:      base.Hostname,
		Ip4table:      base.Ip4table,
		Ip6assign:     base.Ip6assign,
		Ip6hint:       base.Ip6hint,
		Ip6ifaceid:    base.Ip6ifaceid,
		Ip6table:      base.Ip6table,
		Ipaddr:        base.Ipaddr,
		Ipaddrs:       base.Ipaddrs,
		ListenPort:    base.ListenPort,
		Metric:        base.Metric,
		Mtu:           base.Mtu,
		Netmask:       base.Netmask,
		Nohostroute:   base.Nohostroute,
		Peerdns:       base.Peerdns,
		PrivateKey:    base.PrivateKey,
		Proto:         base.Proto,
		Reqaddress:    base.Reqaddress,
		Reqprefix:     base.Reqprefix,
		Runtime:       parseNetworkInterfaceRuntime(obj),
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
