// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &networkWireguardPeerDataSource{}
	_ datasource.DataSourceWithConfigure = &networkWireguardPeerDataSource{}
)

type networkWireguardPeerDataSource struct{ client *client.Client }

func NewNetworkWireguardPeerDataSource() datasource.DataSource {
	return &networkWireguardPeerDataSource{}
}

func (d *networkWireguardPeerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_wireguard_peer"
}

func (d *networkWireguardPeerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *networkWireguardPeerDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the network WireGuard peer.",
		Attributes: map[string]dsschema.Attribute{
			"id":                   dsIDAttribute(),
			"managed":              dsManagedAttribute(),
			"etag":                 dsComputedString("Opaque ETag of the resource's current state."),
			"allowed_ips":          dsComputedStringList("uci option allowed_ips."),
			"description":          dsComputedString("uci option description."),
			"disabled":             dsComputedBool("Whether the entry is disabled."),
			"endpoint_host":        dsComputedString("uci option endpoint_host."),
			"endpoint_port":        dsComputedInt64("uci option endpoint_port."),
			"has_preshared_key":    dsComputedBool("Whether a preshared key is configured."),
			"interface":            dsComputedString("Network interface this entry applies to."),
			"persistent_keepalive": dsComputedInt64("uci option persistent_keepalive."),
			"preshared_key":        dsschema.StringAttribute{Computed: true, Sensitive: true, Description: "Always null; never returned by the API."},
			"public_key":           dsComputedString("uci option public_key."),
			"route_allowed_ips":    dsComputedBool("uci option route_allowed_ips."),
		},
	}
}

func (d *networkWireguardPeerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m networkWireguardPeerModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+networkWireguardPeerCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network WireGuard peer", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("network WireGuard peer not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&networkWireguardPeerResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
