// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const networkInterfaceCollection = "network/interfaces"

var (
	_ resource.Resource                = &networkInterfaceResource{}
	_ resource.ResourceWithConfigure   = &networkInterfaceResource{}
	_ resource.ResourceWithImportState = &networkInterfaceResource{}
)

type networkInterfaceResource struct{ client *client.Client }

func NewNetworkInterfaceResource() resource.Resource { return &networkInterfaceResource{} }

type networkInterfaceModel struct {
	ID            types.String `tfsdk:"id"`
	Managed       types.Bool   `tfsdk:"managed"`
	ETag          types.String `tfsdk:"etag"`
	Addresses     types.List   `tfsdk:"addresses"`
	Auto          types.Bool   `tfsdk:"auto"`
	Clientid      types.String `tfsdk:"clientid"`
	Defaultroute  types.Bool   `tfsdk:"defaultroute"`
	Delegate      types.Bool   `tfsdk:"delegate"`
	Device        types.String `tfsdk:"device"`
	Dns           types.List   `tfsdk:"dns"`
	Gateway       types.String `tfsdk:"gateway"`
	HasPrivateKey types.Bool   `tfsdk:"has_private_key"`
	Hostname      types.String `tfsdk:"hostname"`
	Ip4table      types.String `tfsdk:"ip4table"`
	Ip6assign     types.Int64  `tfsdk:"ip6assign"`
	Ip6hint       types.String `tfsdk:"ip6hint"`
	Ip6ifaceid    types.String `tfsdk:"ip6ifaceid"`
	Ip6table      types.String `tfsdk:"ip6table"`
	Ipaddr        types.String `tfsdk:"ipaddr"`
	Ipaddrs       types.List   `tfsdk:"ipaddrs"`
	ListenPort    types.Int64  `tfsdk:"listen_port"`
	Metric        types.Int64  `tfsdk:"metric"`
	Mtu           types.Int64  `tfsdk:"mtu"`
	Name          types.String `tfsdk:"name"`
	Netmask       types.String `tfsdk:"netmask"`
	Nohostroute   types.Bool   `tfsdk:"nohostroute"`
	Peerdns       types.Bool   `tfsdk:"peerdns"`
	PrivateKey    types.String `tfsdk:"private_key"`
	Proto         types.String `tfsdk:"proto"`
	Reqaddress    types.String `tfsdk:"reqaddress"`
	Reqprefix     types.String `tfsdk:"reqprefix"`
}

func (r *networkInterfaceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_interface"
}

func (r *networkInterfaceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *networkInterfaceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Network interface.",
		Attributes: map[string]schema.Attribute{
			"id":              computedIDAttribute(),
			"managed":         managedAttribute(),
			"etag":            etagAttribute(),
			"addresses":       optionalComputedStringList("uci option addresses."),
			"auto":            optionalComputedBool("uci option auto."),
			"clientid":        optionalComputedString("uci option clientid."),
			"defaultroute":    optionalComputedBool("uci option defaultroute."),
			"delegate":        optionalComputedBool("uci option delegate."),
			"device":          optionalComputedString("Underlying device."),
			"dns":             optionalComputedStringList("uci option dns."),
			"gateway":         optionalComputedString("uci option gateway."),
			"has_private_key": schema.BoolAttribute{Computed: true, Description: "Whether a private key is configured."},
			"hostname":        optionalComputedString("uci option hostname."),
			"ip4table":        optionalComputedString("uci option ip4table."),
			"ip6assign":       optionalComputedInt64("uci option ip6assign."),
			"ip6hint":         optionalComputedString("uci option ip6hint."),
			"ip6ifaceid":      optionalComputedString("uci option ip6ifaceid."),
			"ip6table":        optionalComputedString("uci option ip6table."),
			"ipaddr":          optionalComputedString("uci option ipaddr."),
			"ipaddrs":         optionalComputedStringList("uci option ipaddrs."),
			"listen_port":     optionalComputedInt64("uci option listen_port."),
			"metric":          optionalComputedInt64("uci option metric."),
			"mtu":             optionalComputedInt64("uci option mtu."),
			"name":            schema.StringAttribute{Optional: true, PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}, Description: "Create-time only; picks the uci section name (which becomes the uapi `id`). When omitted, the server emits a 14-char `wg_<rand>` for proto=wireguard (fits Linux IFNAMSIZ for the kernel netdev) or a 28-char ULID otherwise. Useful for LuCI parity (`lan`, `wan`, `guest`) and readable cross-references."},
			"netmask":         optionalComputedString("uci option netmask."),
			"nohostroute":     optionalComputedBool("uci option nohostroute."),
			"peerdns":         optionalComputedBool("uci option peerdns."),
			"private_key":     schema.StringAttribute{Optional: true, Sensitive: true, Description: "WireGuard private key. Write-only: never returned by the API."},
			"proto":           schema.StringAttribute{Required: true, Description: "Protocol."},
			"reqaddress":      optionalComputedString("uci option reqaddress."),
			"reqprefix":       optionalComputedString("uci option reqprefix."),
		},
	}
}

func (r *networkInterfaceResource) body(ctx context.Context, m networkInterfaceModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putList(ctx, out, "addresses", m.Addresses, diags.d)
	putBool(out, "auto", m.Auto)
	putStr(out, "clientid", m.Clientid)
	putBool(out, "defaultroute", m.Defaultroute)
	putBool(out, "delegate", m.Delegate)
	putStr(out, "device", m.Device)
	putList(ctx, out, "dns", m.Dns, diags.d)
	putStr(out, "gateway", m.Gateway)
	putStr(out, "hostname", m.Hostname)
	putStr(out, "ip4table", m.Ip4table)
	putInt64(out, "ip6assign", m.Ip6assign)
	putStr(out, "ip6hint", m.Ip6hint)
	putStr(out, "ip6ifaceid", m.Ip6ifaceid)
	putStr(out, "ip6table", m.Ip6table)
	putStr(out, "ipaddr", m.Ipaddr)
	putList(ctx, out, "ipaddrs", m.Ipaddrs, diags.d)
	putInt64(out, "listen_port", m.ListenPort)
	putInt64(out, "metric", m.Metric)
	putInt64(out, "mtu", m.Mtu)
	if create {
		putStr(out, "name", m.Name)
	}
	putStr(out, "netmask", m.Netmask)
	putBool(out, "nohostroute", m.Nohostroute)
	putBool(out, "peerdns", m.Peerdns)
	putStr(out, "private_key", m.PrivateKey)
	putStr(out, "proto", m.Proto)
	putStr(out, "reqaddress", m.Reqaddress)
	putStr(out, "reqprefix", m.Reqprefix)
	return out
}

func (r *networkInterfaceResource) read(ctx context.Context, obj map[string]any, m *networkInterfaceModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Addresses = diags.list(listVal(ctx, obj, "addresses"))
	m.Auto = boolVal(obj, "auto")
	m.Clientid = strVal(obj, "clientid")
	m.Defaultroute = boolVal(obj, "defaultroute")
	m.Delegate = boolVal(obj, "delegate")
	m.Device = strVal(obj, "device")
	m.Dns = diags.list(listVal(ctx, obj, "dns"))
	m.Gateway = strVal(obj, "gateway")
	m.HasPrivateKey = boolValDefault(obj, "has_private_key")
	m.Hostname = strVal(obj, "hostname")
	m.Ip4table = strVal(obj, "ip4table")
	m.Ip6assign = int64Val(obj, "ip6assign")
	m.Ip6hint = strVal(obj, "ip6hint")
	m.Ip6ifaceid = strVal(obj, "ip6ifaceid")
	m.Ip6table = strVal(obj, "ip6table")
	m.Ipaddr = strVal(obj, "ipaddr")
	m.Ipaddrs = diags.list(listVal(ctx, obj, "ipaddrs"))
	m.ListenPort = int64Val(obj, "listen_port")
	m.Metric = int64Val(obj, "metric")
	m.Mtu = int64Val(obj, "mtu")
	// name is create-only: preserve the planned value (the API never returns it).
	m.Netmask = strVal(obj, "netmask")
	m.Nohostroute = boolVal(obj, "nohostroute")
	m.Peerdns = boolVal(obj, "peerdns")
	// private_key is write-only: preserve the planned value (the API never returns it).
	m.Proto = strVal(obj, "proto")
	m.Reqaddress = strVal(obj, "reqaddress")
	m.Reqprefix = strVal(obj, "reqprefix")
}

func (r *networkInterfaceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan networkInterfaceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+networkInterfaceCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "network interface", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkInterfaceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state networkInterfaceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+networkInterfaceCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network interface", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *networkInterfaceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state networkInterfaceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+networkInterfaceCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "network interface", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkInterfaceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state networkInterfaceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+networkInterfaceCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "network interface", err)
	}
}

func (r *networkInterfaceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, networkInterfaceCollection, "network interface", req, resp)
}
