// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &networkRouteDataSource{}
	_ datasource.DataSourceWithConfigure = &networkRouteDataSource{}
)

type networkRouteDataSource struct{ client *client.Client }

func NewNetworkRouteDataSource() datasource.DataSource { return &networkRouteDataSource{} }

func (d *networkRouteDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_route"
}

func (d *networkRouteDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *networkRouteDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the network route.",
		Attributes: map[string]dsschema.Attribute{
			"id":        dsIDAttribute(),
			"managed":   dsManagedAttribute(),
			"etag":      dsComputedString("Opaque ETag of the resource's current state."),
			"gateway":   dsComputedString("uci option gateway."),
			"interface": dsComputedString("Network interface this entry applies to."),
			"metric":    dsComputedInt64("uci option metric."),
			"mtu":       dsComputedInt64("uci option mtu."),
			"netmask":   dsComputedString("uci option netmask."),
			"source":    dsComputedString("uci option source."),
			"table":     dsComputedInt64("uci option table."),
			"target":    dsComputedString("Target / action."),
			"type":      dsComputedString("uci option type."),
		},
	}
}

func (d *networkRouteDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m networkRouteModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+networkRouteCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network route", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("network route not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&networkRouteResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
