// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const networkRouteCollection = "network/routes"

var (
	_ resource.Resource                = &networkRouteResource{}
	_ resource.ResourceWithConfigure   = &networkRouteResource{}
	_ resource.ResourceWithImportState = &networkRouteResource{}
)

type networkRouteResource struct{ client *client.Client }

func NewNetworkRouteResource() resource.Resource { return &networkRouteResource{} }

type networkRouteModel struct {
	ID        types.String `tfsdk:"id"`
	Managed   types.Bool   `tfsdk:"managed"`
	ETag      types.String `tfsdk:"etag"`
	Gateway   types.String `tfsdk:"gateway"`
	Interface types.String `tfsdk:"interface"`
	Metric    types.Int64  `tfsdk:"metric"`
	Mtu       types.Int64  `tfsdk:"mtu"`
	Netmask   types.String `tfsdk:"netmask"`
	Source    types.String `tfsdk:"source"`
	Table     types.Int64  `tfsdk:"table"`
	Target    types.String `tfsdk:"target"`
	Type      types.String `tfsdk:"type"`
}

func (r *networkRouteResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_route"
}

func (r *networkRouteResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *networkRouteResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A network route.",
		Attributes: map[string]schema.Attribute{
			"id":        computedIDAttribute(),
			"managed":   managedAttribute(),
			"etag":      etagAttribute(),
			"gateway":   optionalComputedString("uci option gateway."),
			"interface": optionalComputedString("Network interface this entry applies to."),
			"metric":    optionalComputedInt64("uci option metric."),
			"mtu":       optionalComputedInt64("uci option mtu."),
			"netmask":   optionalComputedString("uci option netmask."),
			"source":    optionalComputedString("uci option source."),
			"table":     optionalComputedInt64("uci option table."),
			"target":    schema.StringAttribute{Required: true, Description: "Target / action."},
			"type":      optionalComputedString("uci option type."),
		},
	}
}

func (r *networkRouteResource) body(ctx context.Context, m networkRouteModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "gateway", m.Gateway)
	putStr(out, "interface", m.Interface)
	putInt64(out, "metric", m.Metric)
	putInt64(out, "mtu", m.Mtu)
	putStr(out, "netmask", m.Netmask)
	putStr(out, "source", m.Source)
	putInt64(out, "table", m.Table)
	putStr(out, "target", m.Target)
	putStr(out, "type", m.Type)
	return out
}

func (r *networkRouteResource) read(ctx context.Context, obj map[string]any, m *networkRouteModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Gateway = strVal(obj, "gateway")
	m.Interface = strVal(obj, "interface")
	m.Metric = int64Val(obj, "metric")
	m.Mtu = int64Val(obj, "mtu")
	m.Netmask = strVal(obj, "netmask")
	m.Source = strVal(obj, "source")
	m.Table = int64Val(obj, "table")
	m.Target = strVal(obj, "target")
	m.Type = strVal(obj, "type")
}

func (r *networkRouteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan networkRouteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+networkRouteCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "network route", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkRouteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state networkRouteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+networkRouteCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading network route", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *networkRouteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state networkRouteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+networkRouteCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "network route", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *networkRouteResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state networkRouteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+networkRouteCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "network route", err)
	}
}

func (r *networkRouteResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, networkRouteCollection, "network route", req, resp)
}
