// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const openvpnInstanceCollection = "openvpn/instances"

var (
	_ resource.Resource                = &openvpnInstanceResource{}
	_ resource.ResourceWithConfigure   = &openvpnInstanceResource{}
	_ resource.ResourceWithImportState = &openvpnInstanceResource{}
)

type openvpnInstanceResource struct{ client *client.Client }

func NewOpenvpnInstanceResource() resource.Resource { return &openvpnInstanceResource{} }

type openvpnInstanceModel struct {
	ID             types.String `tfsdk:"id"`
	Managed        types.Bool   `tfsdk:"managed"`
	ETag           types.String `tfsdk:"etag"`
	Auth           types.String `tfsdk:"auth"`
	Ca             types.String `tfsdk:"ca"`
	Cert           types.String `tfsdk:"cert"`
	Cipher         types.String `tfsdk:"cipher"`
	Client         types.Bool   `tfsdk:"client"`
	ClientToClient types.Bool   `tfsdk:"client_to_client"`
	CompLzo        types.String `tfsdk:"comp_lzo"`
	Compress       types.String `tfsdk:"compress"`
	CrlVerify      types.String `tfsdk:"crl_verify"`
	Dev            types.String `tfsdk:"dev"`
	DevType        types.String `tfsdk:"dev_type"`
	Dh             types.String `tfsdk:"dh"`
	DuplicateCn    types.Bool   `tfsdk:"duplicate_cn"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	Float          types.Bool   `tfsdk:"float"`
	Group          types.String `tfsdk:"group"`
	HasKey         types.Bool   `tfsdk:"has_key"`
	HasPkcs12      types.Bool   `tfsdk:"has_pkcs12"`
	HasTlsAuth     types.Bool   `tfsdk:"has_tls_auth"`
	Ifconfig       types.String `tfsdk:"ifconfig"`
	IfconfigPool   types.String `tfsdk:"ifconfig_pool"`
	Keepalive      types.String `tfsdk:"keepalive"`
	Key            types.String `tfsdk:"key"`
	Local          types.String `tfsdk:"local"`
	Log            types.String `tfsdk:"log"`
	LogAppend      types.String `tfsdk:"log_append"`
	Lport          types.Int64  `tfsdk:"lport"`
	Mute           types.Int64  `tfsdk:"mute"`
	NcpCiphers     types.String `tfsdk:"ncp_ciphers"`
	NcpDisable     types.Bool   `tfsdk:"ncp_disable"`
	Nobind         types.Bool   `tfsdk:"nobind"`
	PersistKey     types.Bool   `tfsdk:"persist_key"`
	PersistTun     types.Bool   `tfsdk:"persist_tun"`
	Ping           types.Int64  `tfsdk:"ping"`
	PingRestart    types.Int64  `tfsdk:"ping_restart"`
	Pkcs12         types.String `tfsdk:"pkcs12"`
	Port           types.Int64  `tfsdk:"port"`
	Proto          types.String `tfsdk:"proto"`
	Push           types.List   `tfsdk:"push"`
	Remote         types.List   `tfsdk:"remote"`
	RemoteCertTls  types.String `tfsdk:"remote_cert_tls"`
	Route          types.List   `tfsdk:"route"`
	RouteGateway   types.String `tfsdk:"route_gateway"`
	Rport          types.Int64  `tfsdk:"rport"`
	Server         types.String `tfsdk:"server"`
	ServerBridge   types.String `tfsdk:"server_bridge"`
	Status         types.String `tfsdk:"status"`
	TlsAuth        types.String `tfsdk:"tls_auth"`
	TlsClient      types.Bool   `tfsdk:"tls_client"`
	TlsCrypt       types.String `tfsdk:"tls_crypt"`
	TlsServer      types.Bool   `tfsdk:"tls_server"`
	Topology       types.String `tfsdk:"topology"`
	User           types.String `tfsdk:"user"`
	Verb           types.Int64  `tfsdk:"verb"`
	VerifyX509Name types.String `tfsdk:"verify_x509_name"`
}

func (r *openvpnInstanceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_openvpn_instance"
}

func (r *openvpnInstanceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *openvpnInstanceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A openvpn instance.",
		Attributes: map[string]schema.Attribute{
			"id":               computedIDAttribute(),
			"managed":          managedAttribute(),
			"etag":             etagAttribute(),
			"auth":             optionalComputedString("uci option auth."),
			"ca":               optionalComputedString("uci option ca."),
			"cert":             optionalComputedString("uci option cert."),
			"cipher":           optionalComputedString("uci option cipher."),
			"client":           optionalComputedBool("uci option client."),
			"client_to_client": optionalComputedBool("uci option client_to_client."),
			"comp_lzo":         optionalComputedString("uci option comp_lzo."),
			"compress":         optionalComputedString("uci option compress."),
			"crl_verify":       optionalComputedString("uci option crl_verify."),
			"dev":              optionalComputedString("uci option dev."),
			"dev_type":         optionalComputedString("uci option dev_type."),
			"dh":               optionalComputedString("uci option dh."),
			"duplicate_cn":     optionalComputedBool("uci option duplicate_cn."),
			"enabled":          optionalComputedBool("Whether the entry is active."),
			"float":            optionalComputedBool("uci option float."),
			"group":            optionalComputedString("uci option group."),
			"has_key":          schema.BoolAttribute{Computed: true, Description: "Whether a key is configured (the value is never returned)."},
			"has_pkcs12":       schema.BoolAttribute{Computed: true, Description: "Whether a PKCS#12 bundle is configured."},
			"has_tls_auth":     schema.BoolAttribute{Computed: true, Description: "Whether tls-auth/tls-crypt key material is configured."},
			"ifconfig":         optionalComputedString("uci option ifconfig."),
			"ifconfig_pool":    optionalComputedString("uci option ifconfig_pool."),
			"keepalive":        optionalComputedString("uci option keepalive."),
			"key":              schema.StringAttribute{Optional: true, Sensitive: true, Description: "Encryption passphrase. Write-only: never returned by the API."},
			"local":            optionalComputedString("uci option local."),
			"log":              optionalComputedString("uci option log."),
			"log_append":       optionalComputedString("uci option log_append."),
			"lport":            optionalComputedInt64("uci option lport."),
			"mute":             optionalComputedInt64("uci option mute."),
			"ncp_ciphers":      optionalComputedString("uci option ncp_ciphers."),
			"ncp_disable":      optionalComputedBool("uci option ncp_disable."),
			"nobind":           optionalComputedBool("uci option nobind."),
			"persist_key":      optionalComputedBool("uci option persist_key."),
			"persist_tun":      optionalComputedBool("uci option persist_tun."),
			"ping":             optionalComputedInt64("uci option ping."),
			"ping_restart":     optionalComputedInt64("uci option ping_restart."),
			"pkcs12":           schema.StringAttribute{Optional: true, Sensitive: true, Description: "OpenVPN PKCS#12 bundle. Write-only: never returned by the API."},
			"port":             optionalComputedInt64("uci option port."),
			"proto":            optionalComputedString("Protocol."),
			"push":             optionalComputedStringList("uci option push."),
			"remote":           optionalComputedStringList("uci option remote."),
			"remote_cert_tls":  optionalComputedString("uci option remote_cert_tls."),
			"route":            optionalComputedStringList("uci option route."),
			"route_gateway":    optionalComputedString("uci option route_gateway."),
			"rport":            optionalComputedInt64("uci option rport."),
			"server":           optionalComputedString("uci option server."),
			"server_bridge":    optionalComputedString("uci option server_bridge."),
			"status":           optionalComputedString("uci option status."),
			"tls_auth":         schema.StringAttribute{Optional: true, Sensitive: true, Description: "OpenVPN tls-auth/tls-crypt key material. Write-only: never returned by the API."},
			"tls_client":       optionalComputedBool("uci option tls_client."),
			"tls_crypt":        optionalComputedString("uci option tls_crypt."),
			"tls_server":       optionalComputedBool("uci option tls_server."),
			"topology":         optionalComputedString("uci option topology."),
			"user":             optionalComputedString("uci option user."),
			"verb":             optionalComputedInt64("uci option verb."),
			"verify_x509_name": optionalComputedString("uci option verify_x509_name."),
		},
	}
}

func (r *openvpnInstanceResource) body(ctx context.Context, m openvpnInstanceModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "auth", m.Auth)
	putStr(out, "ca", m.Ca)
	putStr(out, "cert", m.Cert)
	putStr(out, "cipher", m.Cipher)
	putBool(out, "client", m.Client)
	putBool(out, "client_to_client", m.ClientToClient)
	putStr(out, "comp_lzo", m.CompLzo)
	putStr(out, "compress", m.Compress)
	putStr(out, "crl_verify", m.CrlVerify)
	putStr(out, "dev", m.Dev)
	putStr(out, "dev_type", m.DevType)
	putStr(out, "dh", m.Dh)
	putBool(out, "duplicate_cn", m.DuplicateCn)
	putBool(out, "enabled", m.Enabled)
	putBool(out, "float", m.Float)
	putStr(out, "group", m.Group)
	putStr(out, "ifconfig", m.Ifconfig)
	putStr(out, "ifconfig_pool", m.IfconfigPool)
	putStr(out, "keepalive", m.Keepalive)
	putStr(out, "key", m.Key)
	putStr(out, "local", m.Local)
	putStr(out, "log", m.Log)
	putStr(out, "log_append", m.LogAppend)
	putInt64(out, "lport", m.Lport)
	putInt64(out, "mute", m.Mute)
	putStr(out, "ncp_ciphers", m.NcpCiphers)
	putBool(out, "ncp_disable", m.NcpDisable)
	putBool(out, "nobind", m.Nobind)
	putBool(out, "persist_key", m.PersistKey)
	putBool(out, "persist_tun", m.PersistTun)
	putInt64(out, "ping", m.Ping)
	putInt64(out, "ping_restart", m.PingRestart)
	putStr(out, "pkcs12", m.Pkcs12)
	putInt64(out, "port", m.Port)
	putStr(out, "proto", m.Proto)
	putList(ctx, out, "push", m.Push, diags.d)
	putList(ctx, out, "remote", m.Remote, diags.d)
	putStr(out, "remote_cert_tls", m.RemoteCertTls)
	putList(ctx, out, "route", m.Route, diags.d)
	putStr(out, "route_gateway", m.RouteGateway)
	putInt64(out, "rport", m.Rport)
	putStr(out, "server", m.Server)
	putStr(out, "server_bridge", m.ServerBridge)
	putStr(out, "status", m.Status)
	putStr(out, "tls_auth", m.TlsAuth)
	putBool(out, "tls_client", m.TlsClient)
	putStr(out, "tls_crypt", m.TlsCrypt)
	putBool(out, "tls_server", m.TlsServer)
	putStr(out, "topology", m.Topology)
	putStr(out, "user", m.User)
	putInt64(out, "verb", m.Verb)
	putStr(out, "verify_x509_name", m.VerifyX509Name)
	return out
}

func (r *openvpnInstanceResource) read(ctx context.Context, obj map[string]any, m *openvpnInstanceModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Auth = strVal(obj, "auth")
	m.Ca = strVal(obj, "ca")
	m.Cert = strVal(obj, "cert")
	m.Cipher = strVal(obj, "cipher")
	m.Client = boolVal(obj, "client")
	m.ClientToClient = boolVal(obj, "client_to_client")
	m.CompLzo = strVal(obj, "comp_lzo")
	m.Compress = strVal(obj, "compress")
	m.CrlVerify = strVal(obj, "crl_verify")
	m.Dev = strVal(obj, "dev")
	m.DevType = strVal(obj, "dev_type")
	m.Dh = strVal(obj, "dh")
	m.DuplicateCn = boolVal(obj, "duplicate_cn")
	m.Enabled = boolVal(obj, "enabled")
	m.Float = boolVal(obj, "float")
	m.Group = strVal(obj, "group")
	m.HasKey = boolValDefault(obj, "has_key")
	m.HasPkcs12 = boolValDefault(obj, "has_pkcs12")
	m.HasTlsAuth = boolValDefault(obj, "has_tls_auth")
	m.Ifconfig = strVal(obj, "ifconfig")
	m.IfconfigPool = strVal(obj, "ifconfig_pool")
	m.Keepalive = strVal(obj, "keepalive")
	// key is write-only: preserve the planned value (the API never returns it).
	m.Local = strVal(obj, "local")
	m.Log = strVal(obj, "log")
	m.LogAppend = strVal(obj, "log_append")
	m.Lport = int64Val(obj, "lport")
	m.Mute = int64Val(obj, "mute")
	m.NcpCiphers = strVal(obj, "ncp_ciphers")
	m.NcpDisable = boolVal(obj, "ncp_disable")
	m.Nobind = boolVal(obj, "nobind")
	m.PersistKey = boolVal(obj, "persist_key")
	m.PersistTun = boolVal(obj, "persist_tun")
	m.Ping = int64Val(obj, "ping")
	m.PingRestart = int64Val(obj, "ping_restart")
	// pkcs12 is write-only: preserve the planned value (the API never returns it).
	m.Port = int64Val(obj, "port")
	m.Proto = strVal(obj, "proto")
	m.Push = diags.list(listVal(ctx, obj, "push"))
	m.Remote = diags.list(listVal(ctx, obj, "remote"))
	m.RemoteCertTls = strVal(obj, "remote_cert_tls")
	m.Route = diags.list(listVal(ctx, obj, "route"))
	m.RouteGateway = strVal(obj, "route_gateway")
	m.Rport = int64Val(obj, "rport")
	m.Server = strVal(obj, "server")
	m.ServerBridge = strVal(obj, "server_bridge")
	m.Status = strVal(obj, "status")
	// tls_auth is write-only: preserve the planned value (the API never returns it).
	m.TlsClient = boolVal(obj, "tls_client")
	m.TlsCrypt = strVal(obj, "tls_crypt")
	m.TlsServer = boolVal(obj, "tls_server")
	m.Topology = strVal(obj, "topology")
	m.User = strVal(obj, "user")
	m.Verb = int64Val(obj, "verb")
	m.VerifyX509Name = strVal(obj, "verify_x509_name")
}

func (r *openvpnInstanceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan openvpnInstanceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+openvpnInstanceCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "openvpn instance", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *openvpnInstanceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state openvpnInstanceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+openvpnInstanceCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading openvpn instance", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *openvpnInstanceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state openvpnInstanceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+openvpnInstanceCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "openvpn instance", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *openvpnInstanceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state openvpnInstanceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+openvpnInstanceCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "openvpn instance", err)
	}
}

func (r *openvpnInstanceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, openvpnInstanceCollection, "openvpn instance", req, resp)
}
