// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &openvpnInstanceDataSource{}
	_ datasource.DataSourceWithConfigure = &openvpnInstanceDataSource{}
)

type openvpnInstanceDataSource struct{ client *client.Client }

func NewOpenvpnInstanceDataSource() datasource.DataSource { return &openvpnInstanceDataSource{} }

func (d *openvpnInstanceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_openvpn_instance"
}

func (d *openvpnInstanceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *openvpnInstanceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the openvpn instance.",
		Attributes: map[string]dsschema.Attribute{
			"id":               dsIDAttribute(),
			"managed":          dsManagedAttribute(),
			"etag":             dsComputedString("Opaque ETag of the resource's current state."),
			"auth":             dsComputedString("uci option auth."),
			"ca":               dsComputedString("uci option ca."),
			"cert":             dsComputedString("uci option cert."),
			"cipher":           dsComputedString("uci option cipher."),
			"client":           dsComputedBool("uci option client."),
			"client_to_client": dsComputedBool("uci option client_to_client."),
			"comp_lzo":         dsComputedString("uci option comp_lzo."),
			"compress":         dsComputedString("uci option compress."),
			"crl_verify":       dsComputedString("uci option crl_verify."),
			"dev":              dsComputedString("uci option dev."),
			"dev_type":         dsComputedString("uci option dev_type."),
			"dh":               dsComputedString("uci option dh."),
			"duplicate_cn":     dsComputedBool("uci option duplicate_cn."),
			"enabled":          dsComputedBool("Whether the entry is active."),
			"float":            dsComputedBool("uci option float."),
			"group":            dsComputedString("uci option group."),
			"has_key":          dsComputedBool("Whether a key is configured (the value is never returned)."),
			"has_pkcs12":       dsComputedBool("Whether a PKCS#12 bundle is configured."),
			"has_tls_auth":     dsComputedBool("Whether tls-auth/tls-crypt key material is configured."),
			"ifconfig":         dsComputedString("uci option ifconfig."),
			"ifconfig_pool":    dsComputedString("uci option ifconfig_pool."),
			"keepalive":        dsComputedString("uci option keepalive."),
			"key":              dsschema.StringAttribute{Computed: true, Sensitive: true, Description: "Always null; never returned by the API."},
			"local":            dsComputedString("uci option local."),
			"log":              dsComputedString("uci option log."),
			"log_append":       dsComputedString("uci option log_append."),
			"lport":            dsComputedInt64("uci option lport."),
			"mute":             dsComputedInt64("uci option mute."),
			"ncp_ciphers":      dsComputedString("uci option ncp_ciphers."),
			"ncp_disable":      dsComputedBool("uci option ncp_disable."),
			"nobind":           dsComputedBool("uci option nobind."),
			"persist_key":      dsComputedBool("uci option persist_key."),
			"persist_tun":      dsComputedBool("uci option persist_tun."),
			"ping":             dsComputedInt64("uci option ping."),
			"ping_restart":     dsComputedInt64("uci option ping_restart."),
			"pkcs12":           dsschema.StringAttribute{Computed: true, Sensitive: true, Description: "Always null; never returned by the API."},
			"port":             dsComputedInt64("uci option port."),
			"proto":            dsComputedString("Protocol."),
			"push":             dsComputedStringList("uci option push."),
			"remote":           dsComputedStringList("uci option remote."),
			"remote_cert_tls":  dsComputedString("uci option remote_cert_tls."),
			"route":            dsComputedStringList("uci option route."),
			"route_gateway":    dsComputedString("uci option route_gateway."),
			"rport":            dsComputedInt64("uci option rport."),
			"server":           dsComputedString("uci option server."),
			"server_bridge":    dsComputedString("uci option server_bridge."),
			"status":           dsComputedString("uci option status."),
			"tls_auth":         dsschema.StringAttribute{Computed: true, Sensitive: true, Description: "Always null; never returned by the API."},
			"tls_client":       dsComputedBool("uci option tls_client."),
			"tls_crypt":        dsComputedString("uci option tls_crypt."),
			"tls_server":       dsComputedBool("uci option tls_server."),
			"topology":         dsComputedString("uci option topology."),
			"user":             dsComputedString("uci option user."),
			"verb":             dsComputedInt64("uci option verb."),
			"verify_x509_name": dsComputedString("uci option verify_x509_name."),
		},
	}
}

func (d *openvpnInstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m openvpnInstanceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+openvpnInstanceCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading openvpn instance", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("openvpn instance not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&openvpnInstanceResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
