// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const prometheusNodeExporterLuaConfigPath = "/prometheus_node_exporter_lua/config"

var (
	_ resource.Resource                = &prometheusNodeExporterLuaConfigResource{}
	_ resource.ResourceWithConfigure   = &prometheusNodeExporterLuaConfigResource{}
	_ resource.ResourceWithImportState = &prometheusNodeExporterLuaConfigResource{}
)

type prometheusNodeExporterLuaConfigResource struct{ client *client.Client }

func NewPrometheusNodeExporterLuaConfigResource() resource.Resource {
	return &prometheusNodeExporterLuaConfigResource{}
}

type prometheusNodeExporterLuaConfigModel struct {
	ID              types.String `tfsdk:"id"`
	Managed         types.Bool   `tfsdk:"managed"`
	ETag            types.String `tfsdk:"etag"`
	Boottime        types.Bool   `tfsdk:"boottime"`
	Cpu             types.Bool   `tfsdk:"cpu"`
	Diskstats       types.Bool   `tfsdk:"diskstats"`
	Edac            types.Bool   `tfsdk:"edac"`
	Entropy         types.Bool   `tfsdk:"entropy"`
	Filesystem      types.Bool   `tfsdk:"filesystem"`
	Hwmon           types.Bool   `tfsdk:"hwmon"`
	ListenInterface types.String `tfsdk:"listen_interface"`
	ListenIpv6      types.Bool   `tfsdk:"listen_ipv6"`
	ListenPort      types.Int64  `tfsdk:"listen_port"`
	Loadavg         types.Bool   `tfsdk:"loadavg"`
	Meminfo         types.Bool   `tfsdk:"meminfo"`
	Netdev          types.Bool   `tfsdk:"netdev"`
	Netstat         types.Bool   `tfsdk:"netstat"`
	Stat            types.Bool   `tfsdk:"stat"`
	Textfile        types.Bool   `tfsdk:"textfile"`
	ThermalZone     types.Bool   `tfsdk:"thermal_zone"`
	Time            types.Bool   `tfsdk:"time"`
	Uname           types.Bool   `tfsdk:"uname"`
	Vmstat          types.Bool   `tfsdk:"vmstat"`
}

func (r *prometheusNodeExporterLuaConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_prometheus_node_exporter_lua_config"
}

func (r *prometheusNodeExporterLuaConfigResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *prometheusNodeExporterLuaConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A prometheus node_exporter config.",
		Attributes: map[string]schema.Attribute{
			"id":               computedIDAttribute(),
			"managed":          managedAttribute(),
			"etag":             etagAttribute(),
			"boottime":         optionalComputedBool("uci option boottime."),
			"cpu":              optionalComputedBool("uci option cpu."),
			"diskstats":        optionalComputedBool("uci option diskstats."),
			"edac":             optionalComputedBool("uci option edac."),
			"entropy":          optionalComputedBool("uci option entropy."),
			"filesystem":       optionalComputedBool("uci option filesystem."),
			"hwmon":            optionalComputedBool("uci option hwmon."),
			"listen_interface": optionalComputedString("uci option listen_interface."),
			"listen_ipv6":      optionalComputedBool("uci option listen_ipv6."),
			"listen_port":      optionalComputedInt64("uci option listen_port."),
			"loadavg":          optionalComputedBool("uci option loadavg."),
			"meminfo":          optionalComputedBool("uci option meminfo."),
			"netdev":           optionalComputedBool("uci option netdev."),
			"netstat":          optionalComputedBool("uci option netstat."),
			"stat":             optionalComputedBool("uci option stat."),
			"textfile":         optionalComputedBool("uci option textfile."),
			"thermal_zone":     optionalComputedBool("uci option thermal_zone."),
			"time":             optionalComputedBool("uci option time."),
			"uname":            optionalComputedBool("uci option uname."),
			"vmstat":           optionalComputedBool("uci option vmstat."),
		},
	}
}

func (r *prometheusNodeExporterLuaConfigResource) body(ctx context.Context, m prometheusNodeExporterLuaConfigModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putBool(out, "boottime", m.Boottime)
	putBool(out, "cpu", m.Cpu)
	putBool(out, "diskstats", m.Diskstats)
	putBool(out, "edac", m.Edac)
	putBool(out, "entropy", m.Entropy)
	putBool(out, "filesystem", m.Filesystem)
	putBool(out, "hwmon", m.Hwmon)
	putStr(out, "listen_interface", m.ListenInterface)
	putBool(out, "listen_ipv6", m.ListenIpv6)
	putInt64(out, "listen_port", m.ListenPort)
	putBool(out, "loadavg", m.Loadavg)
	putBool(out, "meminfo", m.Meminfo)
	putBool(out, "netdev", m.Netdev)
	putBool(out, "netstat", m.Netstat)
	putBool(out, "stat", m.Stat)
	putBool(out, "textfile", m.Textfile)
	putBool(out, "thermal_zone", m.ThermalZone)
	putBool(out, "time", m.Time)
	putBool(out, "uname", m.Uname)
	putBool(out, "vmstat", m.Vmstat)
	return out
}

func (r *prometheusNodeExporterLuaConfigResource) read(ctx context.Context, obj map[string]any, m *prometheusNodeExporterLuaConfigModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Boottime = boolVal(obj, "boottime")
	m.Cpu = boolVal(obj, "cpu")
	m.Diskstats = boolVal(obj, "diskstats")
	m.Edac = boolVal(obj, "edac")
	m.Entropy = boolVal(obj, "entropy")
	m.Filesystem = boolVal(obj, "filesystem")
	m.Hwmon = boolVal(obj, "hwmon")
	m.ListenInterface = strVal(obj, "listen_interface")
	m.ListenIpv6 = boolVal(obj, "listen_ipv6")
	m.ListenPort = int64Val(obj, "listen_port")
	m.Loadavg = boolVal(obj, "loadavg")
	m.Meminfo = boolVal(obj, "meminfo")
	m.Netdev = boolVal(obj, "netdev")
	m.Netstat = boolVal(obj, "netstat")
	m.Stat = boolVal(obj, "stat")
	m.Textfile = boolVal(obj, "textfile")
	m.ThermalZone = boolVal(obj, "thermal_zone")
	m.Time = boolVal(obj, "time")
	m.Uname = boolVal(obj, "uname")
	m.Vmstat = boolVal(obj, "vmstat")
}

func (r *prometheusNodeExporterLuaConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan prometheusNodeExporterLuaConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, prometheusNodeExporterLuaConfigPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "prometheus node_exporter config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *prometheusNodeExporterLuaConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state prometheusNodeExporterLuaConfigModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, prometheusNodeExporterLuaConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading prometheus node_exporter config", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *prometheusNodeExporterLuaConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state prometheusNodeExporterLuaConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, prometheusNodeExporterLuaConfigPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "prometheus node_exporter config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *prometheusNodeExporterLuaConfigResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *prometheusNodeExporterLuaConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
