// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &prometheusNodeExporterLuaConfigDataSource{}
	_ datasource.DataSourceWithConfigure = &prometheusNodeExporterLuaConfigDataSource{}
)

type prometheusNodeExporterLuaConfigDataSource struct{ client *client.Client }

func NewPrometheusNodeExporterLuaConfigDataSource() datasource.DataSource {
	return &prometheusNodeExporterLuaConfigDataSource{}
}

func (d *prometheusNodeExporterLuaConfigDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_prometheus_node_exporter_lua_config"
}

func (d *prometheusNodeExporterLuaConfigDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *prometheusNodeExporterLuaConfigDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the prometheus node_exporter config.",
		Attributes: map[string]dsschema.Attribute{
			"id":               dsComputedString("Stable id."),
			"managed":          dsManagedAttribute(),
			"etag":             dsComputedString("Opaque ETag of the resource's current state."),
			"boottime":         dsComputedBool("uci option boottime."),
			"cpu":              dsComputedBool("uci option cpu."),
			"diskstats":        dsComputedBool("uci option diskstats."),
			"edac":             dsComputedBool("uci option edac."),
			"entropy":          dsComputedBool("uci option entropy."),
			"filesystem":       dsComputedBool("uci option filesystem."),
			"hwmon":            dsComputedBool("uci option hwmon."),
			"listen_interface": dsComputedString("uci option listen_interface."),
			"listen_ipv6":      dsComputedBool("uci option listen_ipv6."),
			"listen_port":      dsComputedInt64("uci option listen_port."),
			"loadavg":          dsComputedBool("uci option loadavg."),
			"meminfo":          dsComputedBool("uci option meminfo."),
			"netdev":           dsComputedBool("uci option netdev."),
			"netstat":          dsComputedBool("uci option netstat."),
			"stat":             dsComputedBool("uci option stat."),
			"textfile":         dsComputedBool("uci option textfile."),
			"thermal_zone":     dsComputedBool("uci option thermal_zone."),
			"time":             dsComputedBool("uci option time."),
			"uname":            dsComputedBool("uci option uname."),
			"vmstat":           dsComputedBool("uci option vmstat."),
		},
	}
}

func (d *prometheusNodeExporterLuaConfigDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m prometheusNodeExporterLuaConfigModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, prometheusNodeExporterLuaConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading prometheus node_exporter config", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("prometheus node_exporter config not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&prometheusNodeExporterLuaConfigResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
