// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const snmpdCom2secCollection = "snmpd/com2secs"

var (
	_ resource.Resource                = &snmpdCom2secResource{}
	_ resource.ResourceWithConfigure   = &snmpdCom2secResource{}
	_ resource.ResourceWithImportState = &snmpdCom2secResource{}
)

type snmpdCom2secResource struct{ client *client.Client }

func NewSnmpdCom2secResource() resource.Resource { return &snmpdCom2secResource{} }

type snmpdCom2secModel struct {
	ID        types.String `tfsdk:"id"`
	Managed   types.Bool   `tfsdk:"managed"`
	ETag      types.String `tfsdk:"etag"`
	Community types.String `tfsdk:"community"`
	Secname   types.String `tfsdk:"secname"`
	Source    types.String `tfsdk:"source"`
}

func (r *snmpdCom2secResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmpd_com2sec"
}

func (r *snmpdCom2secResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *snmpdCom2secResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A snmpd com2sec.",
		Attributes: map[string]schema.Attribute{
			"id":        computedIDAttribute(),
			"managed":   managedAttribute(),
			"etag":      etagAttribute(),
			"community": schema.StringAttribute{Required: true, Description: "uci option community."},
			"secname":   schema.StringAttribute{Required: true, Description: "uci option secname."},
			"source":    schema.StringAttribute{Required: true, Description: "uci option source."},
		},
	}
}

func (r *snmpdCom2secResource) body(ctx context.Context, m snmpdCom2secModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "community", m.Community)
	putStr(out, "secname", m.Secname)
	putStr(out, "source", m.Source)
	return out
}

func (r *snmpdCom2secResource) read(ctx context.Context, obj map[string]any, m *snmpdCom2secModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Community = strVal(obj, "community")
	m.Secname = strVal(obj, "secname")
	m.Source = strVal(obj, "source")
}

func (r *snmpdCom2secResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan snmpdCom2secModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+snmpdCom2secCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "snmpd com2sec", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *snmpdCom2secResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state snmpdCom2secModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+snmpdCom2secCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading snmpd com2sec", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *snmpdCom2secResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state snmpdCom2secModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+snmpdCom2secCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "snmpd com2sec", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *snmpdCom2secResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state snmpdCom2secModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+snmpdCom2secCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "snmpd com2sec", err)
	}
}

func (r *snmpdCom2secResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, snmpdCom2secCollection, "snmpd com2sec", req, resp)
}
