// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &snmpdGroupDataSource{}
	_ datasource.DataSourceWithConfigure = &snmpdGroupDataSource{}
)

type snmpdGroupDataSource struct{ client *client.Client }

func NewSnmpdGroupDataSource() datasource.DataSource { return &snmpdGroupDataSource{} }

func (d *snmpdGroupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmpd_group"
}

func (d *snmpdGroupDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *snmpdGroupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the snmpd group.",
		Attributes: map[string]dsschema.Attribute{
			"id":      dsIDAttribute(),
			"managed": dsManagedAttribute(),
			"etag":    dsComputedString("Opaque ETag of the resource's current state."),
			"group":   dsComputedString("uci option group."),
			"secname": dsComputedString("uci option secname."),
			"version": dsComputedString("uci option version."),
		},
	}
}

func (d *snmpdGroupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m snmpdGroupModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+snmpdGroupCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading snmpd group", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("snmpd group not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&snmpdGroupResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
