// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const snmpdGroupCollection = "snmpd/groups"

var (
	_ resource.Resource                = &snmpdGroupResource{}
	_ resource.ResourceWithConfigure   = &snmpdGroupResource{}
	_ resource.ResourceWithImportState = &snmpdGroupResource{}
)

type snmpdGroupResource struct{ client *client.Client }

func NewSnmpdGroupResource() resource.Resource { return &snmpdGroupResource{} }

type snmpdGroupModel struct {
	ID      types.String `tfsdk:"id"`
	Managed types.Bool   `tfsdk:"managed"`
	ETag    types.String `tfsdk:"etag"`
	Group   types.String `tfsdk:"group"`
	Secname types.String `tfsdk:"secname"`
	Version types.String `tfsdk:"version"`
}

func (r *snmpdGroupResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmpd_group"
}

func (r *snmpdGroupResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *snmpdGroupResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Snmpd group.",
		Attributes: map[string]schema.Attribute{
			"id":      computedIDAttribute(),
			"managed": managedAttribute(),
			"etag":    etagAttribute(),
			"group":   schema.StringAttribute{Required: true, Description: "uci option group."},
			"secname": optionalComputedString("uci option secname."),
			"version": optionalComputedString("uci option version."),
		},
	}
}

func (r *snmpdGroupResource) body(ctx context.Context, m snmpdGroupModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "group", m.Group)
	putStr(out, "secname", m.Secname)
	putStr(out, "version", m.Version)
	return out
}

func (r *snmpdGroupResource) read(ctx context.Context, obj map[string]any, m *snmpdGroupModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Group = strVal(obj, "group")
	m.Secname = strVal(obj, "secname")
	m.Version = strVal(obj, "version")
}

func (r *snmpdGroupResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan snmpdGroupModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+snmpdGroupCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "snmpd group", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *snmpdGroupResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state snmpdGroupModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+snmpdGroupCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading snmpd group", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *snmpdGroupResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state snmpdGroupModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+snmpdGroupCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "snmpd group", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *snmpdGroupResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state snmpdGroupModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+snmpdGroupCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "snmpd group", err)
	}
}

func (r *snmpdGroupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, snmpdGroupCollection, "snmpd group", req, resp)
}
