// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &snmpdAccessDataSource{}
	_ datasource.DataSourceWithConfigure = &snmpdAccessDataSource{}
)

type snmpdAccessDataSource struct{ client *client.Client }

func NewSnmpdAccessDataSource() datasource.DataSource { return &snmpdAccessDataSource{} }

func (d *snmpdAccessDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmpd_access"
}

func (d *snmpdAccessDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *snmpdAccessDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the snmpd access.",
		Attributes: map[string]dsschema.Attribute{
			"id":      dsIDAttribute(),
			"managed": dsManagedAttribute(),
			"etag":    dsComputedString("Opaque ETag of the resource's current state."),
			"context": dsComputedString("uci option context."),
			"group":   dsComputedString("uci option group."),
			"level":   dsComputedString("uci option level."),
			"notify":  dsComputedString("uci option notify."),
			"prefix":  dsComputedString("uci option prefix."),
			"read":    dsComputedString("uci option read."),
			"version": dsComputedString("uci option version."),
			"write":   dsComputedString("uci option write."),
		},
	}
}

func (d *snmpdAccessDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m snmpdAccessModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+snmpdAccessCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading snmpd access", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("snmpd access not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&snmpdAccessResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
