// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const snmpdSystemPath = "/snmpd/system"

var (
	_ resource.Resource                = &snmpdSystemResource{}
	_ resource.ResourceWithConfigure   = &snmpdSystemResource{}
	_ resource.ResourceWithImportState = &snmpdSystemResource{}
)

type snmpdSystemResource struct{ client *client.Client }

func NewSnmpdSystemResource() resource.Resource { return &snmpdSystemResource{} }

type snmpdSystemModel struct {
	ID          types.String `tfsdk:"id"`
	Managed     types.Bool   `tfsdk:"managed"`
	ETag        types.String `tfsdk:"etag"`
	SysContact  types.String `tfsdk:"sys_contact"`
	SysDescr    types.String `tfsdk:"sys_descr"`
	SysLocation types.String `tfsdk:"sys_location"`
	SysName     types.String `tfsdk:"sys_name"`
	SysObjectId types.String `tfsdk:"sys_object_id"`
	SysServices types.Int64  `tfsdk:"sys_services"`
}

func (r *snmpdSystemResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmpd_system"
}

func (r *snmpdSystemResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *snmpdSystemResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Snmpd system.",
		Attributes: map[string]schema.Attribute{
			"id":            computedIDAttribute(),
			"managed":       managedAttribute(),
			"etag":          etagAttribute(),
			"sys_contact":   optionalComputedString("uci option sys_contact."),
			"sys_descr":     optionalComputedString("uci option sys_descr."),
			"sys_location":  optionalComputedString("uci option sys_location."),
			"sys_name":      optionalComputedString("uci option sys_name."),
			"sys_object_id": optionalComputedString("uci option sys_object_id."),
			"sys_services":  optionalComputedInt64("uci option sys_services."),
		},
	}
}

func (r *snmpdSystemResource) body(ctx context.Context, m snmpdSystemModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "sys_contact", m.SysContact)
	putStr(out, "sys_descr", m.SysDescr)
	putStr(out, "sys_location", m.SysLocation)
	putStr(out, "sys_name", m.SysName)
	putStr(out, "sys_object_id", m.SysObjectId)
	putInt64(out, "sys_services", m.SysServices)
	return out
}

func (r *snmpdSystemResource) read(ctx context.Context, obj map[string]any, m *snmpdSystemModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.SysContact = strVal(obj, "sys_contact")
	m.SysDescr = strVal(obj, "sys_descr")
	m.SysLocation = strVal(obj, "sys_location")
	m.SysName = strVal(obj, "sys_name")
	m.SysObjectId = strVal(obj, "sys_object_id")
	m.SysServices = int64Val(obj, "sys_services")
}

func (r *snmpdSystemResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan snmpdSystemModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, snmpdSystemPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "snmpd system", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *snmpdSystemResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state snmpdSystemModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, snmpdSystemPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading snmpd system", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *snmpdSystemResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state snmpdSystemModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, snmpdSystemPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "snmpd system", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *snmpdSystemResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *snmpdSystemResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
