// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &snmpdSystemDataSource{}
	_ datasource.DataSourceWithConfigure = &snmpdSystemDataSource{}
)

type snmpdSystemDataSource struct{ client *client.Client }

func NewSnmpdSystemDataSource() datasource.DataSource { return &snmpdSystemDataSource{} }

func (d *snmpdSystemDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmpd_system"
}

func (d *snmpdSystemDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *snmpdSystemDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the snmpd system.",
		Attributes: map[string]dsschema.Attribute{
			"id":            dsComputedString("Stable id."),
			"managed":       dsManagedAttribute(),
			"etag":          dsComputedString("Opaque ETag of the resource's current state."),
			"sys_contact":   dsComputedString("uci option sys_contact."),
			"sys_descr":     dsComputedString("uci option sys_descr."),
			"sys_location":  dsComputedString("uci option sys_location."),
			"sys_name":      dsComputedString("uci option sys_name."),
			"sys_object_id": dsComputedString("uci option sys_object_id."),
			"sys_services":  dsComputedInt64("uci option sys_services."),
		},
	}
}

func (d *snmpdSystemDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m snmpdSystemModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, snmpdSystemPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading snmpd system", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("snmpd system not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&snmpdSystemResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
