// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &snmpdCom2secDataSource{}
	_ datasource.DataSourceWithConfigure = &snmpdCom2secDataSource{}
)

type snmpdCom2secDataSource struct{ client *client.Client }

func NewSnmpdCom2secDataSource() datasource.DataSource { return &snmpdCom2secDataSource{} }

func (d *snmpdCom2secDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmpd_com2sec"
}

func (d *snmpdCom2secDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *snmpdCom2secDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the snmpd com2sec.",
		Attributes: map[string]dsschema.Attribute{
			"id":        dsIDAttribute(),
			"managed":   dsManagedAttribute(),
			"etag":      dsComputedString("Opaque ETag of the resource's current state."),
			"community": dsComputedString("uci option community."),
			"secname":   dsComputedString("uci option secname."),
			"source":    dsComputedString("uci option source."),
		},
	}
}

func (d *snmpdCom2secDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m snmpdCom2secModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+snmpdCom2secCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading snmpd com2sec", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("snmpd com2sec not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&snmpdCom2secResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
