// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const snmpdAccessCollection = "snmpd/accesses"

var (
	_ resource.Resource                = &snmpdAccessResource{}
	_ resource.ResourceWithConfigure   = &snmpdAccessResource{}
	_ resource.ResourceWithImportState = &snmpdAccessResource{}
)

type snmpdAccessResource struct{ client *client.Client }

func NewSnmpdAccessResource() resource.Resource { return &snmpdAccessResource{} }

type snmpdAccessModel struct {
	ID      types.String `tfsdk:"id"`
	Managed types.Bool   `tfsdk:"managed"`
	ETag    types.String `tfsdk:"etag"`
	Context types.String `tfsdk:"context"`
	Group   types.String `tfsdk:"group"`
	Level   types.String `tfsdk:"level"`
	Notify  types.String `tfsdk:"notify"`
	Prefix  types.String `tfsdk:"prefix"`
	Read    types.String `tfsdk:"read"`
	Version types.String `tfsdk:"version"`
	Write   types.String `tfsdk:"write"`
}

func (r *snmpdAccessResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmpd_access"
}

func (r *snmpdAccessResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *snmpdAccessResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A snmpd access.",
		Attributes: map[string]schema.Attribute{
			"id":      computedIDAttribute(),
			"managed": managedAttribute(),
			"etag":    etagAttribute(),
			"context": optionalComputedString("uci option context."),
			"group":   schema.StringAttribute{Required: true, Description: "uci option group."},
			"level":   optionalComputedString("uci option level."),
			"notify":  optionalComputedString("uci option notify."),
			"prefix":  optionalComputedString("uci option prefix."),
			"read":    optionalComputedString("uci option read."),
			"version": optionalComputedString("uci option version."),
			"write":   optionalComputedString("uci option write."),
		},
	}
}

func (r *snmpdAccessResource) body(ctx context.Context, m snmpdAccessModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "context", m.Context)
	putStr(out, "group", m.Group)
	putStr(out, "level", m.Level)
	putStr(out, "notify", m.Notify)
	putStr(out, "prefix", m.Prefix)
	putStr(out, "read", m.Read)
	putStr(out, "version", m.Version)
	putStr(out, "write", m.Write)
	return out
}

func (r *snmpdAccessResource) read(ctx context.Context, obj map[string]any, m *snmpdAccessModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Context = strVal(obj, "context")
	m.Group = strVal(obj, "group")
	m.Level = strVal(obj, "level")
	m.Notify = strVal(obj, "notify")
	m.Prefix = strVal(obj, "prefix")
	m.Read = strVal(obj, "read")
	m.Version = strVal(obj, "version")
	m.Write = strVal(obj, "write")
}

func (r *snmpdAccessResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan snmpdAccessModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+snmpdAccessCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "snmpd access", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *snmpdAccessResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state snmpdAccessModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+snmpdAccessCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading snmpd access", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *snmpdAccessResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state snmpdAccessModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+snmpdAccessCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "snmpd access", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *snmpdAccessResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state snmpdAccessModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+snmpdAccessCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "snmpd access", err)
	}
}

func (r *snmpdAccessResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, snmpdAccessCollection, "snmpd access", req, resp)
}
