// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const sqmQueueCollection = "sqm/queues"

var (
	_ resource.Resource                = &sqmQueueResource{}
	_ resource.ResourceWithConfigure   = &sqmQueueResource{}
	_ resource.ResourceWithImportState = &sqmQueueResource{}
)

type sqmQueueResource struct{ client *client.Client }

func NewSqmQueueResource() resource.Resource { return &sqmQueueResource{} }

type sqmQueueModel struct {
	ID        types.String `tfsdk:"id"`
	Managed   types.Bool   `tfsdk:"managed"`
	ETag      types.String `tfsdk:"etag"`
	Download  types.Int64  `tfsdk:"download"`
	Enabled   types.Bool   `tfsdk:"enabled"`
	Interface types.String `tfsdk:"interface"`
	Linklayer types.String `tfsdk:"linklayer"`
	Overhead  types.Int64  `tfsdk:"overhead"`
	Qdisc     types.String `tfsdk:"qdisc"`
	Script    types.String `tfsdk:"script"`
	Upload    types.Int64  `tfsdk:"upload"`
}

func (r *sqmQueueResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sqm_queue"
}

func (r *sqmQueueResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *sqmQueueResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A sqm queue.",
		Attributes: map[string]schema.Attribute{
			"id":        computedIDAttribute(),
			"managed":   managedAttribute(),
			"etag":      etagAttribute(),
			"download":  optionalComputedInt64("Download shaping rate in kbit/s."),
			"enabled":   optionalComputedBool("Whether the entry is active."),
			"interface": schema.StringAttribute{Required: true, Description: "Network interface this entry applies to."},
			"linklayer": optionalComputedString("uci option linklayer."),
			"overhead":  optionalComputedInt64("uci option overhead."),
			"qdisc":     optionalComputedString("uci option qdisc."),
			"script":    optionalComputedString("uci option script."),
			"upload":    optionalComputedInt64("Upload shaping rate in kbit/s."),
		},
	}
}

func (r *sqmQueueResource) body(ctx context.Context, m sqmQueueModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putInt64(out, "download", m.Download)
	putBool(out, "enabled", m.Enabled)
	putStr(out, "interface", m.Interface)
	putStr(out, "linklayer", m.Linklayer)
	putInt64(out, "overhead", m.Overhead)
	putStr(out, "qdisc", m.Qdisc)
	putStr(out, "script", m.Script)
	putInt64(out, "upload", m.Upload)
	return out
}

func (r *sqmQueueResource) read(ctx context.Context, obj map[string]any, m *sqmQueueModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Download = int64Val(obj, "download")
	m.Enabled = boolVal(obj, "enabled")
	m.Interface = strVal(obj, "interface")
	m.Linklayer = strVal(obj, "linklayer")
	m.Overhead = int64Val(obj, "overhead")
	m.Qdisc = strVal(obj, "qdisc")
	m.Script = strVal(obj, "script")
	m.Upload = int64Val(obj, "upload")
}

func (r *sqmQueueResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan sqmQueueModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+sqmQueueCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "sqm queue", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *sqmQueueResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state sqmQueueModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+sqmQueueCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading sqm queue", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *sqmQueueResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state sqmQueueModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+sqmQueueCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "sqm queue", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *sqmQueueResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state sqmQueueModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+sqmQueueCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "sqm queue", err)
	}
}

func (r *sqmQueueResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, sqmQueueCollection, "sqm queue", req, resp)
}
