// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &sqmQueueDataSource{}
	_ datasource.DataSourceWithConfigure = &sqmQueueDataSource{}
)

type sqmQueueDataSource struct{ client *client.Client }

func NewSqmQueueDataSource() datasource.DataSource { return &sqmQueueDataSource{} }

func (d *sqmQueueDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sqm_queue"
}

func (d *sqmQueueDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *sqmQueueDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the sqm queue.",
		Attributes: map[string]dsschema.Attribute{
			"id":        dsIDAttribute(),
			"managed":   dsManagedAttribute(),
			"etag":      dsComputedString("Opaque ETag of the resource's current state."),
			"download":  dsComputedInt64("Download shaping rate in kbit/s."),
			"enabled":   dsComputedBool("Whether the entry is active."),
			"interface": dsComputedString("Network interface this entry applies to."),
			"linklayer": dsComputedString("uci option linklayer."),
			"overhead":  dsComputedInt64("uci option overhead."),
			"qdisc":     dsComputedString("uci option qdisc."),
			"script":    dsComputedString("uci option script."),
			"upload":    dsComputedInt64("Upload shaping rate in kbit/s."),
		},
	}
}

func (d *sqmQueueDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m sqmQueueModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+sqmQueueCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading sqm queue", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("sqm queue not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&sqmQueueResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
