// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const systemPath = "/system"

var (
	_ resource.Resource                = &systemResource{}
	_ resource.ResourceWithConfigure   = &systemResource{}
	_ resource.ResourceWithImportState = &systemResource{}
)

type systemResource struct{ client *client.Client }

func NewSystemResource() resource.Resource { return &systemResource{} }

type systemModel struct {
	ID          types.String `tfsdk:"id"`
	Managed     types.Bool   `tfsdk:"managed"`
	ETag        types.String `tfsdk:"etag"`
	Description types.String `tfsdk:"description"`
	Hostname    types.String `tfsdk:"hostname"`
	LogIp       types.String `tfsdk:"log_ip"`
	LogProto    types.String `tfsdk:"log_proto"`
	LogRemote   types.Bool   `tfsdk:"log_remote"`
	LogSize     types.Int64  `tfsdk:"log_size"`
	Notes       types.String `tfsdk:"notes"`
	Timezone    types.String `tfsdk:"timezone"`
	UrandomSeed types.Bool   `tfsdk:"urandom_seed"`
	Zonename    types.String `tfsdk:"zonename"`
}

func (r *systemResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_system"
}

func (r *systemResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *systemResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A system settings.",
		Attributes: map[string]schema.Attribute{
			"id":           computedIDAttribute(),
			"managed":      managedAttribute(),
			"etag":         etagAttribute(),
			"description":  optionalComputedString("uci option description."),
			"hostname":     optionalComputedString("uci option hostname."),
			"log_ip":       optionalComputedString("uci option log_ip."),
			"log_proto":    optionalComputedString("uci option log_proto."),
			"log_remote":   optionalComputedBool("uci option log_remote."),
			"log_size":     optionalComputedInt64("uci option log_size."),
			"notes":        optionalComputedString("uci option notes."),
			"timezone":     optionalComputedString("uci option timezone."),
			"urandom_seed": optionalComputedBool("uci option urandom_seed."),
			"zonename":     optionalComputedString("uci option zonename."),
		},
	}
}

func (r *systemResource) body(ctx context.Context, m systemModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "description", m.Description)
	putStr(out, "hostname", m.Hostname)
	putStr(out, "log_ip", m.LogIp)
	putStr(out, "log_proto", m.LogProto)
	putBool(out, "log_remote", m.LogRemote)
	putInt64(out, "log_size", m.LogSize)
	putStr(out, "notes", m.Notes)
	putStr(out, "timezone", m.Timezone)
	putBool(out, "urandom_seed", m.UrandomSeed)
	putStr(out, "zonename", m.Zonename)
	return out
}

func (r *systemResource) read(ctx context.Context, obj map[string]any, m *systemModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Description = strVal(obj, "description")
	m.Hostname = strVal(obj, "hostname")
	m.LogIp = strVal(obj, "log_ip")
	m.LogProto = strVal(obj, "log_proto")
	m.LogRemote = boolVal(obj, "log_remote")
	m.LogSize = int64Val(obj, "log_size")
	m.Notes = strVal(obj, "notes")
	m.Timezone = strVal(obj, "timezone")
	m.UrandomSeed = boolVal(obj, "urandom_seed")
	m.Zonename = strVal(obj, "zonename")
}

func (r *systemResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan systemModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, systemPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "system settings", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *systemResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state systemModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, systemPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading system settings", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *systemResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state systemModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, systemPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "system settings", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *systemResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *systemResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
