// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &systemTimeserverDataSource{}
	_ datasource.DataSourceWithConfigure = &systemTimeserverDataSource{}
)

type systemTimeserverDataSource struct{ client *client.Client }

func NewSystemTimeserverDataSource() datasource.DataSource { return &systemTimeserverDataSource{} }

func (d *systemTimeserverDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_system_timeserver"
}

func (d *systemTimeserverDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *systemTimeserverDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the system timeserver.",
		Attributes: map[string]dsschema.Attribute{
			"id":            dsIDAttribute(),
			"managed":       dsManagedAttribute(),
			"etag":          dsComputedString("Opaque ETag of the resource's current state."),
			"enable_server": dsComputedBool("uci option enable_server."),
			"enabled":       dsComputedBool("Whether the entry is active."),
			"interface":     dsComputedString("Network interface this entry applies to."),
			"server":        dsComputedStringList("uci option server."),
			"use_dhcp":      dsComputedBool("uci option use_dhcp."),
		},
	}
}

func (d *systemTimeserverDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m systemTimeserverModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+systemTimeserverCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading system timeserver", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("system timeserver not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&systemTimeserverResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
