// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &systemDataSource{}
	_ datasource.DataSourceWithConfigure = &systemDataSource{}
)

type systemDataSource struct{ client *client.Client }

func NewSystemDataSource() datasource.DataSource { return &systemDataSource{} }

func (d *systemDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_system"
}

func (d *systemDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *systemDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the system settings.",
		Attributes: map[string]dsschema.Attribute{
			"id":           dsComputedString("Stable id."),
			"managed":      dsManagedAttribute(),
			"etag":         dsComputedString("Opaque ETag of the resource's current state."),
			"description":  dsComputedString("uci option description."),
			"hostname":     dsComputedString("uci option hostname."),
			"log_ip":       dsComputedString("uci option log_ip."),
			"log_proto":    dsComputedString("uci option log_proto."),
			"log_remote":   dsComputedBool("uci option log_remote."),
			"log_size":     dsComputedInt64("uci option log_size."),
			"notes":        dsComputedString("uci option notes."),
			"timezone":     dsComputedString("uci option timezone."),
			"urandom_seed": dsComputedBool("uci option urandom_seed."),
			"zonename":     dsComputedString("uci option zonename."),
		},
	}
}

func (d *systemDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m systemModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, systemPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading system settings", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("system settings not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&systemResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
