// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const systemTimeserverCollection = "system/timeservers"

var (
	_ resource.Resource                = &systemTimeserverResource{}
	_ resource.ResourceWithConfigure   = &systemTimeserverResource{}
	_ resource.ResourceWithImportState = &systemTimeserverResource{}
)

type systemTimeserverResource struct{ client *client.Client }

func NewSystemTimeserverResource() resource.Resource { return &systemTimeserverResource{} }

type systemTimeserverModel struct {
	ID           types.String `tfsdk:"id"`
	Managed      types.Bool   `tfsdk:"managed"`
	ETag         types.String `tfsdk:"etag"`
	EnableServer types.Bool   `tfsdk:"enable_server"`
	Enabled      types.Bool   `tfsdk:"enabled"`
	Interface    types.String `tfsdk:"interface"`
	Server       types.List   `tfsdk:"server"`
	UseDhcp      types.Bool   `tfsdk:"use_dhcp"`
}

func (r *systemTimeserverResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_system_timeserver"
}

func (r *systemTimeserverResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *systemTimeserverResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A system timeserver.",
		Attributes: map[string]schema.Attribute{
			"id":            computedIDAttribute(),
			"managed":       managedAttribute(),
			"etag":          etagAttribute(),
			"enable_server": optionalComputedBool("uci option enable_server."),
			"enabled":       optionalComputedBool("Whether the entry is active."),
			"interface":     optionalComputedString("Network interface this entry applies to."),
			"server":        optionalComputedStringList("uci option server."),
			"use_dhcp":      optionalComputedBool("uci option use_dhcp."),
		},
	}
}

func (r *systemTimeserverResource) body(ctx context.Context, m systemTimeserverModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putBool(out, "enable_server", m.EnableServer)
	putBool(out, "enabled", m.Enabled)
	putStr(out, "interface", m.Interface)
	putList(ctx, out, "server", m.Server, diags.d)
	putBool(out, "use_dhcp", m.UseDhcp)
	return out
}

func (r *systemTimeserverResource) read(ctx context.Context, obj map[string]any, m *systemTimeserverModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.EnableServer = boolVal(obj, "enable_server")
	m.Enabled = boolVal(obj, "enabled")
	m.Interface = strVal(obj, "interface")
	m.Server = diags.list(listVal(ctx, obj, "server"))
	m.UseDhcp = boolVal(obj, "use_dhcp")
}

func (r *systemTimeserverResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan systemTimeserverModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+systemTimeserverCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "system timeserver", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *systemTimeserverResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state systemTimeserverModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+systemTimeserverCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading system timeserver", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *systemTimeserverResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state systemTimeserverModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+systemTimeserverCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "system timeserver", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *systemTimeserverResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state systemTimeserverModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+systemTimeserverCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "system timeserver", err)
	}
}

func (r *systemTimeserverResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, systemTimeserverCollection, "system timeserver", req, resp)
}
