// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const uhttpdCertCollection = "uhttpd/certs"

var (
	_ resource.Resource                = &uhttpdCertResource{}
	_ resource.ResourceWithConfigure   = &uhttpdCertResource{}
	_ resource.ResourceWithImportState = &uhttpdCertResource{}
)

type uhttpdCertResource struct{ client *client.Client }

func NewUhttpdCertResource() resource.Resource { return &uhttpdCertResource{} }

type uhttpdCertModel struct {
	ID           types.String `tfsdk:"id"`
	Managed      types.Bool   `tfsdk:"managed"`
	ETag         types.String `tfsdk:"etag"`
	Bits         types.Int64  `tfsdk:"bits"`
	Commonname   types.String `tfsdk:"commonname"`
	Country      types.String `tfsdk:"country"`
	Days         types.Int64  `tfsdk:"days"`
	Location     types.String `tfsdk:"location"`
	Organization types.String `tfsdk:"organization"`
	State        types.String `tfsdk:"state"`
}

func (r *uhttpdCertResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_uhttpd_cert"
}

func (r *uhttpdCertResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *uhttpdCertResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Uhttpd cert.",
		Attributes: map[string]schema.Attribute{
			"id":           computedIDAttribute(),
			"managed":      managedAttribute(),
			"etag":         etagAttribute(),
			"bits":         optionalComputedInt64("uci option bits."),
			"commonname":   schema.StringAttribute{Required: true, Description: "uci option commonname."},
			"country":      optionalComputedString("uci option country."),
			"days":         optionalComputedInt64("uci option days."),
			"location":     optionalComputedString("uci option location."),
			"organization": optionalComputedString("uci option organization."),
			"state":        optionalComputedString("uci option state."),
		},
	}
}

func (r *uhttpdCertResource) body(ctx context.Context, m uhttpdCertModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putInt64(out, "bits", m.Bits)
	putStr(out, "commonname", m.Commonname)
	putStr(out, "country", m.Country)
	putInt64(out, "days", m.Days)
	putStr(out, "location", m.Location)
	putStr(out, "organization", m.Organization)
	putStr(out, "state", m.State)
	return out
}

func (r *uhttpdCertResource) read(ctx context.Context, obj map[string]any, m *uhttpdCertModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Bits = int64Val(obj, "bits")
	m.Commonname = strVal(obj, "commonname")
	m.Country = strVal(obj, "country")
	m.Days = int64Val(obj, "days")
	m.Location = strVal(obj, "location")
	m.Organization = strVal(obj, "organization")
	m.State = strVal(obj, "state")
}

func (r *uhttpdCertResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan uhttpdCertModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+uhttpdCertCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "uhttpd cert", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *uhttpdCertResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state uhttpdCertModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+uhttpdCertCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading uhttpd cert", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *uhttpdCertResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state uhttpdCertModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+uhttpdCertCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "uhttpd cert", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *uhttpdCertResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state uhttpdCertModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+uhttpdCertCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "uhttpd cert", err)
	}
}

func (r *uhttpdCertResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, uhttpdCertCollection, "uhttpd cert", req, resp)
}
