// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &uhttpdInstanceDataSource{}
	_ datasource.DataSourceWithConfigure = &uhttpdInstanceDataSource{}
)

type uhttpdInstanceDataSource struct{ client *client.Client }

func NewUhttpdInstanceDataSource() datasource.DataSource { return &uhttpdInstanceDataSource{} }

func (d *uhttpdInstanceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_uhttpd_instance"
}

func (d *uhttpdInstanceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *uhttpdInstanceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the uhttpd instance.",
		Attributes: map[string]dsschema.Attribute{
			"id":              dsIDAttribute(),
			"managed":         dsManagedAttribute(),
			"etag":            dsComputedString("Opaque ETag of the resource's current state."),
			"cert":            dsComputedString("uci option cert."),
			"cgi_prefix":      dsComputedString("uci option cgi_prefix."),
			"error_page":      dsComputedString("uci option error_page."),
			"home":            dsComputedString("uci option home."),
			"http_keepalive":  dsComputedInt64("uci option http_keepalive."),
			"index_page":      dsComputedStringList("uci option index_page."),
			"key":             dsComputedString("Encryption passphrase. Write-only: never returned by the API."),
			"listen_http":     dsComputedStringList("uci option listen_http."),
			"listen_https":    dsComputedStringList("uci option listen_https."),
			"lua_prefix":      dsComputedStringList("uci option lua_prefix."),
			"max_connections": dsComputedInt64("uci option max_connections."),
			"max_requests":    dsComputedInt64("uci option max_requests."),
			"network_timeout": dsComputedInt64("uci option network_timeout."),
			"no_dirlists":     dsComputedBool("uci option no_dirlists."),
			"no_symlinks":     dsComputedBool("uci option no_symlinks."),
			"rfc1918_filter":  dsComputedBool("uci option rfc1918_filter."),
			"script_timeout":  dsComputedInt64("uci option script_timeout."),
			"tcp_keepalive":   dsComputedInt64("uci option tcp_keepalive."),
			"ucode_prefix":    dsComputedStringList("uci option ucode_prefix."),
		},
	}
}

func (d *uhttpdInstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m uhttpdInstanceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+uhttpdInstanceCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading uhttpd instance", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("uhttpd instance not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&uhttpdInstanceResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
