// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &uhttpdCertDataSource{}
	_ datasource.DataSourceWithConfigure = &uhttpdCertDataSource{}
)

type uhttpdCertDataSource struct{ client *client.Client }

func NewUhttpdCertDataSource() datasource.DataSource { return &uhttpdCertDataSource{} }

func (d *uhttpdCertDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_uhttpd_cert"
}

func (d *uhttpdCertDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *uhttpdCertDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the uhttpd cert.",
		Attributes: map[string]dsschema.Attribute{
			"id":           dsIDAttribute(),
			"managed":      dsManagedAttribute(),
			"etag":         dsComputedString("Opaque ETag of the resource's current state."),
			"bits":         dsComputedInt64("uci option bits."),
			"commonname":   dsComputedString("uci option commonname."),
			"country":      dsComputedString("uci option country."),
			"days":         dsComputedInt64("uci option days."),
			"location":     dsComputedString("uci option location."),
			"organization": dsComputedString("uci option organization."),
			"state":        dsComputedString("uci option state."),
		},
	}
}

func (d *uhttpdCertDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m uhttpdCertModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+uhttpdCertCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading uhttpd cert", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("uhttpd cert not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&uhttpdCertResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
