// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const uhttpdInstanceCollection = "uhttpd/instances"

var (
	_ resource.Resource                = &uhttpdInstanceResource{}
	_ resource.ResourceWithConfigure   = &uhttpdInstanceResource{}
	_ resource.ResourceWithImportState = &uhttpdInstanceResource{}
)

type uhttpdInstanceResource struct{ client *client.Client }

func NewUhttpdInstanceResource() resource.Resource { return &uhttpdInstanceResource{} }

type uhttpdInstanceModel struct {
	ID             types.String `tfsdk:"id"`
	Managed        types.Bool   `tfsdk:"managed"`
	ETag           types.String `tfsdk:"etag"`
	Cert           types.String `tfsdk:"cert"`
	CgiPrefix      types.String `tfsdk:"cgi_prefix"`
	ErrorPage      types.String `tfsdk:"error_page"`
	Home           types.String `tfsdk:"home"`
	HttpKeepalive  types.Int64  `tfsdk:"http_keepalive"`
	IndexPage      types.List   `tfsdk:"index_page"`
	Key            types.String `tfsdk:"key"`
	ListenHttp     types.List   `tfsdk:"listen_http"`
	ListenHttps    types.List   `tfsdk:"listen_https"`
	LuaPrefix      types.List   `tfsdk:"lua_prefix"`
	MaxConnections types.Int64  `tfsdk:"max_connections"`
	MaxRequests    types.Int64  `tfsdk:"max_requests"`
	NetworkTimeout types.Int64  `tfsdk:"network_timeout"`
	NoDirlists     types.Bool   `tfsdk:"no_dirlists"`
	NoSymlinks     types.Bool   `tfsdk:"no_symlinks"`
	Rfc1918Filter  types.Bool   `tfsdk:"rfc1918_filter"`
	ScriptTimeout  types.Int64  `tfsdk:"script_timeout"`
	TcpKeepalive   types.Int64  `tfsdk:"tcp_keepalive"`
	UcodePrefix    types.List   `tfsdk:"ucode_prefix"`
}

func (r *uhttpdInstanceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_uhttpd_instance"
}

func (r *uhttpdInstanceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *uhttpdInstanceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Uhttpd instance.",
		Attributes: map[string]schema.Attribute{
			"id":              optionalComputedIDAttribute(),
			"managed":         managedAttribute(),
			"etag":            etagAttribute(),
			"cert":            optionalComputedString("uci option cert."),
			"cgi_prefix":      optionalComputedString("uci option cgi_prefix."),
			"error_page":      optionalComputedString("uci option error_page."),
			"home":            optionalComputedString("uci option home."),
			"http_keepalive":  optionalComputedInt64("uci option http_keepalive."),
			"index_page":      optionalComputedStringList("uci option index_page."),
			"key":             optionalComputedString("Encryption passphrase. Write-only: never returned by the API."),
			"listen_http":     optionalComputedStringList("uci option listen_http."),
			"listen_https":    optionalComputedStringList("uci option listen_https."),
			"lua_prefix":      optionalComputedStringList("uci option lua_prefix."),
			"max_connections": optionalComputedInt64("uci option max_connections."),
			"max_requests":    optionalComputedInt64("uci option max_requests."),
			"network_timeout": optionalComputedInt64("uci option network_timeout."),
			"no_dirlists":     optionalComputedBool("uci option no_dirlists."),
			"no_symlinks":     optionalComputedBool("uci option no_symlinks."),
			"rfc1918_filter":  optionalComputedBool("uci option rfc1918_filter."),
			"script_timeout":  optionalComputedInt64("uci option script_timeout."),
			"tcp_keepalive":   optionalComputedInt64("uci option tcp_keepalive."),
			"ucode_prefix":    optionalComputedStringList("uci option ucode_prefix."),
		},
	}
}

func (r *uhttpdInstanceResource) body(ctx context.Context, m uhttpdInstanceModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	if create {
		putStr(out, "id", m.ID)
	}
	putStr(out, "cert", m.Cert)
	putStr(out, "cgi_prefix", m.CgiPrefix)
	putStr(out, "error_page", m.ErrorPage)
	putStr(out, "home", m.Home)
	putInt64(out, "http_keepalive", m.HttpKeepalive)
	putList(ctx, out, "index_page", m.IndexPage, diags.d)
	putStr(out, "key", m.Key)
	putList(ctx, out, "listen_http", m.ListenHttp, diags.d)
	putList(ctx, out, "listen_https", m.ListenHttps, diags.d)
	putList(ctx, out, "lua_prefix", m.LuaPrefix, diags.d)
	putInt64(out, "max_connections", m.MaxConnections)
	putInt64(out, "max_requests", m.MaxRequests)
	putInt64(out, "network_timeout", m.NetworkTimeout)
	putBool(out, "no_dirlists", m.NoDirlists)
	putBool(out, "no_symlinks", m.NoSymlinks)
	putBool(out, "rfc1918_filter", m.Rfc1918Filter)
	putInt64(out, "script_timeout", m.ScriptTimeout)
	putInt64(out, "tcp_keepalive", m.TcpKeepalive)
	putList(ctx, out, "ucode_prefix", m.UcodePrefix, diags.d)
	return out
}

func (r *uhttpdInstanceResource) read(ctx context.Context, obj map[string]any, m *uhttpdInstanceModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Cert = strVal(obj, "cert")
	m.CgiPrefix = strVal(obj, "cgi_prefix")
	m.ErrorPage = strVal(obj, "error_page")
	m.Home = strVal(obj, "home")
	m.HttpKeepalive = int64Val(obj, "http_keepalive")
	m.IndexPage = diags.list(listVal(ctx, obj, "index_page"))
	m.Key = strVal(obj, "key")
	m.ListenHttp = diags.list(listVal(ctx, obj, "listen_http"))
	m.ListenHttps = diags.list(listVal(ctx, obj, "listen_https"))
	m.LuaPrefix = diags.list(listVal(ctx, obj, "lua_prefix"))
	m.MaxConnections = int64Val(obj, "max_connections")
	m.MaxRequests = int64Val(obj, "max_requests")
	m.NetworkTimeout = int64Val(obj, "network_timeout")
	m.NoDirlists = boolVal(obj, "no_dirlists")
	m.NoSymlinks = boolVal(obj, "no_symlinks")
	m.Rfc1918Filter = boolVal(obj, "rfc1918_filter")
	m.ScriptTimeout = int64Val(obj, "script_timeout")
	m.TcpKeepalive = int64Val(obj, "tcp_keepalive")
	m.UcodePrefix = diags.list(listVal(ctx, obj, "ucode_prefix"))
}

func (r *uhttpdInstanceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan uhttpdInstanceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+uhttpdInstanceCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "uhttpd instance", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *uhttpdInstanceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state uhttpdInstanceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+uhttpdInstanceCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading uhttpd instance", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *uhttpdInstanceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state uhttpdInstanceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+uhttpdInstanceCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "uhttpd instance", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *uhttpdInstanceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state uhttpdInstanceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+uhttpdInstanceCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "uhttpd instance", err)
	}
}

func (r *uhttpdInstanceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, uhttpdInstanceCollection, "uhttpd instance", req, resp)
}
