// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &unboundSrvDataSource{}
	_ datasource.DataSourceWithConfigure = &unboundSrvDataSource{}
)

type unboundSrvDataSource struct{ client *client.Client }

func NewUnboundSrvDataSource() datasource.DataSource { return &unboundSrvDataSource{} }

func (d *unboundSrvDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unbound_srv"
}

func (d *unboundSrvDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *unboundSrvDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the unbound srv options.",
		Attributes: map[string]dsschema.Attribute{
			"id":                 dsComputedString("Stable id."),
			"managed":            dsManagedAttribute(),
			"etag":               dsComputedString("Opaque ETag of the resource's current state."),
			"enabled":            dsComputedBool("Whether the entry is active."),
			"interface_bind":     dsComputedStringList("Addresses unbound binds on (`addr` or `addr@port`). Pair with the main unbound `interface_auto = false` for exclusive binding."),
			"interface_outgoing": dsComputedStringList("Source addresses for upstream recursion (multi-WAN egress)."),
			"ip_transparent":     dsComputedBool("Bind to addresses that are not yet up (VIP / alias / floating addresses)."),
			"srv_line":           dsComputedStringList("Verbatim lines inserted inside unbound's `server:` clause. One entry per line; `unbound-checkconf` validates grammar after restart."),
		},
	}
}

func (d *unboundSrvDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m unboundSrvModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, unboundSrvPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading unbound srv options", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("unbound srv options not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&unboundSrvResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
