// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const unboundExtPath = "/unbound/ext"

var (
	_ resource.Resource                = &unboundExtResource{}
	_ resource.ResourceWithConfigure   = &unboundExtResource{}
	_ resource.ResourceWithImportState = &unboundExtResource{}
)

type unboundExtResource struct{ client *client.Client }

func NewUnboundExtResource() resource.Resource { return &unboundExtResource{} }

type unboundExtModel struct {
	ID      types.String `tfsdk:"id"`
	Managed types.Bool   `tfsdk:"managed"`
	ETag    types.String `tfsdk:"etag"`
	Enabled types.Bool   `tfsdk:"enabled"`
	ExtLine types.List   `tfsdk:"ext_line"`
}

func (r *unboundExtResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unbound_ext"
}

func (r *unboundExtResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *unboundExtResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Unbound ext config.",
		Attributes: map[string]schema.Attribute{
			"id":       computedIDAttribute(),
			"managed":  managedAttribute(),
			"etag":     etagAttribute(),
			"enabled":  optionalComputedBool("Whether the entry is active."),
			"ext_line": optionalComputedStringList("Verbatim lines rendered into unbound_ext.conf, outside the `server:` clause. One entry per line; build whole `forward-zone:`/`view:`/`stub:` clauses by listing them in order."),
		},
	}
}

func (r *unboundExtResource) body(ctx context.Context, m unboundExtModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putBool(out, "enabled", m.Enabled)
	putList(ctx, out, "ext_line", m.ExtLine, diags.d)
	return out
}

func (r *unboundExtResource) read(ctx context.Context, obj map[string]any, m *unboundExtModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Enabled = boolVal(obj, "enabled")
	m.ExtLine = diags.list(listVal(ctx, obj, "ext_line"))
}

func (r *unboundExtResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan unboundExtModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, unboundExtPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "unbound ext config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *unboundExtResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state unboundExtModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, unboundExtPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading unbound ext config", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *unboundExtResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state unboundExtModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, unboundExtPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "unbound ext config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *unboundExtResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *unboundExtResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
