// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &unboundExtDataSource{}
	_ datasource.DataSourceWithConfigure = &unboundExtDataSource{}
)

type unboundExtDataSource struct{ client *client.Client }

func NewUnboundExtDataSource() datasource.DataSource { return &unboundExtDataSource{} }

func (d *unboundExtDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unbound_ext"
}

func (d *unboundExtDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *unboundExtDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the unbound ext config.",
		Attributes: map[string]dsschema.Attribute{
			"id":       dsComputedString("Stable id."),
			"managed":  dsManagedAttribute(),
			"etag":     dsComputedString("Opaque ETag of the resource's current state."),
			"enabled":  dsComputedBool("Whether the entry is active."),
			"ext_line": dsComputedStringList("Verbatim lines rendered into unbound_ext.conf, outside the `server:` clause. One entry per line; build whole `forward-zone:`/`view:`/`stub:` clauses by listing them in order."),
		},
	}
}

func (d *unboundExtDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m unboundExtModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, unboundExtPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading unbound ext config", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("unbound ext config not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&unboundExtResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
