// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const unboundServerPath = "/unbound/server"

var (
	_ resource.Resource                = &unboundServerResource{}
	_ resource.ResourceWithConfigure   = &unboundServerResource{}
	_ resource.ResourceWithImportState = &unboundServerResource{}
)

type unboundServerResource struct{ client *client.Client }

func NewUnboundServerResource() resource.Resource { return &unboundServerResource{} }

type unboundServerModel struct {
	ID               types.String `tfsdk:"id"`
	Managed          types.Bool   `tfsdk:"managed"`
	ETag             types.String `tfsdk:"etag"`
	AddLocalFqdn     types.Int64  `tfsdk:"add_local_fqdn"`
	AddWanFqdn       types.Int64  `tfsdk:"add_wan_fqdn"`
	DhcpLink         types.String `tfsdk:"dhcp_link"`
	DnssecEnabled    types.Bool   `tfsdk:"dnssec_enabled"`
	Domain           types.String `tfsdk:"domain"`
	DomainType       types.String `tfsdk:"domain_type"`
	Enabled          types.Bool   `tfsdk:"enabled"`
	ExtendedStats    types.Bool   `tfsdk:"extended_stats"`
	HideBinddata     types.Bool   `tfsdk:"hide_binddata"`
	InterfaceAuto    types.Bool   `tfsdk:"interface_auto"`
	ListenPort       types.Int64  `tfsdk:"listen_port"`
	Localservice     types.Bool   `tfsdk:"localservice"`
	ManualConf       types.Bool   `tfsdk:"manual_conf"`
	NumThreads       types.Int64  `tfsdk:"num_threads"`
	Prefetch         types.Bool   `tfsdk:"prefetch"`
	Protocol         types.String `tfsdk:"protocol"`
	QueryMinimize    types.Bool   `tfsdk:"query_minimize"`
	RebindProtection types.String `tfsdk:"rebind_protection"`
	Recursion        types.String `tfsdk:"recursion"`
	ResourceLimits   types.String `tfsdk:"resource_limits"`
	TtlMin           types.Int64  `tfsdk:"ttl_min"`
}

func (r *unboundServerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unbound_server"
}

func (r *unboundServerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *unboundServerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Unbound server.",
		Attributes: map[string]schema.Attribute{
			"id":                computedIDAttribute(),
			"managed":           managedAttribute(),
			"etag":              etagAttribute(),
			"add_local_fqdn":    optionalComputedInt64("uci option add_local_fqdn."),
			"add_wan_fqdn":      optionalComputedInt64("uci option add_wan_fqdn."),
			"dhcp_link":         optionalComputedString("uci option dhcp_link."),
			"dnssec_enabled":    optionalComputedBool("uci option dnssec_enabled."),
			"domain":            optionalComputedString("uci option domain."),
			"domain_type":       optionalComputedString("uci option domain_type."),
			"enabled":           optionalComputedBool("Whether the entry is active."),
			"extended_stats":    optionalComputedBool("uci option extended_stats."),
			"hide_binddata":     optionalComputedBool("uci option hide_binddata."),
			"interface_auto":    optionalComputedBool("uci option interface_auto."),
			"listen_port":       optionalComputedInt64("uci option listen_port."),
			"localservice":      optionalComputedBool("uci option localservice."),
			"manual_conf":       optionalComputedBool("uci option manual_conf."),
			"num_threads":       optionalComputedInt64("uci option num_threads."),
			"prefetch":          optionalComputedBool("uci option prefetch."),
			"protocol":          optionalComputedString("uci option protocol."),
			"query_minimize":    optionalComputedBool("uci option query_minimize."),
			"rebind_protection": optionalComputedString("uci option rebind_protection."),
			"recursion":         optionalComputedString("uci option recursion."),
			"resource_limits":   optionalComputedString("uci option resource_limits."),
			"ttl_min":           optionalComputedInt64("uci option ttl_min."),
		},
	}
}

func (r *unboundServerResource) body(ctx context.Context, m unboundServerModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putInt64(out, "add_local_fqdn", m.AddLocalFqdn)
	putInt64(out, "add_wan_fqdn", m.AddWanFqdn)
	putStr(out, "dhcp_link", m.DhcpLink)
	putBool(out, "dnssec_enabled", m.DnssecEnabled)
	putStr(out, "domain", m.Domain)
	putStr(out, "domain_type", m.DomainType)
	putBool(out, "enabled", m.Enabled)
	putBool(out, "extended_stats", m.ExtendedStats)
	putBool(out, "hide_binddata", m.HideBinddata)
	putBool(out, "interface_auto", m.InterfaceAuto)
	putInt64(out, "listen_port", m.ListenPort)
	putBool(out, "localservice", m.Localservice)
	putBool(out, "manual_conf", m.ManualConf)
	putInt64(out, "num_threads", m.NumThreads)
	putBool(out, "prefetch", m.Prefetch)
	putStr(out, "protocol", m.Protocol)
	putBool(out, "query_minimize", m.QueryMinimize)
	putStr(out, "rebind_protection", m.RebindProtection)
	putStr(out, "recursion", m.Recursion)
	putStr(out, "resource_limits", m.ResourceLimits)
	putInt64(out, "ttl_min", m.TtlMin)
	return out
}

func (r *unboundServerResource) read(ctx context.Context, obj map[string]any, m *unboundServerModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.AddLocalFqdn = int64Val(obj, "add_local_fqdn")
	m.AddWanFqdn = int64Val(obj, "add_wan_fqdn")
	m.DhcpLink = strVal(obj, "dhcp_link")
	m.DnssecEnabled = boolVal(obj, "dnssec_enabled")
	m.Domain = strVal(obj, "domain")
	m.DomainType = strVal(obj, "domain_type")
	m.Enabled = boolVal(obj, "enabled")
	m.ExtendedStats = boolVal(obj, "extended_stats")
	m.HideBinddata = boolVal(obj, "hide_binddata")
	m.InterfaceAuto = boolVal(obj, "interface_auto")
	m.ListenPort = int64Val(obj, "listen_port")
	m.Localservice = boolVal(obj, "localservice")
	m.ManualConf = boolVal(obj, "manual_conf")
	m.NumThreads = int64Val(obj, "num_threads")
	m.Prefetch = boolVal(obj, "prefetch")
	m.Protocol = strVal(obj, "protocol")
	m.QueryMinimize = boolVal(obj, "query_minimize")
	m.RebindProtection = strVal(obj, "rebind_protection")
	m.Recursion = strVal(obj, "recursion")
	m.ResourceLimits = strVal(obj, "resource_limits")
	m.TtlMin = int64Val(obj, "ttl_min")
}

func (r *unboundServerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan unboundServerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, unboundServerPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "unbound server", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *unboundServerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state unboundServerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, unboundServerPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading unbound server", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *unboundServerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state unboundServerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, unboundServerPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "unbound server", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *unboundServerResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *unboundServerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
