// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const unboundSrvPath = "/unbound/srv"

var (
	_ resource.Resource                = &unboundSrvResource{}
	_ resource.ResourceWithConfigure   = &unboundSrvResource{}
	_ resource.ResourceWithImportState = &unboundSrvResource{}
)

type unboundSrvResource struct{ client *client.Client }

func NewUnboundSrvResource() resource.Resource { return &unboundSrvResource{} }

type unboundSrvModel struct {
	ID                types.String `tfsdk:"id"`
	Managed           types.Bool   `tfsdk:"managed"`
	ETag              types.String `tfsdk:"etag"`
	Enabled           types.Bool   `tfsdk:"enabled"`
	InterfaceBind     types.List   `tfsdk:"interface_bind"`
	InterfaceOutgoing types.List   `tfsdk:"interface_outgoing"`
	IpTransparent     types.Bool   `tfsdk:"ip_transparent"`
	SrvLine           types.List   `tfsdk:"srv_line"`
}

func (r *unboundSrvResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unbound_srv"
}

func (r *unboundSrvResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *unboundSrvResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Unbound srv options.",
		Attributes: map[string]schema.Attribute{
			"id":                 computedIDAttribute(),
			"managed":            managedAttribute(),
			"etag":               etagAttribute(),
			"enabled":            optionalComputedBool("Whether the entry is active."),
			"interface_bind":     optionalComputedStringList("Addresses unbound binds on (`addr` or `addr@port`). Pair with the main unbound `interface_auto = false` for exclusive binding."),
			"interface_outgoing": optionalComputedStringList("Source addresses for upstream recursion (multi-WAN egress)."),
			"ip_transparent":     optionalComputedBool("Bind to addresses that are not yet up (VIP / alias / floating addresses)."),
			"srv_line":           optionalComputedStringList("Verbatim lines inserted inside unbound's `server:` clause. One entry per line; `unbound-checkconf` validates grammar after restart."),
		},
	}
}

func (r *unboundSrvResource) body(ctx context.Context, m unboundSrvModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putBool(out, "enabled", m.Enabled)
	putList(ctx, out, "interface_bind", m.InterfaceBind, diags.d)
	putList(ctx, out, "interface_outgoing", m.InterfaceOutgoing, diags.d)
	putBool(out, "ip_transparent", m.IpTransparent)
	putList(ctx, out, "srv_line", m.SrvLine, diags.d)
	return out
}

func (r *unboundSrvResource) read(ctx context.Context, obj map[string]any, m *unboundSrvModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Enabled = boolVal(obj, "enabled")
	m.InterfaceBind = diags.list(listVal(ctx, obj, "interface_bind"))
	m.InterfaceOutgoing = diags.list(listVal(ctx, obj, "interface_outgoing"))
	m.IpTransparent = boolVal(obj, "ip_transparent")
	m.SrvLine = diags.list(listVal(ctx, obj, "srv_line"))
}

func (r *unboundSrvResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan unboundSrvModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, unboundSrvPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "unbound srv options", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *unboundSrvResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state unboundSrvModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, unboundSrvPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading unbound srv options", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *unboundSrvResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state unboundSrvModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, unboundSrvPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "unbound srv options", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *unboundSrvResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *unboundSrvResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
