// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &unboundServerDataSource{}
	_ datasource.DataSourceWithConfigure = &unboundServerDataSource{}
)

type unboundServerDataSource struct{ client *client.Client }

func NewUnboundServerDataSource() datasource.DataSource { return &unboundServerDataSource{} }

func (d *unboundServerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unbound_server"
}

func (d *unboundServerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *unboundServerDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the unbound server.",
		Attributes: map[string]dsschema.Attribute{
			"id":                dsComputedString("Stable id."),
			"managed":           dsManagedAttribute(),
			"etag":              dsComputedString("Opaque ETag of the resource's current state."),
			"add_local_fqdn":    dsComputedInt64("uci option add_local_fqdn."),
			"add_wan_fqdn":      dsComputedInt64("uci option add_wan_fqdn."),
			"dhcp_link":         dsComputedString("uci option dhcp_link."),
			"dnssec_enabled":    dsComputedBool("uci option dnssec_enabled."),
			"domain":            dsComputedString("uci option domain."),
			"domain_type":       dsComputedString("uci option domain_type."),
			"enabled":           dsComputedBool("Whether the entry is active."),
			"extended_stats":    dsComputedBool("uci option extended_stats."),
			"hide_binddata":     dsComputedBool("uci option hide_binddata."),
			"interface_auto":    dsComputedBool("uci option interface_auto."),
			"listen_port":       dsComputedInt64("uci option listen_port."),
			"localservice":      dsComputedBool("uci option localservice."),
			"manual_conf":       dsComputedBool("uci option manual_conf."),
			"num_threads":       dsComputedInt64("uci option num_threads."),
			"prefetch":          dsComputedBool("uci option prefetch."),
			"protocol":          dsComputedString("uci option protocol."),
			"query_minimize":    dsComputedBool("uci option query_minimize."),
			"rebind_protection": dsComputedString("uci option rebind_protection."),
			"recursion":         dsComputedString("uci option recursion."),
			"resource_limits":   dsComputedString("uci option resource_limits."),
			"ttl_min":           dsComputedInt64("uci option ttl_min."),
		},
	}
}

func (d *unboundServerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m unboundServerModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, unboundServerPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading unbound server", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("unbound server not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&unboundServerResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
