// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &usteerConfigDataSource{}
	_ datasource.DataSourceWithConfigure = &usteerConfigDataSource{}
)

type usteerConfigDataSource struct{ client *client.Client }

func NewUsteerConfigDataSource() datasource.DataSource { return &usteerConfigDataSource{} }

func (d *usteerConfigDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_usteer_config"
}

func (d *usteerConfigDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *usteerConfigDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the usteer config.",
		Attributes: map[string]dsschema.Attribute{
			"id":                         dsComputedString("Stable id."),
			"managed":                    dsManagedAttribute(),
			"etag":                       dsComputedString("Opaque ETag of the resource's current state."),
			"assoc_steering":             dsComputedBool("uci option assoc_steering."),
			"band_steering_threshold":    dsComputedInt64("uci option band_steering_threshold."),
			"debug_level":                dsComputedInt64("uci option debug_level."),
			"enabled":                    dsComputedBool("Whether the entry is active."),
			"event_log_types":            dsComputedStringList("uci option event_log_types."),
			"ipv6":                       dsComputedBool("uci option ipv6."),
			"load_balancing_threshold":   dsComputedInt64("uci option load_balancing_threshold."),
			"local_sta_timeout":          dsComputedInt64("uci option local_sta_timeout."),
			"local_sta_update":           dsComputedInt64("uci option local_sta_update."),
			"max_assoc_sta":              dsComputedInt64("uci option max_assoc_sta."),
			"max_neighbor_reports":       dsComputedInt64("uci option max_neighbor_reports."),
			"max_retry_band":             dsComputedInt64("uci option max_retry_band."),
			"measurement_report_timeout": dsComputedInt64("uci option measurement_report_timeout."),
			"min_connect_snr":            dsComputedInt64("uci option min_connect_snr."),
			"min_snr":                    dsComputedInt64("uci option min_snr."),
			"min_snr_kick_delay":         dsComputedInt64("uci option min_snr_kick_delay."),
			"network":                    dsComputedString("uci option network."),
			"node_up_script":             dsComputedString("uci option node_up_script."),
			"remote_node_timeout":        dsComputedInt64("uci option remote_node_timeout."),
			"remote_update_interval":     dsComputedInt64("uci option remote_update_interval."),
			"roam_kick_delay":            dsComputedInt64("uci option roam_kick_delay."),
			"roam_process_timeout":       dsComputedInt64("uci option roam_process_timeout."),
			"roam_scan_interval":         dsComputedInt64("uci option roam_scan_interval."),
			"roam_scan_snr":              dsComputedInt64("uci option roam_scan_snr."),
			"roam_scan_tries":            dsComputedInt64("uci option roam_scan_tries."),
			"roam_trigger_interval":      dsComputedInt64("uci option roam_trigger_interval."),
			"roam_trigger_snr":           dsComputedInt64("uci option roam_trigger_snr."),
			"seen_policy_timeout":        dsComputedInt64("uci option seen_policy_timeout."),
			"signal_diff_threshold":      dsComputedInt64("uci option signal_diff_threshold."),
			"ssid_list":                  dsComputedStringList("uci option ssid_list."),
			"sta_block_timeout":          dsComputedInt64("uci option sta_block_timeout."),
			"syslog":                     dsComputedBool("uci option syslog."),
		},
	}
}

func (d *usteerConfigDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m usteerConfigModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, usteerConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading usteer config", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("usteer config not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&usteerConfigResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
