// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const usteerConfigPath = "/usteer/config"

var (
	_ resource.Resource                = &usteerConfigResource{}
	_ resource.ResourceWithConfigure   = &usteerConfigResource{}
	_ resource.ResourceWithImportState = &usteerConfigResource{}
)

type usteerConfigResource struct{ client *client.Client }

func NewUsteerConfigResource() resource.Resource { return &usteerConfigResource{} }

type usteerConfigModel struct {
	ID                       types.String `tfsdk:"id"`
	Managed                  types.Bool   `tfsdk:"managed"`
	ETag                     types.String `tfsdk:"etag"`
	AssocSteering            types.Bool   `tfsdk:"assoc_steering"`
	BandSteeringThreshold    types.Int64  `tfsdk:"band_steering_threshold"`
	DebugLevel               types.Int64  `tfsdk:"debug_level"`
	Enabled                  types.Bool   `tfsdk:"enabled"`
	EventLogTypes            types.List   `tfsdk:"event_log_types"`
	Ipv6                     types.Bool   `tfsdk:"ipv6"`
	LoadBalancingThreshold   types.Int64  `tfsdk:"load_balancing_threshold"`
	LocalStaTimeout          types.Int64  `tfsdk:"local_sta_timeout"`
	LocalStaUpdate           types.Int64  `tfsdk:"local_sta_update"`
	MaxAssocSta              types.Int64  `tfsdk:"max_assoc_sta"`
	MaxNeighborReports       types.Int64  `tfsdk:"max_neighbor_reports"`
	MaxRetryBand             types.Int64  `tfsdk:"max_retry_band"`
	MeasurementReportTimeout types.Int64  `tfsdk:"measurement_report_timeout"`
	MinConnectSnr            types.Int64  `tfsdk:"min_connect_snr"`
	MinSnr                   types.Int64  `tfsdk:"min_snr"`
	MinSnrKickDelay          types.Int64  `tfsdk:"min_snr_kick_delay"`
	Network                  types.String `tfsdk:"network"`
	NodeUpScript             types.String `tfsdk:"node_up_script"`
	RemoteNodeTimeout        types.Int64  `tfsdk:"remote_node_timeout"`
	RemoteUpdateInterval     types.Int64  `tfsdk:"remote_update_interval"`
	RoamKickDelay            types.Int64  `tfsdk:"roam_kick_delay"`
	RoamProcessTimeout       types.Int64  `tfsdk:"roam_process_timeout"`
	RoamScanInterval         types.Int64  `tfsdk:"roam_scan_interval"`
	RoamScanSnr              types.Int64  `tfsdk:"roam_scan_snr"`
	RoamScanTries            types.Int64  `tfsdk:"roam_scan_tries"`
	RoamTriggerInterval      types.Int64  `tfsdk:"roam_trigger_interval"`
	RoamTriggerSnr           types.Int64  `tfsdk:"roam_trigger_snr"`
	SeenPolicyTimeout        types.Int64  `tfsdk:"seen_policy_timeout"`
	SignalDiffThreshold      types.Int64  `tfsdk:"signal_diff_threshold"`
	SsidList                 types.List   `tfsdk:"ssid_list"`
	StaBlockTimeout          types.Int64  `tfsdk:"sta_block_timeout"`
	Syslog                   types.Bool   `tfsdk:"syslog"`
}

func (r *usteerConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_usteer_config"
}

func (r *usteerConfigResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *usteerConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Usteer config.",
		Attributes: map[string]schema.Attribute{
			"id":                         computedIDAttribute(),
			"managed":                    managedAttribute(),
			"etag":                       etagAttribute(),
			"assoc_steering":             optionalComputedBool("uci option assoc_steering."),
			"band_steering_threshold":    optionalComputedInt64("uci option band_steering_threshold."),
			"debug_level":                optionalComputedInt64("uci option debug_level."),
			"enabled":                    optionalComputedBool("Whether the entry is active."),
			"event_log_types":            optionalComputedStringList("uci option event_log_types."),
			"ipv6":                       optionalComputedBool("uci option ipv6."),
			"load_balancing_threshold":   optionalComputedInt64("uci option load_balancing_threshold."),
			"local_sta_timeout":          optionalComputedInt64("uci option local_sta_timeout."),
			"local_sta_update":           optionalComputedInt64("uci option local_sta_update."),
			"max_assoc_sta":              optionalComputedInt64("uci option max_assoc_sta."),
			"max_neighbor_reports":       optionalComputedInt64("uci option max_neighbor_reports."),
			"max_retry_band":             optionalComputedInt64("uci option max_retry_band."),
			"measurement_report_timeout": optionalComputedInt64("uci option measurement_report_timeout."),
			"min_connect_snr":            optionalComputedInt64("uci option min_connect_snr."),
			"min_snr":                    optionalComputedInt64("uci option min_snr."),
			"min_snr_kick_delay":         optionalComputedInt64("uci option min_snr_kick_delay."),
			"network":                    optionalComputedString("uci option network."),
			"node_up_script":             optionalComputedString("uci option node_up_script."),
			"remote_node_timeout":        optionalComputedInt64("uci option remote_node_timeout."),
			"remote_update_interval":     optionalComputedInt64("uci option remote_update_interval."),
			"roam_kick_delay":            optionalComputedInt64("uci option roam_kick_delay."),
			"roam_process_timeout":       optionalComputedInt64("uci option roam_process_timeout."),
			"roam_scan_interval":         optionalComputedInt64("uci option roam_scan_interval."),
			"roam_scan_snr":              optionalComputedInt64("uci option roam_scan_snr."),
			"roam_scan_tries":            optionalComputedInt64("uci option roam_scan_tries."),
			"roam_trigger_interval":      optionalComputedInt64("uci option roam_trigger_interval."),
			"roam_trigger_snr":           optionalComputedInt64("uci option roam_trigger_snr."),
			"seen_policy_timeout":        optionalComputedInt64("uci option seen_policy_timeout."),
			"signal_diff_threshold":      optionalComputedInt64("uci option signal_diff_threshold."),
			"ssid_list":                  optionalComputedStringList("uci option ssid_list."),
			"sta_block_timeout":          optionalComputedInt64("uci option sta_block_timeout."),
			"syslog":                     optionalComputedBool("uci option syslog."),
		},
	}
}

func (r *usteerConfigResource) body(ctx context.Context, m usteerConfigModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putBool(out, "assoc_steering", m.AssocSteering)
	putInt64(out, "band_steering_threshold", m.BandSteeringThreshold)
	putInt64(out, "debug_level", m.DebugLevel)
	putBool(out, "enabled", m.Enabled)
	putList(ctx, out, "event_log_types", m.EventLogTypes, diags.d)
	putBool(out, "ipv6", m.Ipv6)
	putInt64(out, "load_balancing_threshold", m.LoadBalancingThreshold)
	putInt64(out, "local_sta_timeout", m.LocalStaTimeout)
	putInt64(out, "local_sta_update", m.LocalStaUpdate)
	putInt64(out, "max_assoc_sta", m.MaxAssocSta)
	putInt64(out, "max_neighbor_reports", m.MaxNeighborReports)
	putInt64(out, "max_retry_band", m.MaxRetryBand)
	putInt64(out, "measurement_report_timeout", m.MeasurementReportTimeout)
	putInt64(out, "min_connect_snr", m.MinConnectSnr)
	putInt64(out, "min_snr", m.MinSnr)
	putInt64(out, "min_snr_kick_delay", m.MinSnrKickDelay)
	putStr(out, "network", m.Network)
	putStr(out, "node_up_script", m.NodeUpScript)
	putInt64(out, "remote_node_timeout", m.RemoteNodeTimeout)
	putInt64(out, "remote_update_interval", m.RemoteUpdateInterval)
	putInt64(out, "roam_kick_delay", m.RoamKickDelay)
	putInt64(out, "roam_process_timeout", m.RoamProcessTimeout)
	putInt64(out, "roam_scan_interval", m.RoamScanInterval)
	putInt64(out, "roam_scan_snr", m.RoamScanSnr)
	putInt64(out, "roam_scan_tries", m.RoamScanTries)
	putInt64(out, "roam_trigger_interval", m.RoamTriggerInterval)
	putInt64(out, "roam_trigger_snr", m.RoamTriggerSnr)
	putInt64(out, "seen_policy_timeout", m.SeenPolicyTimeout)
	putInt64(out, "signal_diff_threshold", m.SignalDiffThreshold)
	putList(ctx, out, "ssid_list", m.SsidList, diags.d)
	putInt64(out, "sta_block_timeout", m.StaBlockTimeout)
	putBool(out, "syslog", m.Syslog)
	return out
}

func (r *usteerConfigResource) read(ctx context.Context, obj map[string]any, m *usteerConfigModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.AssocSteering = boolVal(obj, "assoc_steering")
	m.BandSteeringThreshold = int64Val(obj, "band_steering_threshold")
	m.DebugLevel = int64Val(obj, "debug_level")
	m.Enabled = boolVal(obj, "enabled")
	m.EventLogTypes = diags.list(listVal(ctx, obj, "event_log_types"))
	m.Ipv6 = boolVal(obj, "ipv6")
	m.LoadBalancingThreshold = int64Val(obj, "load_balancing_threshold")
	m.LocalStaTimeout = int64Val(obj, "local_sta_timeout")
	m.LocalStaUpdate = int64Val(obj, "local_sta_update")
	m.MaxAssocSta = int64Val(obj, "max_assoc_sta")
	m.MaxNeighborReports = int64Val(obj, "max_neighbor_reports")
	m.MaxRetryBand = int64Val(obj, "max_retry_band")
	m.MeasurementReportTimeout = int64Val(obj, "measurement_report_timeout")
	m.MinConnectSnr = int64Val(obj, "min_connect_snr")
	m.MinSnr = int64Val(obj, "min_snr")
	m.MinSnrKickDelay = int64Val(obj, "min_snr_kick_delay")
	m.Network = strVal(obj, "network")
	m.NodeUpScript = strVal(obj, "node_up_script")
	m.RemoteNodeTimeout = int64Val(obj, "remote_node_timeout")
	m.RemoteUpdateInterval = int64Val(obj, "remote_update_interval")
	m.RoamKickDelay = int64Val(obj, "roam_kick_delay")
	m.RoamProcessTimeout = int64Val(obj, "roam_process_timeout")
	m.RoamScanInterval = int64Val(obj, "roam_scan_interval")
	m.RoamScanSnr = int64Val(obj, "roam_scan_snr")
	m.RoamScanTries = int64Val(obj, "roam_scan_tries")
	m.RoamTriggerInterval = int64Val(obj, "roam_trigger_interval")
	m.RoamTriggerSnr = int64Val(obj, "roam_trigger_snr")
	m.SeenPolicyTimeout = int64Val(obj, "seen_policy_timeout")
	m.SignalDiffThreshold = int64Val(obj, "signal_diff_threshold")
	m.SsidList = diags.list(listVal(ctx, obj, "ssid_list"))
	m.StaBlockTimeout = int64Val(obj, "sta_block_timeout")
	m.Syslog = boolVal(obj, "syslog")
}

func (r *usteerConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan usteerConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, usteerConfigPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "usteer config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *usteerConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state usteerConfigModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, usteerConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading usteer config", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *usteerConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state usteerConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, usteerConfigPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "usteer config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *usteerConfigResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *usteerConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
