// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &vnstatInterfaceDataSource{}
	_ datasource.DataSourceWithConfigure = &vnstatInterfaceDataSource{}
)

type vnstatInterfaceDataSource struct{ client *client.Client }

func NewVnstatInterfaceDataSource() datasource.DataSource { return &vnstatInterfaceDataSource{} }

func (d *vnstatInterfaceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_vnstat_interface"
}

func (d *vnstatInterfaceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *vnstatInterfaceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the vnstat interface.",
		Attributes: map[string]dsschema.Attribute{
			"id":        dsIDAttribute(),
			"managed":   dsManagedAttribute(),
			"etag":      dsComputedString("Opaque ETag of the resource's current state."),
			"enabled":   dsComputedBool("Whether the entry is active."),
			"interface": dsComputedString("Network interface this entry applies to."),
		},
	}
}

func (d *vnstatInterfaceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m vnstatInterfaceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+vnstatInterfaceCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading vnstat interface", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("vnstat interface not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&vnstatInterfaceResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
