// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/raspbeguy/terraform-provider-uapi/internal/client"
)

const vnstatConfigPath = "/vnstat/config"

var (
	_ resource.Resource                = &vnstatConfigResource{}
	_ resource.ResourceWithConfigure   = &vnstatConfigResource{}
	_ resource.ResourceWithImportState = &vnstatConfigResource{}
)

type vnstatConfigResource struct{ client *client.Client }

func NewVnstatConfigResource() resource.Resource { return &vnstatConfigResource{} }

type vnstatConfigModel struct {
	ID                 types.String `tfsdk:"id"`
	Managed            types.Bool   `tfsdk:"managed"`
	ETag               types.String `tfsdk:"etag"`
	DatabaseDir        types.String `tfsdk:"database_dir"`
	Interface5minHours types.Int64  `tfsdk:"interface_5min_hours"`
	MonthRotate        types.Int64  `tfsdk:"month_rotate"`
}

func (r *vnstatConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_vnstat_config"
}

func (r *vnstatConfigResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *vnstatConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A vnstat config.",
		Attributes: map[string]schema.Attribute{
			"id":                   computedIDAttribute(),
			"managed":              managedAttribute(),
			"etag":                 etagAttribute(),
			"database_dir":         optionalComputedString("uci option database_dir."),
			"interface_5min_hours": optionalComputedInt64("uci option interface_5min_hours."),
			"month_rotate":         optionalComputedInt64("uci option month_rotate."),
		},
	}
}

func (r *vnstatConfigResource) body(ctx context.Context, m vnstatConfigModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	putStr(out, "database_dir", m.DatabaseDir)
	putInt64(out, "interface_5min_hours", m.Interface5minHours)
	putInt64(out, "month_rotate", m.MonthRotate)
	return out
}

func (r *vnstatConfigResource) read(ctx context.Context, obj map[string]any, m *vnstatConfigModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.DatabaseDir = strVal(obj, "database_dir")
	m.Interface5minHours = int64Val(obj, "interface_5min_hours")
	m.MonthRotate = int64Val(obj, "month_rotate")
}

func (r *vnstatConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan vnstatConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, vnstatConfigPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "vnstat config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *vnstatConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state vnstatConfigModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, vnstatConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading vnstat config", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *vnstatConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state vnstatConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, vnstatConfigPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "vnstat config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *vnstatConfigResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *vnstatConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
