// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &vnstatConfigDataSource{}
	_ datasource.DataSourceWithConfigure = &vnstatConfigDataSource{}
)

type vnstatConfigDataSource struct{ client *client.Client }

func NewVnstatConfigDataSource() datasource.DataSource { return &vnstatConfigDataSource{} }

func (d *vnstatConfigDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_vnstat_config"
}

func (d *vnstatConfigDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *vnstatConfigDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the vnstat config.",
		Attributes: map[string]dsschema.Attribute{
			"id":                   dsComputedString("Stable id."),
			"managed":              dsManagedAttribute(),
			"etag":                 dsComputedString("Opaque ETag of the resource's current state."),
			"database_dir":         dsComputedString("uci option database_dir."),
			"interface_5min_hours": dsComputedInt64("uci option interface_5min_hours."),
			"month_rotate":         dsComputedInt64("uci option month_rotate."),
		},
	}
}

func (d *vnstatConfigDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m vnstatConfigModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, vnstatConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading vnstat config", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("vnstat config not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&vnstatConfigResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
