// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

type wirelessInterfaceDSModel struct {
	ID         types.String                   `tfsdk:"id"`
	Managed    types.Bool                     `tfsdk:"managed"`
	ETag       types.String                   `tfsdk:"etag"`
	Device     types.String                   `tfsdk:"device"`
	Disabled   types.Bool                     `tfsdk:"disabled"`
	Encryption types.String                   `tfsdk:"encryption"`
	HasKey     types.Bool                     `tfsdk:"has_key"`
	Hidden     types.Bool                     `tfsdk:"hidden"`
	Isolate    types.Bool                     `tfsdk:"isolate"`
	Key        types.String                   `tfsdk:"key"`
	Mode       types.String                   `tfsdk:"mode"`
	Network    types.String                   `tfsdk:"network"`
	Ssid       types.String                   `tfsdk:"ssid"`
	Runtime    *wirelessInterfaceRuntimeModel `tfsdk:"runtime"`
}

var (
	_ datasource.DataSource              = &wirelessInterfaceDataSource{}
	_ datasource.DataSourceWithConfigure = &wirelessInterfaceDataSource{}
)

type wirelessInterfaceDataSource struct{ client *client.Client }

func NewWirelessInterfaceDataSource() datasource.DataSource { return &wirelessInterfaceDataSource{} }

func (d *wirelessInterfaceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_interface"
}

func (d *wirelessInterfaceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *wirelessInterfaceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the wireless interface.",
		Attributes: map[string]dsschema.Attribute{
			"id":         dsIDAttribute(),
			"managed":    dsManagedAttribute(),
			"etag":       dsComputedString("Opaque ETag of the resource's current state."),
			"device":     dsComputedString("Underlying device."),
			"disabled":   dsComputedBool("Whether the entry is disabled."),
			"encryption": dsComputedString("uci option encryption."),
			"has_key":    dsComputedBool("Whether a key is configured (the value is never returned)."),
			"hidden":     dsComputedBool("uci option hidden."),
			"isolate":    dsComputedBool("uci option isolate."),
			"key":        dsschema.StringAttribute{Computed: true, Sensitive: true, Description: "Always null; never returned by the API."},
			"mode":       dsComputedString("uci option mode."),
			"network":    dsComputedString("uci option network."),
			"ssid":       dsComputedString("uci option ssid."),
			"runtime":    wirelessInterfaceRuntimeAttribute(),
		},
	}
}

func (d *wirelessInterfaceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var id types.String
	resp.Diagnostics.Append(req.Config.GetAttribute(ctx, path.Root("id"), &id)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+wirelessInterfaceCollection+"/"+id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading wireless interface", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("wireless interface not found", "not found")
		return
	}
	var base wirelessInterfaceModel
	ds := newDiagsink(&resp.Diagnostics)
	(&wirelessInterfaceResource{}).read(ctx, obj, &base, ds)
	base.ETag = types.StringValue(etag)
	m := wirelessInterfaceDSModel{
		ID: base.ID, Managed: base.Managed, ETag: base.ETag,
		Device:     base.Device,
		Disabled:   base.Disabled,
		Encryption: base.Encryption,
		HasKey:     base.HasKey,
		Hidden:     base.Hidden,
		Isolate:    base.Isolate,
		Key:        base.Key,
		Mode:       base.Mode,
		Network:    base.Network,
		Ssid:       base.Ssid,
		Runtime:    parseWirelessInterfaceRuntime(obj),
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
