// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const wirelessDeviceCollection = "wireless/devices"

var (
	_ resource.Resource                = &wirelessDeviceResource{}
	_ resource.ResourceWithConfigure   = &wirelessDeviceResource{}
	_ resource.ResourceWithImportState = &wirelessDeviceResource{}
)

type wirelessDeviceResource struct{ client *client.Client }

func NewWirelessDeviceResource() resource.Resource { return &wirelessDeviceResource{} }

type wirelessDeviceModel struct {
	ID       types.String `tfsdk:"id"`
	Managed  types.Bool   `tfsdk:"managed"`
	ETag     types.String `tfsdk:"etag"`
	Band     types.String `tfsdk:"band"`
	Channel  types.Int64  `tfsdk:"channel"`
	Country  types.String `tfsdk:"country"`
	Disabled types.Bool   `tfsdk:"disabled"`
	Htmode   types.String `tfsdk:"htmode"`
	Txpower  types.Int64  `tfsdk:"txpower"`
	Type     types.String `tfsdk:"type"`
}

func (r *wirelessDeviceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_device"
}

func (r *wirelessDeviceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *wirelessDeviceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Wireless device.",
		Attributes: map[string]schema.Attribute{
			"id":       computedIDAttribute(),
			"managed":  managedAttribute(),
			"etag":     etagAttribute(),
			"band":     optionalComputedString("uci option band."),
			"channel":  optionalComputedInt64("uci option channel."),
			"country":  optionalComputedString("uci option country."),
			"disabled": optionalComputedBool("Whether the entry is disabled."),
			"htmode":   optionalComputedString("uci option htmode."),
			"txpower":  optionalComputedInt64("uci option txpower."),
			"type":     schema.StringAttribute{Required: true, Description: "uci option type."},
		},
	}
}

func (r *wirelessDeviceResource) body(ctx context.Context, m wirelessDeviceModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "band", m.Band)
	putInt64(out, "channel", m.Channel)
	putStr(out, "country", m.Country)
	putBool(out, "disabled", m.Disabled)
	putStr(out, "htmode", m.Htmode)
	putInt64(out, "txpower", m.Txpower)
	putStr(out, "type", m.Type)
	return out
}

func (r *wirelessDeviceResource) read(ctx context.Context, obj map[string]any, m *wirelessDeviceModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Band = strVal(obj, "band")
	m.Channel = int64Val(obj, "channel")
	m.Country = strVal(obj, "country")
	m.Disabled = boolVal(obj, "disabled")
	m.Htmode = strVal(obj, "htmode")
	m.Txpower = int64Val(obj, "txpower")
	m.Type = strVal(obj, "type")
}

func (r *wirelessDeviceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan wirelessDeviceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+wirelessDeviceCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "wireless device", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *wirelessDeviceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state wirelessDeviceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+wirelessDeviceCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading wireless device", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *wirelessDeviceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state wirelessDeviceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+wirelessDeviceCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "wireless device", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *wirelessDeviceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state wirelessDeviceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+wirelessDeviceCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "wireless device", err)
	}
}

func (r *wirelessDeviceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, wirelessDeviceCollection, "wireless device", req, resp)
}
