// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const wirelessInterfaceCollection = "wireless/interfaces"

var (
	_ resource.Resource                = &wirelessInterfaceResource{}
	_ resource.ResourceWithConfigure   = &wirelessInterfaceResource{}
	_ resource.ResourceWithImportState = &wirelessInterfaceResource{}
)

type wirelessInterfaceResource struct{ client *client.Client }

func NewWirelessInterfaceResource() resource.Resource { return &wirelessInterfaceResource{} }

type wirelessInterfaceModel struct {
	ID         types.String `tfsdk:"id"`
	Managed    types.Bool   `tfsdk:"managed"`
	ETag       types.String `tfsdk:"etag"`
	Device     types.String `tfsdk:"device"`
	Disabled   types.Bool   `tfsdk:"disabled"`
	Encryption types.String `tfsdk:"encryption"`
	HasKey     types.Bool   `tfsdk:"has_key"`
	Hidden     types.Bool   `tfsdk:"hidden"`
	Isolate    types.Bool   `tfsdk:"isolate"`
	Key        types.String `tfsdk:"key"`
	Mode       types.String `tfsdk:"mode"`
	Network    types.String `tfsdk:"network"`
	Ssid       types.String `tfsdk:"ssid"`
}

func (r *wirelessInterfaceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_interface"
}

func (r *wirelessInterfaceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *wirelessInterfaceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Wireless interface.",
		Attributes: map[string]schema.Attribute{
			"id":         computedIDAttribute(),
			"managed":    managedAttribute(),
			"etag":       etagAttribute(),
			"device":     schema.StringAttribute{Required: true, Description: "Underlying device."},
			"disabled":   optionalComputedBool("Whether the entry is disabled."),
			"encryption": optionalComputedString("uci option encryption."),
			"has_key":    schema.BoolAttribute{Computed: true, Description: "Whether a key is configured (the value is never returned)."},
			"hidden":     optionalComputedBool("uci option hidden."),
			"isolate":    optionalComputedBool("uci option isolate."),
			"key":        schema.StringAttribute{Optional: true, Sensitive: true, Description: "Encryption passphrase. Write-only: never returned by the API."},
			"mode":       optionalComputedString("uci option mode."),
			"network":    optionalComputedString("uci option network."),
			"ssid":       optionalComputedString("uci option ssid."),
		},
	}
}

func (r *wirelessInterfaceResource) body(ctx context.Context, m wirelessInterfaceModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "device", m.Device)
	putBool(out, "disabled", m.Disabled)
	putStr(out, "encryption", m.Encryption)
	putBool(out, "hidden", m.Hidden)
	putBool(out, "isolate", m.Isolate)
	putStr(out, "key", m.Key)
	putStr(out, "mode", m.Mode)
	putStr(out, "network", m.Network)
	putStr(out, "ssid", m.Ssid)
	return out
}

func (r *wirelessInterfaceResource) read(ctx context.Context, obj map[string]any, m *wirelessInterfaceModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Device = strVal(obj, "device")
	m.Disabled = boolVal(obj, "disabled")
	m.Encryption = strVal(obj, "encryption")
	m.HasKey = boolValDefault(obj, "has_key")
	m.Hidden = boolVal(obj, "hidden")
	m.Isolate = boolVal(obj, "isolate")
	// key is write-only: preserve the planned value (the API never returns it).
	m.Mode = strVal(obj, "mode")
	m.Network = strVal(obj, "network")
	m.Ssid = strVal(obj, "ssid")
}

func (r *wirelessInterfaceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan wirelessInterfaceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+wirelessInterfaceCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "wireless interface", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *wirelessInterfaceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state wirelessInterfaceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+wirelessInterfaceCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading wireless interface", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *wirelessInterfaceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state wirelessInterfaceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+wirelessInterfaceCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "wireless interface", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *wirelessInterfaceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state wirelessInterfaceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+wirelessInterfaceCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "wireless interface", err)
	}
}

func (r *wirelessInterfaceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, wirelessInterfaceCollection, "wireless interface", req, resp)
}
