// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &wirelessDeviceDataSource{}
	_ datasource.DataSourceWithConfigure = &wirelessDeviceDataSource{}
)

type wirelessDeviceDataSource struct{ client *client.Client }

func NewWirelessDeviceDataSource() datasource.DataSource { return &wirelessDeviceDataSource{} }

func (d *wirelessDeviceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_device"
}

func (d *wirelessDeviceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *wirelessDeviceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the wireless device.",
		Attributes: map[string]dsschema.Attribute{
			"id":       dsIDAttribute(),
			"managed":  dsManagedAttribute(),
			"etag":     dsComputedString("Opaque ETag of the resource's current state."),
			"band":     dsComputedString("uci option band."),
			"channel":  dsComputedInt64("uci option channel."),
			"country":  dsComputedString("uci option country."),
			"disabled": dsComputedBool("Whether the entry is disabled."),
			"htmode":   dsComputedString("uci option htmode."),
			"txpower":  dsComputedInt64("uci option txpower."),
			"type":     dsComputedString("uci option type."),
		},
	}
}

func (d *wirelessDeviceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m wirelessDeviceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+wirelessDeviceCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading wireless device", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("wireless device not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&wirelessDeviceResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
